# Generated by Django 5.1.1 on 2025-03-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_options_alter_subject_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='acted_subjects',
        ),
    ]
