# Generated by Django 6.0.1 on 2026-03-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier slug, e.g. 'acted_main'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="External-facing name, e.g. 'THE ACTUARIAL EDUCATION COMPANY (ActEd)'",
                        max_length=200,
                    ),
                ),
                (
                    "default_sign_off_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default sign-off for salutations, e.g. 'Kind Regards'",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": '"acted"."team"',
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="staff.staff",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_staff",
                        to="staff.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Staff",
                "verbose_name_plural": "Team Staff",
                "db_table": '"acted"."team_staff"',
                "unique_together": {("team", "staff")},
            },
        ),
    ]
