# Generated by Django 6.0.1 on 2026-03-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_create_team_and_team_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="name_format",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="show_job_title",
        ),
    ]
