# Generated by Django 6.0.1 on 2026-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_remove_name_format_show_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="initials",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Short initials used to identify staff in legacy systems",
                max_length=10,
            ),
        ),
    ]
