# Generated by Django 5.1.1 on 2025-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productvariation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
