# Generated by Django 5.1 on 2024-XX-XX XX:XX

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariation_description_short'),
    ]

    operations = [
        TrigramExtension(),
    ]
