# Generated by Django 5.2.2 on 2025-09-11 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "send_invoices_to",
                    models.CharField(
                        choices=[("HOME", "Home"), ("WORK", "Work")],
                        default="HOME",
                        max_length=8,
                    ),
                ),
                (
                    "send_study_material_to",
                    models.CharField(
                        choices=[("HOME", "Home"), ("WORK", "Work")],
                        default="HOME",
                        max_length=8,
                    ),
                ),
                ("remarks", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "acted_user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserProfileAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[("HOME", "Home"), ("WORK", "Work")], max_length=8
                    ),
                ),
                (
                    "address_data",
                    models.JSONField(
                        default=dict,
                        help_text="Address data in JSON format to support different country address structures",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Country name for easy filtering", max_length=64
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=64, null=True)),
                ("department", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="userprofile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile Address",
                "verbose_name_plural": "User Profile Addresses",
                "db_table": "acted_user_profile_address",
            },
        ),
        migrations.CreateModel(
            name="UserProfileContactNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("WORK", "Work"),
                            ("MOBILE", "Mobile"),
                        ],
                        max_length=8,
                    ),
                ),
                ("number", models.CharField(max_length=32)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_numbers",
                        to="userprofile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile Contact Number",
                "verbose_name_plural": "User Profile Contact Numbers",
                "db_table": "acted_user_profile_contact_number",
            },
        ),
        migrations.CreateModel(
            name="UserProfileEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[("PERSONAL", "Personal"), ("WORK", "Work")],
                        max_length=16,
                    ),
                ),
                ("email", models.EmailField(max_length=128)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="userprofile.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile Email",
                "verbose_name_plural": "User Profile Emails",
                "db_table": "acted_user_profile_email",
            },
        ),
    ]
