# Generated by Django 5.1.1 on 2025-04-24 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=16, null=True)),
                ('send_invoices_to', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work')], default='HOME', max_length=8)),
                ('send_study_material_to', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work')], default='HOME', max_length=8)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActedUserProfileEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('WORK', 'Work')], max_length=16)),
                ('email', models.EmailField(max_length=128)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ActedUserProfileContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('MOBILE', 'Mobile')], max_length=8)),
                ('number', models.CharField(max_length=32)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ActedUserProfileAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work')], max_length=8)),
                ('building', models.CharField(blank=True, max_length=64, null=True)),
                ('street', models.CharField(max_length=64)),
                ('district', models.CharField(blank=True, max_length=64, null=True)),
                ('town', models.CharField(max_length=64)),
                ('county', models.CharField(blank=True, max_length=32, null=True)),
                ('postcode', models.CharField(max_length=16)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(max_length=64)),
                ('company', models.CharField(blank=True, max_length=64, null=True)),
                ('department', models.CharField(blank=True, max_length=64, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='userprofile.userprofile')),
            ],
        ),
    ]
