# Generated by Django 5.1.1 on 2025-04-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acteduserprofileaddress',
            options={'verbose_name': 'User Profile Address', 'verbose_name_plural': 'User Profile Addresses'},
        ),
        migrations.AlterModelOptions(
            name='acteduserprofilecontactnumber',
            options={'verbose_name': 'User Profile Contact Number', 'verbose_name_plural': 'User Profile Contact Numbers'},
        ),
        migrations.AlterModelOptions(
            name='acteduserprofileemail',
            options={'verbose_name': 'User Profile Email', 'verbose_name_plural': 'User Profile Emails'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelTable(
            name='acteduserprofileaddress',
            table='acted_user_profile_address',
        ),
        migrations.AlterModelTable(
            name='acteduserprofilecontactnumber',
            table='acted_user_profile_contact_number',
        ),
        migrations.AlterModelTable(
            name='acteduserprofileemail',
            table='acted_user_profile_email',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='acted_user_profile',
        ),
    ]
