# Generated by Django 5.2.2 on 2025-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilecontactnumber',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text="ISO 3166-1 alpha-2 country code (e.g., 'HK', 'GB')", max_length=2),
        ),
    ]
