# Generated by Django 5.1.1 on 2025-04-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_acteduserprofileaddress_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActedUserProfileAddress',
            new_name='UserProfileAddress',
        ),
        migrations.RenameModel(
            old_name='ActedUserProfileContactNumber',
            new_name='UserProfileContactNumber',
        ),
        migrations.RenameModel(
            old_name='ActedUserProfileEmail',
            new_name='UserProfileEmail',
        ),
    ]
