# Generated by Django 5.2.2 on 2025-08-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_add_json_address_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileaddress",
            name="country",
            field=models.CharField(
                help_text="Country name for easy filtering", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="userprofileaddress",
            name="postcode",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="userprofileaddress",
            name="street",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="userprofileaddress",
            name="town",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
