# Generated by Django 5.2.2 on 2025-08-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_make_legacy_address_fields_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileaddress",
            name="building",
        ),
        migrations.RemoveField(
            model_name="userprofileaddress",
            name="county",
        ),
        migrations.RemoveField(
            model_name="userprofileaddress",
            name="district",
        ),
        migrations.RemoveField(
            model_name="userprofileaddress",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="userprofileaddress",
            name="state",
        ),
        migrations.RemoveField(
            model_name="userprofileaddress",
            name="street",
        ),
        migrations.RemoveField(
            model_name="userprofileaddress",
            name="town",
        ),
    ]
