# Generated by Django 6.0.1 on 2026-04-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_migrate_to_acted_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="userprofilecontactnumber",
            name="number_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="userprofileemail",
            name="email_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
