# Generated by Django 6.0.1 on 2026-01-25 18:30
# Modified: Table created by catalog.0002_create_models.
# Uses SeparateDatabaseAndState to register model without creating table.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_create_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ExamSession",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "session_code",
                            models.CharField(
                                help_text="Unique session identifier (e.g., 2025-04 for April 2025)",
                                max_length=50,
                            ),
                        ),
                        (
                            "start_date",
                            models.DateTimeField(
                                help_text="Start date of the exam session period"
                            ),
                        ),
                        (
                            "end_date",
                            models.DateTimeField(
                                help_text="End date of the exam session period"
                            ),
                        ),
                        ("create_date", models.DateTimeField(auto_now_add=True)),
                        ("modified_date", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Exam Session",
                        "verbose_name_plural": "Exam Sessions",
                        "db_table": '"acted"."catalog_exam_sessions"',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
