# Generated by Django 6.0.1 on 2026-05-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_exam_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsession",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this exam session is active for sale (default off; activate via management command)",
            ),
        ),
    ]
