# Generated by Django 5.1.1 on 2025-03-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examsession',
            table='acted_exam_sessions',
        ),
    ]
