# Generated by Django 5.1.1 on 2025-04-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_sessions_subjects', '0001_initial'),
        ('products', '0003_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSessionSubjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_session_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_sessions_subjects.examsessionsubject')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Exam Session Subject Product',
                'verbose_name_plural': 'Exam Session Subject Products',
                'db_table': 'acted_exam_session_subject_products',
                'unique_together': {('exam_session_subject', 'product')},
            },
        ),
    ]
