# Generated by Django 5.2.2 on 2025-09-11 11:30
# Updated: 2026-01-14 - Changed FK references from legacy apps to catalog

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0006_add_exam_session_subject"),  # ExamSessionSubject, Product, ProductBundle
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSessionSubjectBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this bundle is currently available for the exam session",
                    ),
                ),
                (
                    "override_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional override for the bundle name (defaults to master bundle name)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "override_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional override for the bundle description",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which to display this bundle for the exam session",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle",
                    models.ForeignKey(
                        help_text="The master bundle template this is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_session_bundles",
                        to="catalog.productbundle",
                    ),
                ),
                (
                    "exam_session_subject",
                    models.ForeignKey(
                        help_text="The specific exam session and subject this bundle is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="catalog.examsessionsubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Session Subject Bundle",
                "verbose_name_plural": "Exam Session Subject Bundles",
                "db_table": "acted_exam_session_subject_bundles",
                "ordering": [
                    "exam_session_subject__exam_session__session_code",
                    "display_order",
                    "bundle__bundle_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="ExamSessionSubjectProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_session_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.examsessionsubject",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Session Subject Product",
                "verbose_name_plural": "Exam Session Subject Products",
                "db_table": "acted_exam_session_subject_products",
                "unique_together": {("exam_session_subject", "product")},
            },
        ),
        migrations.CreateModel(
            name="ExamSessionSubjectProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated product code for this variation",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_session_subject_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="exam_sessions_subjects_products.examsessionsubjectproduct",
                    ),
                ),
                (
                    "product_product_variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.productproductvariation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Session Subject Product Variation",
                "verbose_name_plural": "Exam Session Subject Product Variations",
                "db_table": "acted_exam_session_subject_product_variations",
                "unique_together": {
                    ("exam_session_subject_product", "product_product_variation")
                },
            },
        ),
        migrations.CreateModel(
            name="ExamSessionSubjectBundleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_price_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("retaker", "Retaker"),
                            ("additional", "Additional Copy"),
                        ],
                        default="standard",
                        help_text="Default price type for this product when added via bundle",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of this product to add when bundle is selected",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of this product within the bundle",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this product is currently active in the bundle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle",
                    models.ForeignKey(
                        help_text="The exam session bundle this product belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_products",
                        to="exam_sessions_subjects_products.examsessionsubjectbundle",
                    ),
                ),
                (
                    "exam_session_subject_product_variation",
                    models.ForeignKey(
                        help_text="The specific exam session product variation included in the bundle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_sessions_subjects_products.examsessionsubjectproductvariation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Session Bundle Product",
                "verbose_name_plural": "Exam Session Bundle Products",
                "db_table": "acted_exam_session_subject_bundle_products",
                "ordering": [
                    "sort_order",
                    "exam_session_subject_product_variation__exam_session_subject_product__product__shortname",
                ],
                "unique_together": {
                    ("bundle", "exam_session_subject_product_variation")
                },
            },
        ),
        migrations.AddField(
            model_name="examsessionsubjectbundle",
            name="product_variations",
            field=models.ManyToManyField(
                help_text="Exam session product variations included in this bundle",
                related_name="bundles",
                through="exam_sessions_subjects_products.ExamSessionSubjectBundleProduct",
                to="exam_sessions_subjects_products.examsessionsubjectproductvariation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examsessionsubjectbundle",
            unique_together={("bundle", "exam_session_subject")},
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("retaker", "Retaker"),
                            ("reduced", "Reduced Rate"),
                            ("additional", "Additional Copy"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GBP", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="exam_sessions_subjects_products.examsessionsubjectproductvariation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
                "db_table": "acted_exam_session_subject_product_variation_price",
                "unique_together": {("variation", "price_type")},
            },
        ),
    ]
