# Generated by Django 5.2.2 on 2026-01-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_copy_data"),
        ("exam_sessions_subjects_products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsessionsubjectbundle",
            name="bundle",
            field=models.ForeignKey(
                help_text="The master bundle template this is based on",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_session_bundles",
                to="catalog.productbundle",
            ),
        ),
        migrations.AlterField(
            model_name="examsessionsubjectproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
            ),
        ),
        migrations.AlterField(
            model_name="examsessionsubjectproductvariation",
            name="product_product_variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.productproductvariation",
            ),
        ),
    ]
