# Generated by Django 5.1.1 on 2025-05-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions_subjects_products', '0001_initial'),
        ('products', '0002_remove_productvariation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSessionSubjectProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_session_subject_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='exam_sessions_subjects_products.examsessionsubjectproduct')),
                ('product_product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productproductvariation')),
            ],
            options={
                'verbose_name': 'Exam Session Subject Product Variation',
                'verbose_name_plural': 'Exam Session Subject Product Variations',
                'db_table': 'acted_exam_session_subject_product_variations',
                'unique_together': {('exam_session_subject_product', 'product_product_variation')},
            },
        ),
    ]
