# Generated by Django 5.1.1 on 2025-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions_subjects_products', '0002_examsessionsubjectproductvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsessionsubjectproductvariation',
            name='product_code',
            field=models.CharField(blank=True, help_text='Auto-generated product code for this variation', max_length=64, null=True),
        ),
    ]
