# Generated by Django 5.1.1 on 2025-05-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions_subjects_products', '0004_create_acted_current_product_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='exam_sessions_subjects_products.examsessionsubjectproductvariation')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'acted_exam_session_subject_product_variation_price',
            },
        ),
    ]
