# Generated by Django 5.1.1 on 2025-05-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions_subjects_products', '0005_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('retaker', 'Retaker'), ('reduced', 'Reduced Rate'), ('additional', 'Additional Copy')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='exam_sessions_subjects_products.examsessionsubjectproductvariation'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('variation', 'price_type')},
        ),
    ]
