# Generated by Django 5.1.1 on 2025-03-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customfield',
            new_name='adm.custom__entity__3df6f7_idx',
            old_name='customfield_entity__a50e73_idx',
        ),
        migrations.RenameIndex(
            model_name='customfield',
            new_name='adm.custom__externa_74d36b_idx',
            old_name='customfield_externa_5b4667_idx',
        ),
        migrations.AlterModelTable(
            name='customfield',
            table='adm.custom_fields',
        ),
        migrations.AlterModelTable(
            name='pricelevel',
            table='adm.pricelevels',
        ),
    ]
