# Generated by Django 5.2.2 on 2025-09-03 11:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseTemplatePriceLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("last_synced", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_template",
                    models.ForeignKey(
                        db_column="course_template_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_levels",
                        to="administrate.coursetemplate",
                    ),
                ),
                (
                    "price_level",
                    models.ForeignKey(
                        db_column="price_level_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_template_prices",
                        to="administrate.pricelevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Template Price Level",
                "verbose_name_plural": "Course Template Price Levels",
                "db_table": "adm.course_template_price_levels",
                "ordering": ["course_template", "price_level"],
                "unique_together": {("course_template", "price_level")},
            },
        ),
    ]
