# Generated by Django 5.2.2 on 2025-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfield",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
    ]
