# Generated by Django 5.1.1 on 2025-03-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customfield',
            name='custom_field_extid_idx',
        ),
    ]
