# Generated by Django 5.1.1 on 2025-03-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0002_remove_customfield_custom_field_extid_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('categories', models.TextField(blank=True)),
                ('pricing_band', models.CharField(choices=[('OC', 'Online Classroom'), ('F2F', 'Face-to-face'), ('LO', 'Live Online')], max_length=3)),
                ('learning_mode', models.CharField(choices=[('C', 'Classroom'), ('L', 'LMS'), ('B', 'Blended')], max_length=1)),
                ('ocr_moodle_code', models.CharField(blank=True, max_length=50)),
                ('subject', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Template',
                'verbose_name_plural': 'Course Templates',
                'db_table': 'course_templates',
                'ordering': ['course_code'],
            },
        ),
    ]
