# Generated by Django 5.1.1 on 2025-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0003_coursetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetemplate',
            options={'ordering': ['code'], 'verbose_name': 'Course Template', 'verbose_name_plural': 'Course Templates'},
        ),
        migrations.RenameField(
            model_name='coursetemplate',
            old_name='course_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='coursetemplate',
            name='learning_mode',
        ),
        migrations.RemoveField(
            model_name='coursetemplate',
            name='ocr_moodle_code',
        ),
        migrations.RemoveField(
            model_name='coursetemplate',
            name='pricing_band',
        ),
        migrations.RemoveField(
            model_name='coursetemplate',
            name='subject',
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='event_learning_mode',
            field=models.CharField(blank=True, choices=[('CLASSROOM', 'Classroom'), ('LMS', 'Online'), ('BLENDED', 'Blended')], max_length=20, null=True),
        ),
    ]
