# Generated by Django 5.1.1 on 2025-03-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0004_alter_coursetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursetemplate',
            table='adm.course_templates',
        ),
    ]
