# Generated by Django 6.0.1 on 2026-02-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0004_alter_customfield_roles_to_jsonfield"),
        ("tutorials", "0005_add_fks_to_events_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetemplate",
            name="tutorial_course_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adm_course_templates",
                to="tutorials.tutorialcoursetemplate",
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="tutorial_instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adm_instructors",
                to="tutorials.tutorialinstructor",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="tutorial_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adm_locations",
                to="tutorials.tutoriallocation",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="tutorial_venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adm_venues",
                to="tutorials.tutorialvenue",
            ),
        ),
    ]
