# Generated by Django 6.0.1 on 2026-02-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0005_add_cross_schema_fks_to_acted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursetemplate",
            options={
                "ordering": ["external_id"],
                "verbose_name": "Course Template",
                "verbose_name_plural": "Course Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="instructor",
            options={
                "ordering": ["external_id"],
                "verbose_name": "Instructor",
                "verbose_name_plural": "Instructors",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["external_id"],
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.RemoveField(
            model_name="coursetemplate",
            name="active",
        ),
        migrations.RemoveField(
            model_name="coursetemplate",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="coursetemplate",
            name="code",
        ),
        migrations.RemoveField(
            model_name="coursetemplate",
            name="title",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="location",
            name="active",
        ),
        migrations.RemoveField(
            model_name="location",
            name="code",
        ),
        migrations.RemoveField(
            model_name="location",
            name="name",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="description",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="name",
        ),
    ]
