# Generated by Django 6.0.1 on 2026-02-12 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0006_remove_redundant_adm_columns"),
        ("tutorials", "0010_move_instructors_to_sessions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("session_title", models.CharField(blank=True, max_length=255)),
                (
                    "learning_mode",
                    models.CharField(
                        choices=[
                            ("CLASSROOM", "Face-to-face tuition"),
                            ("BLENDED", "Live Online tuition"),
                            ("LMS", "Online Classroom"),
                        ],
                        default="BLENDED",
                        max_length=20,
                    ),
                ),
                (
                    "tutorial_category",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Tutorials"),
                            ("BLOCK", "Block Tutorials"),
                            ("BUNDLE_5", "5-day Bundle"),
                            ("BUNDLE_6", "6-day Bundle"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                ("administrator", models.CharField(blank=True, max_length=255)),
                ("max_places", models.PositiveIntegerField(default=0)),
                ("min_places", models.PositiveIntegerField(default=0)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("lms_start_date", models.DateTimeField(blank=True, null=True)),
                ("lms_end_date", models.DateTimeField(blank=True, null=True)),
                ("access_duration", models.CharField(blank=True, max_length=100)),
                (
                    "event_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("virtual_classroom", models.CharField(blank=True, max_length=255)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("sold_out", models.BooleanField(default=False)),
                ("cancelled", models.BooleanField(default=False)),
                ("web_sale", models.BooleanField(default=True)),
                ("sitting", models.CharField(blank=True, max_length=50)),
                ("finalisation_date", models.DateTimeField(blank=True, null=True)),
                ("ocr_moodle_code", models.CharField(blank=True, max_length=100)),
                ("sage_code", models.CharField(blank=True, max_length=100)),
                ("recordings", models.BooleanField(default=False)),
                ("recording_pin", models.CharField(blank=True, max_length=50)),
                ("extra_information", models.TextField(blank=True)),
                ("tutors", models.CharField(blank=True, max_length=255)),
                ("timezone", models.CharField(default="Europe/London", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrate.coursetemplate",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrate.location",
                    ),
                ),
                (
                    "primary_instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_events",
                        to="administrate.instructor",
                    ),
                ),
                (
                    "tutorial_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adm_events",
                        to="tutorials.tutorialevents",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrate.venue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Event",
                "verbose_name_plural": "Tutorial Events",
                "db_table": '"adm"."events"',
                "ordering": ["title", "lms_start_date"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("day_number", models.PositiveIntegerField()),
                ("classroom_start_date", models.DateField()),
                ("classroom_start_time", models.TimeField()),
                ("classroom_end_date", models.DateField()),
                ("classroom_end_time", models.TimeField()),
                (
                    "session_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("cancelled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="administrate.event",
                    ),
                ),
                (
                    "session_instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_instructions",
                        to="administrate.instructor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Session",
                "verbose_name_plural": "Tutorial Sessions",
                "db_table": '"adm"."sessions"',
                "ordering": ["event", "day_number"],
                "unique_together": {("event", "day_number")},
            },
        ),
    ]
