# Generated by Django 5.1.1 on 2025-03-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0007_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='profile_image',
        ),
        migrations.AlterModelTable(
            name='instructor',
            table='adm.instructors',
        ),
    ]
