# Generated by Django 6.0.1 on 2026-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0007_add_event_tutorial_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(db_index=True, max_length=100)),
                ("operation", models.CharField(max_length=50)),
                ("graphql_query", models.TextField()),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "entity_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("entity_id", models.CharField(blank=True, default="", max_length=255)),
                ("records_processed", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "API Audit Log",
                "verbose_name_plural": "API Audit Logs",
                "db_table": '"adm"."api_audit_log"',
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["command", "started_at"],
                        name="api_audit_l_command_1f0a10_idx",
                    ),
                    models.Index(
                        fields=["success", "started_at"],
                        name="api_audit_l_success_4a086b_idx",
                    ),
                ],
            },
        ),
    ]
