# Generated by Django 6.0.1 on 2026-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0008_add_api_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="external_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
