# Generated by Django 6.0.1 on 2026-05-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0009_session_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "administrate_webhook_id",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("administrate_event_timestamp", models.DateTimeField(db_index=True)),
                ("webhook_type_name", models.CharField(max_length=80)),
                ("entity_type", models.CharField(max_length=40)),
                ("entity_external_id", models.CharField(db_index=True, max_length=64)),
                ("raw_payload", models.JSONField()),
                ("raw_headers", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("applied", "Applied"),
                            ("duplicate", "Duplicate"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("task_id", models.CharField(blank=True, default="", max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": '"adm"."webhook_inbox"',
                "indexes": [
                    models.Index(
                        fields=["status", "received_at"],
                        name="webhook_inb_status_10552b_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_external_id"],
                        name="webhook_inb_entity__eb4549_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "administrate_webhook_id",
                            "entity_external_id",
                            "administrate_event_timestamp",
                        ),
                        name="uniq_webhook_inbox_delivery",
                    )
                ],
            },
        ),
    ]
