# Generated by Django 5.1.1 on 2025-04-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0009_venue'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='venue',
            table='adm.venues',
        ),
    ]
