# Generated by Django 6.0.1 on 2026-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0010_webhookinbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "administrate_webhook_id",
                    models.CharField(max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=120)),
                ("webhook_type_name", models.CharField(max_length=80)),
                (
                    "lifecycle_state",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": '"adm"."webhook_registrations"',
            },
        ),
    ]
