# Generated by Django 6.0.1 on 2026-05-15 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0011_add_webhook_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="course_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrate.coursetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrate.location",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="primary_instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_events",
                to="administrate.instructor",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
