# Generated by Django 6.0.1 on 2026-05-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0012_nullify_event_bridge_fks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["external_id"],
                "verbose_name": "Administrate Event Bridge",
                "verbose_name_plural": "Administrate Event Bridges",
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="access_duration",
        ),
        migrations.RemoveField(
            model_name="event",
            name="administrator",
        ),
        migrations.RemoveField(
            model_name="event",
            name="cancelled",
        ),
        migrations.RemoveField(
            model_name="event",
            name="course_template",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_url",
        ),
        migrations.RemoveField(
            model_name="event",
            name="extra_information",
        ),
        migrations.RemoveField(
            model_name="event",
            name="finalisation_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="learning_mode",
        ),
        migrations.RemoveField(
            model_name="event",
            name="lifecycle_state",
        ),
        migrations.RemoveField(
            model_name="event",
            name="lms_end_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="lms_start_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.RemoveField(
            model_name="event",
            name="max_places",
        ),
        migrations.RemoveField(
            model_name="event",
            name="min_places",
        ),
        migrations.RemoveField(
            model_name="event",
            name="ocr_moodle_code",
        ),
        migrations.RemoveField(
            model_name="event",
            name="primary_instructor",
        ),
        migrations.RemoveField(
            model_name="event",
            name="recording_pin",
        ),
        migrations.RemoveField(
            model_name="event",
            name="recordings",
        ),
        migrations.RemoveField(
            model_name="event",
            name="registration_deadline",
        ),
        migrations.RemoveField(
            model_name="event",
            name="sage_code",
        ),
        migrations.RemoveField(
            model_name="event",
            name="session_title",
        ),
        migrations.RemoveField(
            model_name="event",
            name="sitting",
        ),
        migrations.RemoveField(
            model_name="event",
            name="sold_out",
        ),
        migrations.RemoveField(
            model_name="event",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
        migrations.RemoveField(
            model_name="event",
            name="tutorial_category",
        ),
        migrations.RemoveField(
            model_name="event",
            name="tutors",
        ),
        migrations.RemoveField(
            model_name="event",
            name="venue",
        ),
        migrations.RemoveField(
            model_name="event",
            name="virtual_classroom",
        ),
        migrations.RemoveField(
            model_name="event",
            name="web_sale",
        ),
    ]
