"""Phase 2 of the session+learner webhook expansion (2026-05-18).

Refactor `adm.sessions` into a thin bridge, mirroring what PR #120 did
for `adm.events`. Post-migration the table carries only:
  - id (PK)
  - external_id (Administrate join key, nullable+unique)
  - tutorial_session_id (FK to `acted.tutorial_sessions`, nullable, SET_NULL)
  - created_at / updated_at

All redundant data columns (title, day_number, classroom_*, cancelled,
session_url, session_instructor_id, event_id) are dropped. The acted
master (`acted.tutorial_sessions`) is the source of truth for that data
and was already populated by CSV bulk import.

Backfill strategy (pure SQL, idempotent):
  1. For each `adm.sessions` row, locate the matching
     `acted.tutorial_sessions` row by joining through `adm.events` on
     `event.tutorial_event_id` and matching `day_number == sequence`.
     Set `tutorial_session_id` on the bridge row.
  2. For rows where the bridge had `cancelled = TRUE`, propagate that
     flag onto the matched `tutorial_sessions.cancelled`. (Phase 1 of
     this PR added that column to the master.)
  3. Drop the now-redundant columns.

Rows where `event.tutorial_event_id IS NULL` (orphaned bridges) survive
with `tutorial_session_id = NULL` — the developer/operator can clean
them up manually after migration. We don't auto-create master rows
because we'd need to fabricate FKs (course_template, etc.) that aren't
on the bridge.

Forward-only: reversing this migration cannot restore the dropped
column data without a backup.
"""
from django.db import migrations, models


SQL_BACKFILL_TUTORIAL_SESSION_ID = '''
-- PostgreSQL UPDATE FROM uses comma-joined FROM tables (the JOIN ON
-- syntax can't reference the target table in its ON clause).
UPDATE "adm"."sessions" s
   SET tutorial_session_id = ts.id
  FROM "adm"."events" e, "acted"."tutorial_sessions" ts
 WHERE s.event_id = e.id
   AND ts.tutorial_event_id = e.tutorial_event_id
   AND ts.sequence = s.day_number
   AND e.tutorial_event_id IS NOT NULL
   AND s.tutorial_session_id IS NULL;
'''


SQL_PROPAGATE_CANCELLED = '''
UPDATE "acted"."tutorial_sessions" ts
   SET cancelled = TRUE
  FROM "adm"."sessions" s
 WHERE s.tutorial_session_id = ts.id
   AND s.cancelled = TRUE
   AND ts.cancelled = FALSE;
'''


def noop_reverse(apps, schema_editor):
    raise NotImplementedError(
        'Session thin-bridge refactor is forward-only: reversing would '
        'require restoring dropped columns (title, day_number, '
        'classroom_*, session_instructor, session_url, cancelled, event) '
        'from a backup.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0013_drop_event_legacy_columns'),
        # Need tutorial_sessions.cancelled column to exist before we
        # propagate the bridge's cancelled flag onto it.
        ('tutorials', '0028_tutorial_sessions_webhook_prep'),
    ]

    operations = [
        # 1. Drop unique_together so we can later drop its constituent
        # fields. Django's AlterUniqueTogether uses an introspection
        # helper (`_delete_composed_index`) that breaks on schema-
        # qualified table names like `"adm"."sessions"` — it queries
        # information_schema with the bare table name and finds zero
        # constraints. Bypass via SeparateDatabaseAndState: the state
        # side updates Django's model graph (so RemoveField below sees
        # no unique_together), the database side drops the actual
        # constraint via raw SQL. The constraint name was generated by
        # Django when migration 0007 created the table; using
        # `IF EXISTS` keeps the migration safe to re-run.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='session',
                    unique_together=set(),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "adm"."sessions" '
                        'DROP CONSTRAINT IF EXISTS '
                        '"sessions_event_id_day_number_d730421b_uniq";'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),

        # 2. Add the new FK to the acted master. Nullable so the
        # AddField succeeds on a non-empty table; backfill below fills
        # rows that have a discoverable match.
        migrations.AddField(
            model_name='session',
            name='tutorial_session',
            field=models.ForeignKey(
                to='tutorials.tutorialsessions',
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
                related_name='adm_sessions',
            ),
        ),

        # 3. Backfill the FK from the existing (event, day_number) pair.
        # Rows whose adm.event has tutorial_event=NULL stay unlinked.
        migrations.RunSQL(
            sql=SQL_BACKFILL_TUTORIAL_SESSION_ID,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # 4. Propagate cancelled state onto the master.
        migrations.RunSQL(
            sql=SQL_PROPAGATE_CANCELLED,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # 5. Drop the redundant columns. Django emits ALTER TABLE DROP
        # COLUMN for each. The order doesn't matter (no FK dependency
        # between them) but we drop the M2M-blocking ones (event,
        # session_instructor) explicitly first as a habit.
        migrations.RemoveField(model_name='session', name='event'),
        migrations.RemoveField(model_name='session', name='session_instructor'),
        migrations.RemoveField(model_name='session', name='title'),
        migrations.RemoveField(model_name='session', name='day_number'),
        migrations.RemoveField(model_name='session', name='classroom_start_date'),
        migrations.RemoveField(model_name='session', name='classroom_start_time'),
        migrations.RemoveField(model_name='session', name='classroom_end_date'),
        migrations.RemoveField(model_name='session', name='classroom_end_time'),
        migrations.RemoveField(model_name='session', name='session_url'),
        migrations.RemoveField(model_name='session', name='cancelled'),

        # 6. Update Meta to match the new thin-bridge identity.
        migrations.AlterModelOptions(
            name='session',
            options={
                'ordering': ['external_id'],
                'verbose_name': 'Administrate Session Bridge',
                'verbose_name_plural': 'Administrate Session Bridges',
            },
        ),
    ]
