# Generated by Django 5.2.2 on 2026-01-16 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marking_vouchers", "0001_initial"),
        ("rules_engine", "0009_add_cart_calculate_vat_entry_point"),
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total before VAT and fees",
                        max_digits=10,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total VAT amount",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Final total including VAT",
                        max_digits=10,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="VAT rate applied (e.g., 0.2000 for 20%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "vat_country",
                    models.CharField(
                        blank=True,
                        help_text="Country code for VAT calculation",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "vat_calculation_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of VAT calculation used",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "calculations_applied",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All rule engine calculations applied to this order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "acted_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActedOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("invoice", "Invoice"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="card",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP", help_text="Payment currency", max_length=3
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Opayo transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string", null=True
                    ),
                ),
                (
                    "opayo_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full Opayo API response"
                    ),
                ),
                (
                    "opayo_status_code",
                    models.CharField(
                        blank=True,
                        help_text="Opayo status code",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "opayo_status_detail",
                    models.CharField(
                        blank=True,
                        help_text="Opayo status detail",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if payment failed",
                        null=True,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Error code if payment failed",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was processed", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment metadata",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="cart.actedorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Payment",
                "verbose_name_plural": "Order Payments",
                "db_table": "acted_order_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                (
                    "has_marking",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if cart contains marking products",
                    ),
                ),
                (
                    "has_digital",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if cart contains digital products (eBooks, Online Classroom)",
                    ),
                ),
                (
                    "has_tutorial",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if cart contains tutorial products",
                    ),
                ),
                (
                    "has_material",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if cart contains material products (printed books, eBooks)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vat_result",
                    models.JSONField(
                        blank=True,
                        help_text="VAT calculation results from rules engine (Epic 3)",
                        null=True,
                    ),
                ),
                (
                    "vat_calculation_error",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if VAT calculation failed for this cart",
                    ),
                ),
                (
                    "vat_calculation_error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if VAT calculation failed",
                        null=True,
                    ),
                ),
                (
                    "vat_last_calculated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last VAT calculation attempt",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "db_table": "acted_carts",
                "ordering": ["updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("tutorial_booking_fee", "Tutorial Booking Fee"),
                            ("service_charge", "Service Charge"),
                            ("processing_fee", "Processing Fee"),
                            ("convenience_fee", "Convenience Fee"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("is_refundable", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by_rule",
                    models.IntegerField(
                        blank=True, help_text="Rule ID that applied this fee", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="cart.cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Fee",
                "verbose_name_plural": "Cart Fees",
                "db_table": "acted_cart_fees",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("marking_voucher", "Marking Voucher"),
                            ("fee", "Fee"),
                        ],
                        default="product",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_type", models.CharField(default="standard", max_length=20)),
                (
                    "actual_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "has_expired_deadline",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if marking product has expired deadlines",
                    ),
                ),
                (
                    "expired_deadlines_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of expired deadlines for marking products",
                    ),
                ),
                (
                    "marking_paper_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of marking papers for marking products",
                    ),
                ),
                (
                    "is_marking",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is a marking product",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional product-specific data (e.g., tutorial choices, variation IDs)",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vat_region",
                    models.CharField(
                        blank=True,
                        help_text="Regional VAT classification (UK, IE, EU, SA, ROW)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="VAT rate applied (e.g., 0.2000 for 20%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated VAT amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total including VAT (net + VAT)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "vat_calculated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last VAT calculation",
                        null=True,
                    ),
                ),
                (
                    "vat_rule_version",
                    models.IntegerField(
                        blank=True,
                        help_text="Version of rule that calculated VAT",
                        null=True,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                    ),
                ),
                (
                    "marking_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marking_vouchers.markingvoucher",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to store.Product",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "db_table": "acted_cart_items",
                "ordering": ["added_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderDeliveryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_address_type",
                    models.CharField(
                        blank=True,
                        choices=[("home", "Home"), ("work", "Work")],
                        help_text="Type of delivery address (home/work)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "invoice_address_type",
                    models.CharField(
                        blank=True,
                        choices=[("home", "Home"), ("work", "Work")],
                        help_text="Type of invoice address (home/work)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "delivery_address_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete delivery address data in JSON format",
                    ),
                ),
                (
                    "invoice_address_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete invoice address data in JSON format",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Associated order for this delivery detail",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_detail",
                        to="cart.actedorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Delivery Detail",
                "verbose_name_plural": "Order Delivery Details",
                "db_table": "acted_order_delivery_detail",
            },
        ),
        migrations.CreateModel(
            name="OrderUserAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acknowledgment_type",
                    models.CharField(
                        choices=[
                            ("terms_conditions", "Terms & Conditions"),
                            ("product_specific", "Product-Specific Acknowledgment"),
                            ("deadline_expired", "Expired Deadline Acknowledgment"),
                            ("policy_change", "Policy Change Acknowledgment"),
                            ("warning", "Warning Acknowledgment"),
                            ("digital_consent", "Digital Content Consent"),
                            ("custom", "Custom Acknowledgment"),
                        ],
                        help_text="Type of acknowledgment required",
                        max_length=50,
                    ),
                ),
                (
                    "rule_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the rule that triggered this acknowledgment",
                        null=True,
                    ),
                ),
                (
                    "template_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the message template used for this acknowledgment",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title/subject of the acknowledgment", max_length=255
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(
                        help_text="Brief summary of what was acknowledged"
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user accepted/acknowledged this requirement",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when acknowledgment was made",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of user who made the acknowledgment",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string of browser used to make acknowledgment",
                    ),
                ),
                (
                    "content_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version of content that was acknowledged",
                        max_length=20,
                    ),
                ),
                (
                    "acknowledgment_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data related to this acknowledgment (product IDs, specific conditions, etc.)",
                    ),
                ),
                (
                    "rules_engine_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data from rules engine evaluation that triggered this acknowledgment",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Associated order for this acknowledgment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_acknowledgments",
                        to="cart.actedorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order User Acknowledgment",
                "verbose_name_plural": "Order User Acknowledgments",
                "db_table": "acted_order_user_acknowledgments",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderUserContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "home_phone_country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        help_text="Required mobile phone number", max_length=20
                    ),
                ),
                (
                    "mobile_phone_country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                    ),
                ),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "work_phone_country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Required email address", max_length=254
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Associated order for this contact information",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_contact",
                        to="cart.actedorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order User Contact",
                "verbose_name_plural": "Order User Contacts",
                "db_table": "acted_order_user_contact",
            },
        ),
        migrations.CreateModel(
            name="OrderUserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference_type",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing Preferences"),
                            ("communication", "Communication Preferences"),
                            ("delivery", "Delivery Preferences"),
                            ("notification", "Notification Preferences"),
                            ("custom", "Custom Preference"),
                        ],
                        default="custom",
                        help_text="Type of preference",
                        max_length=50,
                    ),
                ),
                (
                    "preference_key",
                    models.CharField(
                        help_text="Unique key identifying this preference",
                        max_length=100,
                    ),
                ),
                (
                    "preference_value",
                    models.JSONField(
                        default=dict,
                        help_text="User's preference value(s) stored as JSON",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("radio", "Radio Button"),
                            ("checkbox", "Checkbox"),
                            ("text", "Text Input"),
                            ("textarea", "Text Area"),
                            ("select", "Dropdown Select"),
                            ("custom", "Custom Input"),
                        ],
                        default="text",
                        help_text="Type of input used to collect this preference",
                        max_length=20,
                    ),
                ),
                (
                    "display_mode",
                    models.CharField(
                        choices=[
                            ("inline", "Inline Display"),
                            ("modal", "Modal Dialog"),
                        ],
                        default="inline",
                        help_text="How the preference was displayed to the user",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the preference displayed to user",
                        max_length=255,
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(
                        blank=True, help_text="Brief summary of the preference content"
                    ),
                ),
                (
                    "is_submitted",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user has submitted this preference",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "rules_engine_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data from rules engine evaluation",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Associated order for this preference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="cart.actedorder",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules_engine.actedrule",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules_engine.messagetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order User Preference",
                "verbose_name_plural": "Order User Preferences",
                "db_table": "acted_order_user_preferences",
            },
        ),
        migrations.CreateModel(
            name="ActedOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("marking_voucher", "Marking Voucher"),
                            ("fee", "Fee"),
                        ],
                        default="product",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_type", models.CharField(default="standard", max_length=20)),
                (
                    "actual_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount before VAT",
                        max_digits=10,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="VAT amount for this item",
                        max_digits=10,
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total amount including VAT",
                        max_digits=10,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="VAT rate applied to this item",
                        max_digits=5,
                    ),
                ),
                (
                    "is_vat_exempt",
                    models.BooleanField(
                        default=False, help_text="Whether this item is exempt from VAT"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional product-specific data (e.g., tutorial choices, variation IDs)",
                    ),
                ),
                (
                    "marking_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marking_vouchers.markingvoucher",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.actedorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to store.Product",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": "acted_order_items",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("product__isnull", False),
                            ("marking_voucher__isnull", False),
                            ("item_type", "fee"),
                            _connector="OR",
                        ),
                        name="order_item_has_product_or_voucher_or_is_fee",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("product__isnull", False),
                            ("marking_voucher__isnull", False),
                            _negated=True,
                        ),
                        name="order_item_not_both_product_and_voucher",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["vat_result"], name="idx_cart_vat_result"),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user",),
                name="unique_cart_per_user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartfee",
            unique_together={("cart", "fee_type")},
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["vat_region"], name="idx_cartitem_vat_region"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["vat_calculated_at"], name="idx_cartitem_vat_calc_at"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "vat_region"], name="idx_cartitem_cart_vat_region"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product__isnull", False),
                    ("marking_voucher__isnull", False),
                    ("item_type", "fee"),
                    _connector="OR",
                ),
                name="cart_item_has_product_or_voucher_or_is_fee",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product__isnull", False),
                    ("marking_voucher__isnull", False),
                    _negated=True,
                ),
                name="cart_item_not_both_product_and_voucher",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vat_rate__isnull", True),
                    models.Q(("vat_rate__gte", 0.0), ("vat_rate__lte", 1.0)),
                    _connector="OR",
                ),
                name="cart_item_vat_rate_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vat_amount__isnull", True),
                    ("vat_amount__gte", 0),
                    _connector="OR",
                ),
                name="cart_item_vat_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gross_amount__isnull", True),
                    ("gross_amount__gte", 0),
                    _connector="OR",
                ),
                name="cart_item_gross_amount_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="orderdeliverydetail",
            index=models.Index(fields=["order"], name="acted_order_order_i_c68122_idx"),
        ),
        migrations.AddIndex(
            model_name="orderuseracknowledgment",
            index=models.Index(
                fields=["order", "acknowledgment_type"],
                name="acted_order_order_i_35b378_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderuseracknowledgment",
            index=models.Index(
                fields=["rule_id"], name="acted_order_rule_id_aa7ebb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderuseracknowledgment",
            index=models.Index(
                fields=["acknowledgment_type"], name="acted_order_acknowl_c605b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderusercontact",
            index=models.Index(fields=["order"], name="acted_order_order_i_0276a0_idx"),
        ),
        migrations.AddIndex(
            model_name="orderuserpreference",
            index=models.Index(
                fields=["order", "preference_type"],
                name="acted_order_order_i_0d9b3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderuserpreference",
            index=models.Index(
                fields=["preference_key"], name="acted_order_prefere_d4597b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderuserpreference",
            index=models.Index(
                fields=["submitted_at"], name="acted_order_submitt_83e093_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderuserpreference",
            unique_together={("order", "rule", "preference_key")},
        ),
    ]
