# Generated by Django 6.0.1 on 2026-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actedorder",
            name="user",
        ),
        migrations.RemoveField(
            model_name="actedorderpayment",
            name="order",
        ),
        migrations.RemoveConstraint(
            model_name="actedorderitem",
            name="order_item_has_product_or_voucher_or_is_fee",
        ),
        migrations.RemoveConstraint(
            model_name="actedorderitem",
            name="order_item_not_both_product_and_voucher",
        ),
        migrations.RemoveIndex(
            model_name="orderdeliverydetail",
            name="acted_order_order_i_c68122_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderuseracknowledgment",
            name="acted_order_order_i_35b378_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderuseracknowledgment",
            name="acted_order_rule_id_aa7ebb_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderuseracknowledgment",
            name="acted_order_acknowl_c605b9_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderusercontact",
            name="acted_order_order_i_0276a0_idx",
        ),
        migrations.AlterUniqueTogether(
            name="orderuserpreference",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="orderuserpreference",
            name="acted_order_order_i_0d9b3c_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderuserpreference",
            name="acted_order_prefere_d4597b_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderuserpreference",
            name="acted_order_submitt_83e093_idx",
        ),
        migrations.AlterField(
            model_name="cart",
            name="vat_result",
            field=models.JSONField(
                blank=True,
                help_text="VAT calculation results from rules engine",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ActedOrderPayment",
        ),
        migrations.RemoveField(
            model_name="orderdeliverydetail",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderuseracknowledgment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderusercontact",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderuserpreference",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderuserpreference",
            name="rule",
        ),
        migrations.RemoveField(
            model_name="orderuserpreference",
            name="template",
        ),
        migrations.DeleteModel(
            name="ActedOrderItem",
        ),
        migrations.DeleteModel(
            name="OrderDeliveryDetail",
        ),
        migrations.DeleteModel(
            name="OrderUserAcknowledgment",
        ),
        migrations.DeleteModel(
            name="OrderUserContact",
        ),
        migrations.DeleteModel(
            name="ActedOrder",
        ),
        migrations.DeleteModel(
            name="OrderUserPreference",
        ),
    ]
