# Generated by Django 5.1.1 on 2025-04-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cartitem_options_and_more'),
        ('exam_sessions_subjects_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_sessions_subjects_products.examsessionsubjectproduct'),
        ),
    ]
