# Generated by Django 5.1.1 on 2025-05-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('exam_sessions_subjects_products', '0006_price_price_type_alter_price_variation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='actedorderitem',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='actedorderitem',
            name='price_type',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_type',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'price_type')},
        ),
    ]
