# Generated by Django 5.2.2 on 2025-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="has_digital",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if cart contains digital products (eBooks, Online Classroom)",
            ),
        ),
    ]
