# Generated by Django 6.0.1 on 2026-04-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_table_alter_cartfee_table_and_more"),
        ("marking_vouchers", "0002_migrate_to_acted_schema"),
        # Minimum required: store.Purchasable created in 0004.
        # Note: intentionally NOT depending on later store migrations so
        # cart.0004 can be ordered flexibly by the migration graph.
        ("store", "0004_create_purchasable"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="cart_item_has_product_or_voucher_or_is_fee",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="purchasable",
            field=models.ForeignKey(
                blank=True,
                help_text="The catalog entity being purchased. Non-null in Release B.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items_by_purchasable",
                to="store.purchasable",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product__isnull", False),
                    ("marking_voucher__isnull", False),
                    ("purchasable__isnull", False),
                    ("item_type", "fee"),
                    _connector="OR",
                ),
                name="cart_item_has_product_or_voucher_or_is_fee",
            ),
        ),
    ]
