# Generated by Django 5.2.2 on 2025-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actedorderitem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional product-specific data (e.g., tutorial choices, variation IDs)",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional product-specific data (e.g., tutorial choices, variation IDs)",
            ),
        ),
    ]
