# Generated by Django 5.2.2 on 2025-09-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cart_has_digital_cartitem_expired_deadlines_count_and_more"),
        ("rules_engine", "0003_userpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference_type",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing Preferences"),
                            ("communication", "Communication Preferences"),
                            ("delivery", "Delivery Preferences"),
                            ("notification", "Notification Preferences"),
                            ("custom", "Custom Preference"),
                        ],
                        default="custom",
                        help_text="Type of preference",
                        max_length=50,
                    ),
                ),
                (
                    "preference_key",
                    models.CharField(
                        help_text="Unique key identifying this preference",
                        max_length=100,
                    ),
                ),
                (
                    "preference_value",
                    models.JSONField(
                        default=dict,
                        help_text="User's preference value(s) stored as JSON",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("radio", "Radio Button"),
                            ("checkbox", "Checkbox"),
                            ("text", "Text Input"),
                            ("textarea", "Text Area"),
                            ("select", "Dropdown Select"),
                            ("custom", "Custom Input"),
                        ],
                        default="text",
                        help_text="Type of input used to collect this preference",
                        max_length=20,
                    ),
                ),
                (
                    "display_mode",
                    models.CharField(
                        choices=[
                            ("inline", "Inline Display"),
                            ("modal", "Modal Dialog"),
                        ],
                        default="inline",
                        help_text="How the preference was displayed to the user",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the preference displayed to user",
                        max_length=255,
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(
                        blank=True, help_text="Brief summary of the preference content"
                    ),
                ),
                (
                    "is_submitted",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user has submitted this preference",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "rules_engine_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data from rules engine evaluation",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Associated order for this preference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="cart.actedorder",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules_engine.actedrule",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules_engine.messagetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order User Preference",
                "verbose_name_plural": "Order User Preferences",
                "db_table": "acted_order_user_preferences",
                "indexes": [
                    models.Index(
                        fields=["order", "preference_type"],
                        name="acted_order_order_i_0d9b3c_idx",
                    ),
                    models.Index(
                        fields=["preference_key"], name="acted_order_prefere_d4597b_idx"
                    ),
                    models.Index(
                        fields=["submitted_at"], name="acted_order_submitt_83e093_idx"
                    ),
                ],
                "unique_together": {("order", "rule", "preference_key")},
            },
        ),
    ]
