# Generated by Django 5.2.2 on 2025-06-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_actedorderitem_metadata_cartitem_metadata"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
