# Generated by Django 5.1.1 on 2025-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_actedorder_actedorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
