# Generated by Django 5.2.2 on 2025-09-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_orderuserpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="has_material",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if cart contains material products (printed books, eBooks)",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="has_tutorial",
            field=models.BooleanField(
                default=False, help_text="Indicates if cart contains tutorial products"
            ),
        ),
    ]
