# Generated by Django 5.2.2 on 2025-06-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_remove_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="actedorder",
            name="calculations_applied",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="All rule engine calculations applied to this order",
            ),
        ),
        migrations.AddField(
            model_name="actedorder",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total before VAT and fees",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="actedorder",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Final total including VAT",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="actedorder",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total VAT amount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="actedorder",
            name="vat_calculation_type",
            field=models.CharField(
                blank=True,
                help_text="Type of VAT calculation used",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actedorder",
            name="vat_country",
            field=models.CharField(
                blank=True,
                help_text="Country code for VAT calculation",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actedorder",
            name="vat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="VAT rate applied (e.g., 0.2000 for 20%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actedorderitem",
            name="gross_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total amount including VAT",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="actedorderitem",
            name="is_vat_exempt",
            field=models.BooleanField(
                default=False, help_text="Whether this item is exempt from VAT"
            ),
        ),
        migrations.AddField(
            model_name="actedorderitem",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount before VAT",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="actedorderitem",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="VAT amount for this item",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="actedorderitem",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="VAT rate applied to this item",
                max_digits=5,
            ),
        ),
    ]
