# Generated by Django 5.2.2 on 2025-07-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_add_acted_order_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("tutorial_booking_fee", "Tutorial Booking Fee"),
                            ("service_charge", "Service Charge"),
                            ("processing_fee", "Processing Fee"),
                            ("convenience_fee", "Convenience Fee"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("is_refundable", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by_rule",
                    models.IntegerField(
                        blank=True, help_text="Rule ID that applied this fee", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="cart.cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Fee",
                "verbose_name_plural": "Cart Fees",
                "db_table": "acted_cart_fees",
                "unique_together": {("cart", "fee_type")},
            },
        ),
    ]
