# Generated by Django 5.2.2 on 2025-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_cartfee"),
    ]

    operations = [
        migrations.AddField(
            model_name="actedorderitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("product", "Product"),
                    ("marking_voucher", "Marking Voucher"),
                ],
                default="product",
                max_length=20,
            ),
        ),
    ]
