# Generated by Django 5.2.2 on 2025-07-17 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_actedorderitem_item_type"),
        ("exam_sessions_subjects_products", "0008_new_bundle_structure"),
        ("marking_vouchers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actedorderitem",
            name="marking_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marking_vouchers.markingvoucher",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("product", "Product"),
                    ("marking_voucher", "Marking Voucher"),
                ],
                default="product",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="marking_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marking_vouchers.markingvoucher",
            ),
        ),
        migrations.AlterField(
            model_name="actedorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sessions_subjects_products.examsessionsubjectproduct",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sessions_subjects_products.examsessionsubjectproduct",
            ),
        ),
        migrations.AddConstraint(
            model_name="actedorderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product__isnull", False),
                    ("marking_voucher__isnull", False),
                    _connector="OR",
                ),
                name="order_item_has_product_or_voucher",
            ),
        ),
        migrations.AddConstraint(
            model_name="actedorderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product__isnull", False),
                    ("marking_voucher__isnull", False),
                    _negated=True,
                ),
                name="order_item_not_both_product_and_voucher",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product__isnull", False),
                    ("marking_voucher__isnull", False),
                    _connector="OR",
                ),
                name="cart_item_has_product_or_voucher",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product__isnull", False),
                    ("marking_voucher__isnull", False),
                    _negated=True,
                ),
                name="cart_item_not_both_product_and_voucher",
            ),
        ),
    ]
