# Generated by Django 5.2.2 on 2025-08-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_actedorderitem_marking_voucher_cartitem_item_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActedOrderTermsAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "general_terms_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user accepted general terms and conditions",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when T&C were accepted"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of user who accepted T&C",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string of browser used to accept T&C",
                    ),
                ),
                (
                    "terms_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version of T&C that were accepted",
                        max_length=20,
                    ),
                ),
                (
                    "product_acknowledgments",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Product-specific acknowledgments (e.g., expired deadlines, special conditions)",
                    ),
                ),
                (
                    "rules_engine_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data from rules engine evaluation that triggered T&C requirements",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Associated order for this T&C acceptance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_acceptance",
                        to="cart.actedorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Terms Acceptance",
                "verbose_name_plural": "Order Terms Acceptances",
                "db_table": "acted_order_terms_acceptance",
                "ordering": ["-accepted_at"],
            },
        ),
    ]
