# Generated by Django 5.2.2 on 2025-08-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_refactor_terms_to_generic_acknowledgments"),
    ]

    operations = [
        # Update the model's db_table setting first
        migrations.AlterModelTable(
            name='orderuseracknowledgment',
            table='acted_order_user_acknowledgments',
        ),
    ]
