# Generated by Django 5.2.2 on 2025-08-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0014_add_cart_marking_flags"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orderuseracknowledgment",
            new_name="acted_order_order_i_35b378_idx",
            old_name="order_user__order_i_1d56bf_idx",
        ),
        migrations.RenameIndex(
            model_name="orderuseracknowledgment",
            new_name="acted_order_rule_id_aa7ebb_idx",
            old_name="order_user__rule_id_c66e23_idx",
        ),
        migrations.RenameIndex(
            model_name="orderuseracknowledgment",
            new_name="acted_order_acknowl_c605b9_idx",
            old_name="order_user__acknowl_4b2cc4_idx",
        ),
    ]
