# Generated by Django 5.1 on 2025-09-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_update_constraints_for_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone', models.CharField(help_text='Required mobile phone number', max_length=20)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(help_text='Required email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Associated order for this contact information', on_delete=django.db.models.deletion.CASCADE, related_name='user_contact', to='cart.actedorder')),
            ],
            options={
                'verbose_name': 'Order User Contact',
                'verbose_name_plural': 'Order User Contacts',
                'db_table': 'acted_order_user_contact',
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address_type', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work')], help_text='Type of delivery address (home/work)', max_length=10, null=True)),
                ('delivery_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_state', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_country', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_address_type', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work')], help_text='Type of invoice address (home/work)', max_length=10, null=True)),
                ('invoice_address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_city', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_state', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Associated order for this delivery preference', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_preference', to='cart.actedorder')),
            ],
            options={
                'verbose_name': 'Order Delivery Preference',
                'verbose_name_plural': 'Order Delivery Preferences',
                'db_table': 'acted_order_delivery_preference',
            },
        ),
        migrations.AddIndex(
            model_name='orderusercontact',
            index=models.Index(fields=['order'], name='acted_order_order_i_35c378_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdeliverypreference',
            index=models.Index(fields=['order'], name='acted_order_order_i_35c379_idx'),
        ),
    ]