# Generated by Django 5.2.2 on 2025-09-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0019_rename_delivery_preference_to_detail"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orderdeliverydetail",
            new_name="acted_order_order_i_c68122_idx",
            old_name="acted_order_order_i_35c379_idx",
        ),
        migrations.RenameIndex(
            model_name="orderusercontact",
            new_name="acted_order_order_i_0276a0_idx",
            old_name="acted_order_order_i_35c378_idx",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="expired_deadlines_count",
            field=models.IntegerField(
                default=0, help_text="Number of expired deadlines for marking products"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="marking_paper_count",
            field=models.IntegerField(
                default=0,
                help_text="Total number of marking papers for marking products",
            ),
        ),
        migrations.AlterField(
            model_name="orderdeliverydetail",
            name="order",
            field=models.ForeignKey(
                help_text="Associated order for this delivery detail",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_detail",
                to="cart.actedorder",
            ),
        ),
    ]
