# Generated by Django 5.2.2 on 2025-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cart",
            "0020_rename_acted_order_order_i_35c379_idx_acted_order_order_i_c68122_idx_and_more",
        ),
    ]

    operations = [
        # Add JSONB fields for storing complete address data
        migrations.AddField(
            model_name='orderdeliverydetail',
            name='delivery_address_data',
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text="Complete delivery address data in JSON format"
            ),
        ),
        migrations.AddField(
            model_name='orderdeliverydetail',
            name='invoice_address_data',
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text="Complete invoice address data in JSON format"
            ),
        ),
    ]
