# Generated by Django 5.2.2 on 2025-09-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0021_add_jsonb_address_fields"),
    ]

    operations = [
        # Remove individual delivery address fields
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='delivery_address_line1',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='delivery_address_line2',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='delivery_state',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='delivery_postal_code',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='delivery_country',
        ),

        # Remove individual invoice address fields
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='invoice_address_line1',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='invoice_address_line2',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='invoice_city',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='invoice_state',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='invoice_postal_code',
        ),
        migrations.RemoveField(
            model_name='orderdeliverydetail',
            name='invoice_country',
        ),
    ]
