# Generated by Django 5.2.2 on 2025-10-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0024_cart_unique_cart_per_user"),
        ("exam_sessions_subjects_products", "0001_initial"),
        ("marking_vouchers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="gross_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total including VAT (net + VAT)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="vat_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated VAT amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="vat_calculated_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last VAT calculation", null=True
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="vat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="VAT rate applied (e.g., 0.2000 for 20%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="vat_region",
            field=models.CharField(
                blank=True,
                help_text="Regional VAT classification (UK, IE, EU, SA, ROW)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="vat_rule_version",
            field=models.IntegerField(
                blank=True, help_text="Version of rule that calculated VAT", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["vat_region"], name="idx_cartitem_vat_region"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["vat_calculated_at"], name="idx_cartitem_vat_calc_at"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "vat_region"], name="idx_cartitem_cart_vat_region"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vat_rate__isnull", True),
                    models.Q(("vat_rate__gte", 0.0), ("vat_rate__lte", 1.0)),
                    _connector="OR",
                ),
                name="cart_item_vat_rate_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vat_amount__isnull", True),
                    ("vat_amount__gte", 0),
                    _connector="OR",
                ),
                name="cart_item_vat_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gross_amount__isnull", True),
                    ("gross_amount__gte", 0),
                    _connector="OR",
                ),
                name="cart_item_gross_amount_non_negative",
            ),
        ),
    ]
