# Generated by Django 5.2.2 on 2025-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0025_add_vat_fields_to_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="vat_calculation_error",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if VAT calculation failed for this cart",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="vat_calculation_error_message",
            field=models.TextField(
                blank=True,
                help_text="Error message if VAT calculation failed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="vat_last_calculated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last VAT calculation attempt",
                null=True,
            ),
        ),
    ]
