# Generated by Django 5.2.2 on 2025-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_add_vat_error_fields_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderusercontact',
            name='home_phone_country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
        migrations.AddField(
            model_name='orderusercontact',
            name='mobile_phone_country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
        migrations.AddField(
            model_name='orderusercontact',
            name='work_phone_country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
    ]
