# Generated by Django 5.2.2 on 2025-12-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_add_phone_country_codes_to_order_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuseracknowledgment',
            name='acknowledgment_type',
            field=models.CharField(choices=[('terms_conditions', 'Terms & Conditions'), ('product_specific', 'Product-Specific Acknowledgment'), ('deadline_expired', 'Expired Deadline Acknowledgment'), ('policy_change', 'Policy Change Acknowledgment'), ('warning', 'Warning Acknowledgment'), ('digital_consent', 'Digital Content Consent'), ('custom', 'Custom Acknowledgment')], help_text='Type of acknowledgment required', max_length=50),
        ),
    ]
