# Generated by Django 5.2.2 on 2026-01-14 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_simplify_product_fk'),
        ('store', '0002_migrate_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actedorderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Reference to store.Product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Reference to store.Product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.product'),
        ),
    ]
