# Generated by Django 5.1.1 on 2025-03-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0002_alter_examsession_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examsession',
            table='exam_sessions',
        ),
    ]
