# Generated by Django 6.0.1 on 2026-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # Create the legacy schema in PostgreSQL before any table creation.
        # The schema must exist for the schema-qualified db_table to work.
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS legacy;',
            reverse_sql='DROP SCHEMA IF EXISTS legacy CASCADE;',
        ),
        migrations.CreateModel(
            name="LegacyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_code",
                    models.CharField(
                        db_index=True,
                        help_text="Subject code (e.g., CM2, 101, CB1)",
                        max_length=10,
                    ),
                ),
                (
                    "delivery_format",
                    models.CharField(
                        help_text="Delivery format: P=Printed, C=eBook, M=Marking, T=Tutorial",
                        max_length=1,
                    ),
                ),
                (
                    "product_template_code",
                    models.CharField(
                        help_text="Product template code from CSV col3 (e.g., N, C, X, EX)",
                        max_length=50,
                    ),
                ),
                (
                    "session_code",
                    models.CharField(
                        db_index=True,
                        help_text="Exam session code (e.g., 95, 01, 20, 26S)",
                        max_length=10,
                    ),
                ),
                (
                    "full_code",
                    models.CharField(
                        db_index=True,
                        help_text="Full product code from CSV col5 (e.g., CM2/PC/20)",
                        max_length=64,
                    ),
                ),
                (
                    "legacy_product_name",
                    models.TextField(
                        help_text="Original raw fullname from the CSV (col6)"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short name from the CSV (col7)", max_length=255
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        db_index=True,
                        help_text="Output of normalize_fullname() — powers search matching",
                        max_length=255,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        help_text="CSV filename this row was imported from (provenance)",
                        max_length=100,
                    ),
                ),
                (
                    "source_line",
                    models.PositiveIntegerField(
                        help_text="Line number in the source CSV (provenance)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Legacy Product",
                "verbose_name_plural": "Legacy Products",
                "db_table": '"legacy"."products"',
                "indexes": [
                    models.Index(
                        fields=["subject_code", "session_code"],
                        name="legacy_prod_subj_sess_idx",
                    ),
                    models.Index(
                        fields=["normalized_name"], name="legacy_prod_norm_name_idx"
                    ),
                ],
            },
        ),
    ]
