# Generated by Django 6.0.1 on 2026-04-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legacy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_ref",
                    models.IntegerField(
                        db_index=True,
                        help_text="Student reference (joins to acted.students.student_ref)",
                    ),
                ),
                ("order_date", models.DateField(help_text="Order date from CSV")),
                (
                    "delivery_pref",
                    models.CharField(
                        help_text="Delivery preference: H=Home, W=Work", max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "Legacy Order",
                "verbose_name_plural": "Legacy Orders",
                "db_table": '"legacy"."orders"',
                "indexes": [
                    models.Index(
                        fields=["student_ref", "order_date"],
                        name="legacy_ord_ref_date_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LegacyOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.IntegerField(
                        db_index=True,
                        help_text="Legacy order line number (column 7 in CSV, not unique)",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        db_index=True,
                        help_text="Full product code (joins to legacy.products.full_code or store.Product.product_code)",
                        max_length=64,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price paid", max_digits=10
                    ),
                ),
                ("quantity", models.IntegerField(help_text="Quantity ordered")),
                (
                    "free_of_charge",
                    models.BooleanField(
                        default=False, help_text="Item was free of charge"
                    ),
                ),
                (
                    "is_retaker",
                    models.BooleanField(
                        default=False, help_text="Retaker pricing applied"
                    ),
                ),
                (
                    "is_reduced",
                    models.BooleanField(
                        default=False, help_text="Reduced pricing applied"
                    ),
                ),
                (
                    "is_additional",
                    models.BooleanField(default=False, help_text="Additional copy"),
                ),
                (
                    "is_reduced_rate",
                    models.BooleanField(
                        default=False, help_text="Reduced rate applied"
                    ),
                ),
                (
                    "session_code",
                    models.CharField(
                        db_index=True,
                        help_text="Exam session code extracted from product_code",
                        max_length=10,
                    ),
                ),
                (
                    "subject_code",
                    models.CharField(
                        db_index=True,
                        help_text="Subject code extracted from product_code",
                        max_length=10,
                    ),
                ),
                (
                    "source_line",
                    models.PositiveIntegerField(
                        help_text="Line number in the source CSV (provenance)"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="legacy.legacyorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legacy Order Item",
                "verbose_name_plural": "Legacy Order Items",
                "db_table": '"legacy"."order_items"',
                "indexes": [
                    models.Index(
                        fields=["session_code", "subject_code"],
                        name="legacy_oi_sess_subj_idx",
                    ),
                    models.Index(
                        fields=["product_code"], name="legacy_oi_prod_code_idx"
                    ),
                ],
            },
        ),
    ]
