# Generated by Django 6.0.1 on 2026-04-15 13:29

import django.db.models.deletion
from django.db import migrations, models


def populate_product_fk(apps, schema_editor):
    """Populate product_id FK on legacy.order_items from product_code.

    Matches order_items.product_code to legacy.products.full_code.
    Session 26 items (no legacy.products entry) remain NULL.
    """
    LegacyProduct = apps.get_model("legacy", "LegacyProduct")
    LegacyOrderItem = apps.get_model("legacy", "LegacyOrderItem")

    # Build lookup: full_code -> id
    code_to_id = dict(LegacyProduct.objects.values_list("full_code", "id"))

    # Batch update in chunks to avoid memory issues
    batch_size = 10000
    total = LegacyOrderItem.objects.count()
    updated = 0
    skipped = 0

    # Process in ID-ordered chunks
    last_id = 0
    while True:
        items = list(
            LegacyOrderItem.objects.filter(id__gt=last_id)
            .order_by("id")
            .values_list("id", "product_code")[:batch_size]
        )
        if not items:
            break

        # Build bulk update list
        to_update = []
        for item_id, product_code in items:
            product_pk = code_to_id.get(product_code)
            if product_pk:
                to_update.append((item_id, product_pk))
            else:
                skipped += 1

        if to_update:
            # Use raw SQL for efficient batch update
            connection = schema_editor.connection
            with connection.cursor() as cursor:
                # Update in sub-batches of 1000 for SQL parameter limits
                for i in range(0, len(to_update), 1000):
                    sub_batch = to_update[i : i + 1000]
                    case_sql = " ".join(
                        f"WHEN {item_id} THEN {prod_id}"
                        for item_id, prod_id in sub_batch
                    )
                    ids = ",".join(str(item_id) for item_id, _ in sub_batch)
                    cursor.execute(
                        f'UPDATE "legacy"."order_items" '
                        f"SET product_id = CASE id {case_sql} END "
                        f"WHERE id IN ({ids})"
                    )
            updated += len(to_update)

        last_id = items[-1][0]
        print(f"  Populated {updated + skipped}/{total} items "
              f"(updated={updated}, skipped={skipped})")


class Migration(migrations.Migration):

    dependencies = [
        ("legacy", "0002_add_orders_tables"),
    ]

    operations = [
        # Step 1: Drop existing db_index, then add unique constraint
        migrations.RunSQL(
            sql=[
                'DROP INDEX IF EXISTS "legacy"."products_full_code_8ff8ee95_like";',
                'DROP INDEX IF EXISTS "legacy"."products_full_code_8ff8ee95";',
            ],
            reverse_sql=[
                'CREATE INDEX "products_full_code_8ff8ee95" ON "legacy"."products" ("full_code");',
                "CREATE INDEX \"products_full_code_8ff8ee95_like\" ON \"legacy\".\"products\" (\"full_code\" varchar_pattern_ops);",
            ],
        ),
        migrations.AlterField(
            model_name="legacyproduct",
            name="full_code",
            field=models.CharField(
                help_text="Full product code from CSV col5 (e.g., CM2/PC/20)",
                max_length=64,
                unique=True,
            ),
        ),
        # Step 2: Add nullable product FK
        migrations.AddField(
            model_name="legacyorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="FK to legacy.products (null for session 26 items)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="legacy.legacyproduct",
            ),
        ),
        # Step 3: Populate product_id from product_code
        migrations.RunPython(
            populate_product_fk,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 4: Remove old columns and their indexes
        migrations.RemoveIndex(
            model_name="legacyorderitem",
            name="legacy_oi_sess_subj_idx",
        ),
        migrations.RemoveIndex(
            model_name="legacyorderitem",
            name="legacy_oi_prod_code_idx",
        ),
        migrations.RemoveField(
            model_name="legacyorderitem",
            name="product_code",
        ),
        migrations.RemoveField(
            model_name="legacyorderitem",
            name="session_code",
        ),
        migrations.RemoveField(
            model_name="legacyorderitem",
            name="subject_code",
        ),
    ]
