# API Response Contract: Tutorial Sessions in Unified Search
# Feature: 20260204-tutorial-sessions
# Endpoint: POST /api/search/unified/

openapi: 3.0.3
info:
  title: Tutorial Sessions API Response Contract
  version: 1.0.0
  description: |
    Contract for the sessions array nested within tutorial events
    in the unified search API response.

components:
  schemas:
    TutorialSession:
      type: object
      description: Individual session within a tutorial event
      required:
        - id
        - title
        - location
        - venue
        - start_date
        - end_date
        - sequence
      properties:
        id:
          type: integer
          format: int64
          description: Session primary key
          example: 1
        title:
          type: string
          maxLength: 255
          description: Session display title
          example: "Day 1 - Introduction"
        location:
          type: string
          maxLength: 255
          description: Physical location name
          example: "Dublin"
        venue:
          type: string
          maxLength: 255
          description: Venue name
          example: "Camden Court Hotel"
        start_date:
          type: string
          format: date-time
          description: Session start datetime (ISO 8601)
          example: "2025-07-22T09:00:00"
        end_date:
          type: string
          format: date-time
          description: Session end datetime (ISO 8601)
          example: "2025-07-22T17:00:00"
        sequence:
          type: integer
          minimum: 1
          description: Ordering within the event
          example: 1
        url:
          type: string
          format: uri
          maxLength: 500
          nullable: true
          description: Optional video conference or resource URL
          example: "https://zoom.us/j/123456789"

    TutorialEvent:
      type: object
      description: Tutorial event with nested sessions
      required:
        - id
        - code
        - venue
        - is_soldout
        - remain_space
        - start_date
        - end_date
        - title
        - sessions
      properties:
        id:
          type: integer
          format: int64
          example: 61
        code:
          type: string
          example: "CM2-55-25S"
        venue:
          type: string
          example: "Camden Court Hotel"
        is_soldout:
          type: boolean
          example: false
        finalisation_date:
          type: string
          format: date
          nullable: true
          example: "2025-06-22"
        remain_space:
          type: integer
          example: 11
        start_date:
          type: string
          format: date
          example: "2025-07-22"
        end_date:
          type: string
          format: date
          example: "2025-08-21"
        title:
          type: string
          example: "CM2-55-25S"
        price:
          type: number
          nullable: true
          example: null
        sessions:
          type: array
          description: Sessions within this event, ordered by sequence
          items:
            $ref: '#/components/schemas/TutorialSession'

    ProductVariation:
      type: object
      description: Product variation with events containing sessions
      properties:
        id:
          type: integer
          example: 72
        store_product_id:
          type: integer
          example: 719
        variation_type:
          type: string
          example: "Tutorial"
        name:
          type: string
          example: "CM2_f2f_5"
        description:
          type: string
          example: "CM2 5-day bundle"
        description_short:
          type: string
          example: "5-day bundle"
        prices:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              price_type:
                type: string
                enum: [standard, retaker, reduced, additional]
              amount:
                type: string
              currency:
                type: string
        events:
          type: array
          description: Tutorial events (only for Tutorial variation types)
          items:
            $ref: '#/components/schemas/TutorialEvent'

    UnifiedSearchProduct:
      type: object
      description: Product in unified search response
      properties:
        id:
          type: integer
          example: 719
        essp_id:
          type: integer
          example: 719
        store_product_id:
          type: integer
          example: 719
        type:
          type: string
          enum: [Tutorial, Materials, Markings]
          example: "Tutorial"
        product_id:
          type: integer
          example: 129
        product_code:
          type: string
          example: "DUB"
        product_name:
          type: string
          example: "Tutorial - Dublin"
        product_short_name:
          type: string
          example: "Dublin"
        product_description:
          type: string
          example: "Dublin"
        buy_both:
          type: boolean
          example: false
        subject_id:
          type: integer
          example: 7
        subject_code:
          type: string
          example: "CM2"
        subject_description:
          type: string
          example: "Economic Modelling"
        exam_session_code:
          type: string
          example: "25S"
        exam_session_id:
          type: integer
          example: 6
        variations:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariation'

# Example response showing complete structure with sessions
paths:
  /api/search/unified/:
    post:
      summary: Unified product search
      responses:
        '200':
          description: Search results with tutorial sessions
          content:
            application/json:
              example:
                products:
                  - id: 719
                    essp_id: 719
                    store_product_id: 719
                    type: "Tutorial"
                    product_id: 129
                    product_code: "DUB"
                    product_name: "Tutorial - Dublin"
                    product_short_name: "Dublin"
                    product_description: "Dublin"
                    buy_both: false
                    subject_id: 7
                    subject_code: "CM2"
                    subject_description: "Economic Modelling"
                    exam_session_code: "25S"
                    exam_session_id: 6
                    variations:
                      - id: 72
                        store_product_id: 719
                        variation_type: "Tutorial"
                        name: "CM2_f2f_5"
                        description: "CM2 5-day bundle"
                        description_short: "5-day bundle"
                        prices:
                          - id: 2136
                            price_type: "standard"
                            amount: "755.00"
                            currency: "gbp"
                          - id: 2382
                            price_type: "reduced"
                            amount: "566.25"
                            currency: "gbp"
                        events:
                          - id: 61
                            code: "CM2-55-25S"
                            venue: "Camden Court Hotel"
                            is_soldout: false
                            finalisation_date: "2025-06-22"
                            remain_space: 11
                            start_date: "2025-07-22"
                            end_date: "2025-08-21"
                            title: "CM2-55-25S"
                            price: null
                            sessions:
                              - id: 1
                                title: "Day 1 - Introduction to Economic Models"
                                location: "Dublin"
                                venue: "Camden Court Hotel"
                                start_date: "2025-07-22T09:00:00"
                                end_date: "2025-07-22T17:00:00"
                                sequence: 1
                                url: null
                              - id: 2
                                title: "Day 2 - Stochastic Models"
                                location: "Dublin"
                                venue: "Camden Court Hotel"
                                start_date: "2025-07-23T09:00:00"
                                end_date: "2025-07-23T17:00:00"
                                sequence: 2
                                url: null
                filter_counts:
                  subjects: {}
                  categories: {}
                  product_types: {}
                pagination:
                  page: 1
                  page_size: 20
                  total_count: 1
                  has_next: false
                  has_previous: false
