# Generated by Django 5.1.1 on 2025-04-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSessionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_sessions.examsession')),
            ],
            options={
                'verbose_name': 'Exam Session Subject',
                'verbose_name_plural': 'Exam Session Subjects',
                'db_table': 'acted_exam_session_subjects',
            },
        ),
    ]
