# Generated by Django 5.1.1 on 2025-04-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_sessions_subjects', '0001_initial'),
        ('exam_sessions_subjects_products', '0001_initial'),        
        ('subjects', '0003_alter_subject_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsessionsubject',
            name='products',
            field=models.ManyToManyField(through='exam_sessions_subjects_products.ExamSessionSubjectProduct', to='products.product'),
        ),
        migrations.AddField(
            model_name='examsessionsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='examsessionsubject',
            unique_together={('exam_session', 'subject')},
        ),
    ]
