# Generated by Django 5.2.2 on 2025-09-11 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam_sessions_subjects", "0001_initial"),
        ("exam_sessions_subjects_products", "0001_initial"),
        ("products", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsessionsubject",
            name="products",
            field=models.ManyToManyField(
                through="exam_sessions_subjects_products.ExamSessionSubjectProduct",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="examsessionsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="subjects.subject"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examsessionsubject",
            unique_together={("exam_session", "subject")},
        ),
    ]
