# Generated by Django 5.2.2 on 2026-01-05 15:17
#
# IMPORTANT: This migration must run BEFORE exam_sessions.0002_delete_examsession
# because AlterField needs the old model (exam_sessions.examsession) to exist
# in Django's migration state.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_create_models"),  # Changed from 0003 - only need models, not data
        ("exam_sessions", "0001_initial"),  # Ensure old ExamSession model still exists
        ("exam_sessions_subjects", "0002_initial"),
        ("exam_sessions_subjects_products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsessionsubject",
            name="exam_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.examsession"
            ),
        ),
        migrations.AlterField(
            model_name="examsessionsubject",
            name="products",
            field=models.ManyToManyField(
                through="exam_sessions_subjects_products.ExamSessionSubjectProduct",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="examsessionsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.subject"
            ),
        ),
    ]
