# Generated by Django 5.2.2 on 2026-01-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0009_add_exam_session_subject_product"),
        ("catalog_products", "0001_initial"),
        ("catalog_products_bundles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether bundle is available for purchase",
                    ),
                ),
                (
                    "override_name",
                    models.CharField(
                        blank=True,
                        help_text="Override the template bundle name for this instance",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "override_description",
                    models.TextField(
                        blank=True,
                        help_text="Override the template description for this instance",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order for bundle display"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle_template",
                    models.ForeignKey(
                        help_text="The catalog bundle template this is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_bundles",
                        to="catalog_products_bundles.productbundle",
                    ),
                ),
                (
                    "exam_session_subject",
                    models.ForeignKey(
                        help_text="The exam session subject this bundle is available for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_bundles",
                        to="catalog.examsessionsubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Bundle",
                "verbose_name_plural": "Store Bundles",
                "db_table": '"acted"."bundles"',
                "ordering": ["display_order", "created_at"],
                "unique_together": {("bundle_template", "exam_session_subject")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        help_text="Unique auto-generated product code",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether product is available for purchase",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_session_subject",
                    models.ForeignKey(
                        help_text="The exam session subject this product is available for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_products",
                        to="catalog.examsessionsubject",
                    ),
                ),
                (
                    "product_product_variation",
                    models.ForeignKey(
                        help_text="The product variation (template + variation combination)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_products",
                        to="catalog_products.productproductvariation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Product",
                "verbose_name_plural": "Store Products",
                "db_table": '"acted"."products"',
                "unique_together": {
                    ("exam_session_subject", "product_product_variation")
                },
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("retaker", "Retaker"),
                            ("reduced", "Reduced Rate"),
                            ("additional", "Additional Copy"),
                        ],
                        default="standard",
                        help_text="The type of pricing tier",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Price amount", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP",
                        help_text="Currency code (ISO 4217)",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product this price applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
                "db_table": '"acted"."prices"',
                "unique_together": {("product", "price_type")},
            },
        ),
        migrations.CreateModel(
            name="BundleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_price_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("retaker", "Retaker"),
                            ("reduced", "Reduced Rate"),
                            ("additional", "Additional Copy"),
                        ],
                        default="standard",
                        help_text="Default price type to use for this product in the bundle",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity of this product in the bundle"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the bundle"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this product is active in the bundle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle",
                    models.ForeignKey(
                        help_text="The bundle this product belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_products",
                        to="store.bundle",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product included in this bundle",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_memberships",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bundle Product",
                "verbose_name_plural": "Bundle Products",
                "db_table": '"acted"."bundle_products"',
                "ordering": ["sort_order", "created_at"],
                "unique_together": {("bundle", "product")},
            },
        ),
    ]
