# Generated by Django 6.0.1 on 2026-01-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_products", "0001_initial"),
        ("catalog_products_bundles", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="bundle_template",
            field=models.ForeignKey(
                help_text="The catalog bundle template this is based on",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_bundles",
                to="catalog_products_bundles.productbundle",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_product_variation",
            field=models.ForeignKey(
                help_text="The product variation (template + variation combination)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_products",
                to="catalog_products.productproductvariation",
            ),
        ),
    ]
