# Generated by Django 6.0.1 on 2026-02-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_bundle_bundle_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this price is active"
            ),
        ),
    ]
