# Generated by Django 6.0.1 on 2026-04-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_is_active_to_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchasable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("product", "Store Product (ESS-based)"),
                            ("marking_voucher", "Marking Voucher"),
                            ("document_binder", "Document Binder"),
                            ("additional_charge", "Additional Charge"),
                        ],
                        max_length=32,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dynamic_pricing",
                    models.BooleanField(
                        default=False,
                        help_text="If True, price is set per cart/order line (actual_price), not from Price table.",
                    ),
                ),
                (
                    "vat_classification",
                    models.CharField(
                        blank=True,
                        help_text="Used by VAT rules engine to select rate.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Purchasable",
                "verbose_name_plural": "Purchasables",
                "db_table": '"acted"."purchasables"',
                "indexes": [
                    models.Index(fields=["kind"], name="purchasable_kind_80ecfa_idx"),
                    models.Index(
                        fields=["is_active"], name="purchasable_is_acti_7c7a2a_idx"
                    ),
                ],
            },
        ),
    ]
