# Generated by Django 6.0.1 on 2026-04-20 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_create_purchasable"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericItem",
            fields=[
                (
                    "purchasable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.purchasable",
                    ),
                ),
                (
                    "validity_period_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If set, issued instances expire this many days after purchase (e.g., 1460 for 4 years).",
                        null=True,
                    ),
                ),
                (
                    "stock_tracked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether physical inventory is tracked for this item.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generic Item",
                "verbose_name_plural": "Generic Items",
                "db_table": '"acted"."generic_items"',
            },
            bases=("store.purchasable",),
        ),
    ]
