# Generated by Django 6.0.1 on 2026-04-20 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_create_generic_item"),
    ]

    operations = [
        # Drop old unique constraint: DB + state separated because the
        # schema-qualified/quoted table name ('"acted"."prices"') prevents
        # Django's schema editor from finding the composed unique constraint.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "acted"."prices" '
                        'DROP CONSTRAINT IF EXISTS '
                        '"prices_product_id_price_type_9fd9f5db_uniq";',
                    reverse_sql='ALTER TABLE "acted"."prices" '
                                'ADD CONSTRAINT '
                                '"prices_product_id_price_type_9fd9f5db_uniq" '
                                'UNIQUE (product_id, price_type);',
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="price",
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="price",
            name="purchasable",
            field=models.ForeignKey(
                blank=True,
                help_text="The purchasable this price applies to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="store.purchasable",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED - use purchasable. Removed in Release B.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.product",
            ),
        ),
    ]
