# Generated by Django 6.0.1 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_drop_price_product_fk"),
    ]

    operations = [
        # The UNIQUE (exam_session_subject_id, product_product_variation_id)
        # constraint was created by raw SQL in an earlier migration with a
        # Django-generated name that does not match the autodetector's
        # expectation, so AlterUniqueTogether cannot find it on its own.
        # Drop it explicitly in the DB, and simultaneously clear the
        # model-state unique_together so future autogen stays aligned.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "acted"."products" '
                        'DROP CONSTRAINT IF EXISTS '
                        '"products_exam_session_subject_id__02f7493b_uniq";'
                    ),
                    reverse_sql=(
                        'ALTER TABLE "acted"."products" '
                        'ADD CONSTRAINT '
                        '"products_exam_session_subject_id__02f7493b_uniq" '
                        'UNIQUE (exam_session_subject_id, '
                        'product_product_variation_id);'
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="product",
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchasable",
            name="is_addon",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True for solution/addon purchasables (e.g., PXS, CXS, "
                    "CM1S, CYS). Distinguishes addons from their base product "
                    "when both share the same catalog PPV "
                    "(see Product.unique_together)."
                ),
            ),
        ),
    ]
