# Generated by Django 6.0.1 on 2026-05-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_ensure_fee_generic_exists"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Product",
                "verbose_name_plural": "Material Products",
                "db_table": '"acted"."material_products"',
            },
            bases=("store.product",),
        ),
        migrations.AlterField(
            model_name="purchasable",
            name="kind",
            field=models.CharField(
                choices=[
                    ("material", "Material Product"),
                    ("tutorial", "Tutorial Product"),
                    ("marking", "Marking Product"),
                    ("marking_voucher", "Marking Voucher"),
                    ("document_binder", "Document Binder"),
                    ("additional_charge", "Additional Charge"),
                    ("product", "Legacy Product (pre-split)"),
                ],
                max_length=32,
            ),
        ),
    ]
