# Generated by Django 6.0.1 on 2026-05-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_create_material_products"),
        ("tutorials", "0024_attendance_sync_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.product",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("F2F_1F", "Face-to-Face 1-day"),
                            ("F2F_3F", "Face-to-Face 3-day"),
                            ("F2F_5F", "Face-to-Face 5-day"),
                            ("LIVE", "Live Online"),
                            ("REC", "Recorded"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "tutorial_course_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_tutorial_products",
                        to="tutorials.tutorialcoursetemplate",
                    ),
                ),
                (
                    "tutorial_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_tutorial_products",
                        to="tutorials.tutoriallocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Product",
                "verbose_name_plural": "Tutorial Products",
                "db_table": '"acted"."tutorial_products"',
            },
            bases=("store.product",),
        ),
    ]
