# Generated by Django 6.0.1 on 2026-05-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0017_add_marking_template_and_paper_fk"),
        ("store", "0017_create_tutorial_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkingProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.product",
                    ),
                ),
                (
                    "paper_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of papers in this series. Optional — can be derived from MarkingPaper rows attached to this template.",
                        null=True,
                    ),
                ),
                (
                    "marking_template",
                    models.ForeignKey(
                        help_text="The marking series template this product realizes.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_marking_products",
                        to="marking.markingtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marking Product",
                "verbose_name_plural": "Marking Products",
                "db_table": '"acted"."marking_products"',
            },
            bases=("store.product",),
        ),
    ]
