# Generated by Django 6.0.1 on 2026-05-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_create_marking_products"),
        ("tutorials", "0024_attendance_sync_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorialproduct",
            name="format",
            field=models.CharField(
                choices=[
                    ("F2F_1F", "Face-to-Face 1 full day"),
                    ("F2F_1PD", "Face-to-Face Paper B Preparation Day"),
                    ("F2F_2F", "Face-to-Face 2 full days"),
                    ("F2F_3F", "Face-to-Face 3 full days"),
                    ("F2F_4F", "Face-to-Face 4 full days"),
                    ("F2F_5B", "Face-to-Face 5-day bundle"),
                    ("F2F_5F", "Face-to-Face 5 full days"),
                    ("F2F_6B", "Face-to-Face 6-day bundle"),
                    ("F2F_6H", "Face-to-Face 6 half days"),
                    ("LO_10H", "Live Online 10 half days"),
                    ("LO_1F", "Live Online 1 full day"),
                    ("LO_1PD", "Live Online Paper B Preparation Day"),
                    ("LO_2F", "Live Online 2 full days"),
                    ("LO_2H", "Live Online 2 half days"),
                    ("LO_3F", "Live Online 3 full days"),
                    ("LO_4F", "Live Online 4 full days"),
                    ("LO_4H", "Live Online 4 half days"),
                    ("LO_5B", "Live Online 5-day bundle"),
                    ("LO_5F", "Live Online 5 full days"),
                    ("LO_6B", "Live Online 6-day bundle"),
                    ("LO_6H", "Live Online 6 half days"),
                    ("LO_8H", "Live Online 8 half days"),
                    ("OC", "Online Classroom"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tutorialproduct",
            name="tutorial_course_template",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL if no matching `{subject}_{format}` template existed at Phase 2 backfill time. Operators can link a real template later.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store_tutorial_products",
                to="tutorials.tutorialcoursetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="tutorialproduct",
            name="tutorial_location",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL for OC (Online Classroom) rows — no physical venue.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store_tutorial_products",
                to="tutorials.tutoriallocation",
            ),
        ),
    ]
