# Generated by Django 6.0.1 on 2026-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_reshape_tutorial_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasable",
            name="kind",
            field=models.CharField(
                choices=[
                    ("material", "Material Product"),
                    ("tutorial", "Tutorial Product"),
                    ("marking", "Marking Product"),
                    ("marking_voucher", "Marking Voucher"),
                    ("document_binder", "Document Binder"),
                    ("additional_charge", "Additional Charge"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name='purchasable',
            constraint=models.CheckConstraint(
                condition=~models.Q(kind='product'),
                name='purchasable_kind_not_legacy_product',
            ),
        ),
    ]
