# Generated by Django 5.1.1 on 2025-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2 or alpha-3 code', max_length=3, unique=True)),
                ('phone_code', models.CharField(help_text='International dialing code, e.g. +44', max_length=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='VAT percentage, e.g. 20.00', max_digits=5)),
                ('have_postcode', models.BooleanField(default=True, help_text='Does this country use postcodes?')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
