# Generated by Django 5.1.1 on 2025-04-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(help_text='ISO 3166-1 alpha-2 or alpha-3 code', max_length=10, unique=True),
        ),
    ]
