# Generated by Django 5.1.1 on 2025-04-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0002_remove_productcategory_code_productcategory_iscore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='isCore',
            new_name='is_core',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='isDisplay',
            new_name='is_display',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='isMarking',
            new_name='is_marking',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='isRevision',
            new_name='is_revision',
        ),
    ]
