# Generated by Django 5.1.1 on 2025-05-02 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ref', models.AutoField(primary_key=True, serialize=False)),
                ('student_type', models.CharField(choices=[('S', 'STUDENTS'), ('Q', 'QUALIFIED'), ('I', 'INACTIVE')], default='regular', max_length=50)),
                ('apprentice_type', models.CharField(choices=[('none', 'None'), ('L4', 'LEVEL 4'), ('L7', 'LEVEL 7')], default='none', max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'acted_students',
            },
        ),
    ]
