# Generated by Django 5.1.1 on 2025-03-03 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='apprentice_type',
            field=models.CharField(choices=[('none', 'None'), ('L4', 'LEVEL 4'), ('L7', 'LEVEL 7')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('S', 'STUDENTS'), ('Q', 'QUALIFIED'), ('I', 'INACTIVE')], default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
