# Generated by Django 5.2.2 on 2025-06-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsettings",
            name="default_value",
            field=models.JSONField(
                blank=True, default=dict, help_text="Default value for this setting"
            ),
        ),
    ]
