# Generated by Django 5.2.2 on 2025-09-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailCampaign",
        ),
    ]
