# Generated by Django 5.2.2 on 2025-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_alter_emailsettings_default_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="html_content",
        ),
        migrations.AddField(
            model_name="emaillog",
            name="content_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete email content payload including templates, context, and rendered content",
            ),
        ),
    ]
