# Generated by Django 5.2.2 on 2025-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_delete_emailcampaign"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_code",
                    models.CharField(
                        help_text="Full module code (e.g., CM1A01)", max_length=10
                    ),
                ),
                (
                    "module_group",
                    models.CharField(
                        choices=[
                            ("CM1", "CM1 - Certificate in Mathematics 1"),
                            ("CM2", "CM2 - Certificate in Mathematics 2"),
                            ("CS1", "CS1 - Certificate in Statistics 1"),
                            ("CS2", "CS2 - Certificate in Statistics 2"),
                            ("CB", "CB - Certificate in Business"),
                            ("CP1", "CP1 - Certificate in Probability 1"),
                            ("CP2", "CP2 - Certificate in Probability 2"),
                            ("CP3", "CP3 - Certificate in Probability 3"),
                            ("SP", "SP - Statistics and Probability"),
                            ("SA", "SA - Statistical Analysis"),
                        ],
                        help_text="Module group for calendar categorization",
                        max_length=5,
                    ),
                ),
                (
                    "assignment_code",
                    models.CharField(help_text="Assignment identifier", max_length=20),
                ),
                (
                    "title",
                    models.CharField(help_text="Assignment title", max_length=200),
                ),
                (
                    "recommend_date",
                    models.DateField(
                        blank=True, help_text="Recommended completion date", null=True
                    ),
                ),
                ("deadline_date", models.DateField(help_text="Assignment deadline")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Include in calendar generation"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        default="2026", help_text="Academic year", max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Assignment Deadline",
                "verbose_name_plural": "Assignment Deadlines",
                "db_table": "utils_assignment_deadline",
                "ordering": ["module_group", "deadline_date", "module_code"],
                "indexes": [
                    models.Index(
                        fields=["module_group", "deadline_date"],
                        name="utils_assig_module__0a4857_idx",
                    ),
                    models.Index(
                        fields=["is_active", "deadline_date"],
                        name="utils_assig_is_acti_071d10_idx",
                    ),
                ],
                "unique_together": {
                    ("module_code", "assignment_code", "academic_year")
                },
            },
        ),
    ]
