# Generated by Django 5.2.2 on 2025-06-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0003_change_emaillog_content_to_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="content_payload",
        ),
        migrations.RemoveField(
            model_name="emaillog",
            name="text_content",
        ),
    ]
