# Generated by Django 5.2.2 on 2025-10-07 11:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_assignmentdeadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilsCountrys',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT percentage (e.g., 20.00 for 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VAT Country',
                'verbose_name_plural': 'VAT Countries',
                'db_table': 'utils_countrys',
            },
        ),
        migrations.CreateModel(
            name='UtilsRegion',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VAT Region',
                'verbose_name_plural': 'VAT Regions',
                'db_table': 'utils_regions',
            },
        ),
        migrations.CreateModel(
            name='UtilsCountryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.utilscountrys')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.utilsregion')),
            ],
            options={
                'db_table': 'utils_country_region',
                'unique_together': {('country', 'effective_from')},
            },
        ),
    ]
