# Generated by Django 5.2.2 on 2026-01-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_populate_vat_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentDeadline',
        ),
    ]
