# Generated by Django 5.2.2 on 2025-06-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_add_content_insertion_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailcontentplaceholder",
            name="default_content",
        ),
        migrations.RemoveField(
            model_name="emailcontentrule",
            name="content_variables",
        ),
        migrations.RemoveField(
            model_name="emailcontentrule",
            name="insert_position",
        ),
        migrations.RemoveField(
            model_name="emailcontentrule",
            name="placeholder_name",
        ),
        migrations.RemoveField(
            model_name="emailtemplatecontentrule",
            name="variables_override",
        ),
        migrations.AddField(
            model_name="emailcontentplaceholder",
            name="content_variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Variables available in content templates for this placeholder",
            ),
        ),
        migrations.AddField(
            model_name="emailcontentplaceholder",
            name="default_content_template",
            field=models.TextField(
                blank=True,
                help_text="Default MJML/HTML content template when no rules match",
            ),
        ),
        migrations.AddField(
            model_name="emailcontentplaceholder",
            name="insert_position",
            field=models.CharField(
                choices=[
                    ("replace", "Replace Placeholder"),
                    ("before", "Before Placeholder"),
                    ("after", "After Placeholder"),
                    ("append", "Append to End"),
                    ("prepend", "Prepend to Beginning"),
                ],
                default="replace",
                help_text="How to insert content relative to placeholder",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emailcontentrule",
            name="placeholder",
            field=models.ForeignKey(
                blank=True,
                help_text="Placeholder that this rule targets",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_rules",
                to="utils.emailcontentplaceholder",
            ),
        ),
        migrations.AlterField(
            model_name="emailcontentrule",
            name="condition_field",
            field=models.CharField(
                help_text="Field name to evaluate (e.g., 'items.product_code', 'user.country')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="emailcontentrule",
            name="content_template",
            field=models.TextField(
                help_text="MJML/HTML content template to insert when this specific rule matches"
            ),
        ),
    ]
