# Generated by Django 5.2.2 on 2026-01-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_delete_assignmentdeadline'),
    ]

    operations = [
        # AlterUniqueTogether must run before RemoveField drops the referenced fields
        migrations.AlterUniqueTogether(
            name='emailtemplateattachment',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplatecontentrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='emailtemplateattachment',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='emailcontentplaceholder',
            name='templates',
        ),
        migrations.RemoveField(
            model_name='emailcontentrule',
            name='placeholder',
        ),
        migrations.RemoveField(
            model_name='emailcontentrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='emailcontentrule',
            name='templates',
        ),
        migrations.RemoveField(
            model_name='emailtemplatecontentrule',
            name='content_rule',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='queue_item',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='template',
        ),
        migrations.RemoveField(
            model_name='emailqueue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='emailqueue',
            name='template',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='emailtemplatecontentrule',
            name='template',
        ),
        migrations.RemoveField(
            model_name='emailtemplateattachment',
            name='template',
        ),
        migrations.DeleteModel(
            name='EmailAttachment',
        ),
        migrations.DeleteModel(
            name='EmailContentPlaceholder',
        ),
        migrations.DeleteModel(
            name='EmailContentRule',
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.DeleteModel(
            name='EmailQueue',
        ),
        migrations.DeleteModel(
            name='EmailSettings',
        ),
        migrations.DeleteModel(
            name='EmailTemplateContentRule',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='EmailTemplateAttachment',
        ),
    ]
