# Generated by Django 5.2.2 on 2025-06-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0006_refactor_content_rule_placeholder_separation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcontentrule",
            name="placeholder",
            field=models.ForeignKey(
                help_text="Placeholder that this rule targets",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_rules",
                to="utils.emailcontentplaceholder",
            ),
        ),
    ]
