# Generated by Django 5.2.2 on 2025-06-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0007_alter_emailcontentrule_placeholder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailcontentrule",
            name="content_template",
        ),
    ]
