# Generated by Django 5.2.2 on 2025-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0008_remove_emailcontentrule_content_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("password_reset", "Password Reset"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("account_activation", "Account Activation"),
                    ("newsletter", "Newsletter"),
                    ("welcome", "Welcome Email"),
                    ("reminder", "Reminder Email"),
                    ("notification", "System Notification"),
                    ("marketing", "Marketing Email"),
                    ("support", "Support Email"),
                    ("custom", "Custom Email"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
