insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Additional Mock Pack', 'Additional Mock Pack', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('ASET (2014-2017 Papers)', 'ASET (2014-2017 Papers)', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('ASET (2020-2023 Papers)', 'ASET (2020-2023 Papers)', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Combined Materials Pack', 'Combined Materials Pack', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Core Reading', 'Core Reading', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Course Notes', 'Course Notes', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Flash Cards', 'Flash Cards', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Marking Voucher', 'Marking Voucher', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Mock Exam Marking', 'Mock Exam Marking', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('The Vault', 'The Vault', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Sound Revision', 'Sound Revision', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Series Y Solutions ', 'Series Y Solutions ', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Series Y Assignments (Marking)', 'Series Y Assignments (Marking)', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Series X Solutions', 'Series X Solutions', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Series X Assignments', 'Series X Assignments', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Revision Notes', 'Revision Notes', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Paper B Online Resources', 'Paper B Online Resources', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Mock Exam Solutions', 'Mock Exam Solutions', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Mock Exam', 'Mock Exam', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Mini ASET (September 2024 Paper)', 'Mini ASET (September 2024 Paper)', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Mini ASET (April 2024 Paper) ', 'Mini ASET (April 2024 Paper) ', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Baxter & Rennie Textbook', 'Baxter & Rennie Textbook', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Economics Textbook 11th Ed.', 'Economics Textbook 11th Ed.', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Lam Textbook 2nd Ed.', 'Lam Textbook 2nd Ed.', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Maths & Stats Bronze', 'Maths & Stats Bronze', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Maths & Stats Bronze to Gold Upgrade', 'Maths & Stats Bronze to Gold Upgrade', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Maths & Stats Bronze to Silver Upgrade', 'Maths & Stats Bronze to Silver Upgrade', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Maths & Stats Gold ', 'Maths & Stats Gold ', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Maths & Stats Silver ', 'Maths & Stats Silver ', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Bronze', 'Module 0 Bronze', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Bronze to Gold Upgrade', 'Module 0 Bronze to Gold Upgrade', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Bronze to Silver Upgrade', 'Module 0 Bronze to Silver Upgrade', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Gold Renewal', 'Module 0 Gold Renewal', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Online Course - Gold', 'Module 0 Online Course - Gold', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Online Course - Silver', 'Module 0 Online Course - Silver', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Gold Renewal', 'Module 0 Gold Renewal', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Online Course - Gold', 'Module 0 Online Course - Gold', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Online Course - Silver', 'Module 0 Online Course - Silver', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Silver Renewal', 'Module 0 Silver Renewal', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 0 Silver to Gold Upgrade', 'Module 0 Silver to Gold Upgrade', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Module 1 Bronze', 'Module 1 Bronze', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Printed Textbook', 'Printed Textbook', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Printed Textbook 2nd Edition', 'Printed Textbook 2nd Edition', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('SP6 Hull Textbook 11th Ed.', 'SP6 Hull Textbook 11th Ed.', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );
insert into acted_products (fullname, shortname, description, created_at, updated_at, is_active ) values ('Sweeting Textbook 2nd Ed.', 'Sweeting Textbook 2nd Ed.', '''', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true );

insert into acted_product_productcategory (product_id, product_category_id) values (3, 13);
insert into acted_product_productcategory (product_id, product_category_id) values (37, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (5, 1);
insert into acted_product_productcategory (product_id, product_category_id) values (6, 11);
insert into acted_product_productcategory (product_id, product_category_id) values (7, 3);
insert into acted_product_productcategory (product_id, product_category_id) values (38, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (9, 7);
insert into acted_product_productcategory (product_id, product_category_id) values (8, 7);
insert into acted_product_productcategory (product_id, product_category_id) values (10, 8);
insert into acted_product_productcategory (product_id, product_category_id) values (39, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (40, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (15, 6);
insert into acted_product_productcategory (product_id, product_category_id) values (16, 6);
insert into acted_product_productcategory (product_id, product_category_id) values (17, 9);
insert into acted_product_productcategory (product_id, product_category_id) values (68, 9);
insert into acted_product_productcategory (product_id, product_category_id) values (18, 2);
insert into acted_product_productcategory (product_id, product_category_id) values (19, 10);
insert into acted_product_productcategory (product_id, product_category_id) values (20, 5);
insert into acted_product_productcategory (product_id, product_category_id) values (41, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (69, 12);
insert into acted_product_productcategory (product_id, product_category_id) values (35, 4);
insert into acted_product_productcategory (product_id, product_category_id) values (44, 16);
insert into acted_product_productcategory (product_id, product_category_id) values (43, 16);
insert into acted_product_productcategory (product_id, product_category_id) values (42, 16);
insert into acted_product_productcategory (product_id, product_category_id) values (45, 17);
insert into acted_product_productcategory (product_id, product_category_id) values (46, 15);
insert into acted_product_productcategory (product_id, product_category_id) values (47, 15);
insert into acted_product_productcategory (product_id, product_category_id) values (63, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (50, 1);
insert into acted_product_productcategory (product_id, product_category_id) values (51, 3);
insert into acted_product_productcategory (product_id, product_category_id) values (64, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (52, 7);
insert into acted_product_productcategory (product_id, product_category_id) values (53, 8);
insert into acted_product_productcategory (product_id, product_category_id) values (65, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (66, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (54, 2);
insert into acted_product_productcategory (product_id, product_category_id) values (55, 10);
insert into acted_product_productcategory (product_id, product_category_id) values (67, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (59, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (60, 14);
insert into acted_product_productcategory (product_id, product_category_id) values (61, 4);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (3,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (2,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (4,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (37,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (5,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (6,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (7,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (38,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (9,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (8,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (10,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (11,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (39,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (12,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (13,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (40,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (15,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (16,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (17,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (68,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (18,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (19,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (20,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (21,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (22,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (23,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (24,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (25,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (26,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (27,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (28,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (29,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (14,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (41,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (30,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (31,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (32,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (33,);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (34,8);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (69,8);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (35,9);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (36,6);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (70,7);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (44,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (43,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (42,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (45,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (46,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (47,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (48,1);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (63,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (49,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (50,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (51,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (64,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (52,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (53,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (65,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (66,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (54,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (55,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (56,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (57,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (58,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (67,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (59,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (60,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (61,2);
INSERT INTO acted_product_productsubtype (product_id, product_subtype_id) VALUES (62,8);

INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (3,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (2,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (4,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (37,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (5,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (6,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (7,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (38,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (9,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (8,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (10,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (11,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (39,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (12,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (13,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (40,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (15,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (16,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (17,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (68,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (18,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (19,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (20,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (21,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (22,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (23,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (24,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (25,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (26,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (27,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (28,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (29,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (14,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (41,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (30,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (31,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (32,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (33,3);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (34,3);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (69,3);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (35,3);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (36,3);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (70,3);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (44,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (43,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (42,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (45,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (46,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (47,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (48,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (63,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (49,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (50,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (51,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (64,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (52,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (53,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (65,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (66,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (54,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (55,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (56,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (57,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (58,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (67,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (59,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (60,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (61,1);
INSERT INTO acted_product_producttype (product_id, product_type_id) VALUES (62,3);
