# Generated by Django 6.0.1 on 2026-01-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0003_change_fk_to_store_product"),
        ("store", "0002_alter_bundle_bundle_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markingpaper",
            name="store_product",
            field=models.ForeignKey(
                blank=True,
                help_text="The store product this marking paper belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marking_papers",
                to="store.product",
            ),
        ),
    ]
