# Generated by Django 6.0.1 on 2026-04-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0005_add_marker_model"),
        ("marking_vouchers", "0002_migrate_to_acted_schema"),
        ("orders", "0003_alter_orderitem_options"),
        ("students", "0002_migrate_to_acted_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkingPaperSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_date", models.DateTimeField()),
                ("hub_download_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marking_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="marking.markingpaper",
                    ),
                ),
                (
                    "marking_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="marking_vouchers.markingvoucher",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marking_submissions",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marking_submissions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marking Paper Submission",
                "verbose_name_plural": "Marking Paper Submissions",
                "db_table": '"acted"."marking_paper_submissions"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "marking_paper"),
                        name="uq_submission_student_paper",
                    )
                ],
            },
        ),
    ]
