# Generated by Django 6.0.1 on 2026-04-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0006_add_marking_paper_submission"),
        ("staff", "0003_remove_name_format_show_job_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkingPaperGrading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocate_date", models.DateTimeField()),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("hub_download_date", models.DateTimeField(blank=True, null=True)),
                ("hub_upload_date", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocate_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocated_gradings",
                        to="staff.staff",
                    ),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gradings",
                        to="marking.marker",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading",
                        to="marking.markingpapersubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marking Paper Grading",
                "verbose_name_plural": "Marking Paper Gradings",
                "db_table": '"acted"."marking_paper_gradings"',
            },
        ),
    ]
