# Generated by Django 6.0.1 on 2026-04-21 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0007_add_marking_paper_grading"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkingPaperFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("E", "Excellent"),
                            ("G", "Good"),
                            ("A", "Average"),
                            ("P", "Poor"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                ("submission_date", models.DateTimeField()),
                ("hub_download_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grading",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="marking.markingpapergrading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marking Paper Feedback",
                "verbose_name_plural": "Marking Paper Feedbacks",
                "db_table": '"acted"."marking_paper_feedbacks"',
            },
        ),
    ]
