# Generated by Django 6.0.1 on 2026-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0009_switch_marking_voucher_to_generic_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="legacy_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="mkref from legacy system (markers.csv)",
                null=True,
                unique=True,
            ),
        ),
    ]
