# Generated by Django 6.0.1 on 2026-04-29
#
# Phase A5: Rename MarkingPaper.store_product -> purchasable, retarget the
# FK from store.Product to store.Purchasable, and add the new
# is_active and sequences fields.
#
# This migration uses RenameField + AlterField to preserve existing
# data. Every store.Product.id value is also a valid store.Purchasable.id
# (shared PK via purchasable_ptr_id from store.0010_product_to_mti_subclass),
# so the FK retarget is lossless.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0010_add_marker_legacy_id"),
        ("store", "0014_add_is_addon_and_drop_product_unique"),
    ]

    operations = [
        migrations.RenameField(
            model_name="markingpaper",
            old_name="store_product",
            new_name="purchasable",
        ),
        migrations.AlterField(
            model_name="markingpaper",
            name="purchasable",
            field=models.ForeignKey(
                blank=True,
                help_text="The purchasable this marking paper belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marking_papers",
                to="store.purchasable",
            ),
        ),
        migrations.AddField(
            model_name="markingpaper",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="markingpaper",
            name="sequences",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Sequence number within the named paper (e.g., X-1, X-2, M2-1, M2-2).",
                null=True,
            ),
        ),
    ]
