# Generated by Django 6.0.1 on 2026-04-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0011_marking_paper_purchasable_fk"),
        ("marking_vouchers", "0005_add_redeemed_voucher"),
        ("orders", "0011_order_order_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="markingpapersubmission",
            name="marking_voucher",
        ),
        migrations.AddField(
            model_name="markingpapersubmission",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="markingpapersubmission",
            name="redeemed_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="marking_vouchers.redeemedvoucher",
            ),
        ),
        migrations.AlterField(
            model_name="markingpapersubmission",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marking_submissions",
                to="orders.orderitem",
            ),
        ),
    ]
