# Generated by Django 6.0.1 on 2026-05-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0016_submission_unique_with_voucher"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Series code (e.g., 'X', 'MM1', 'Y').",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Series X Marking').",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marking Template",
                "verbose_name_plural": "Marking Templates",
                "db_table": '"acted"."marking_templates"',
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="markingpaper",
            name="marking_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The marking template this paper belongs to. Nullable during Phase 1 (created); backfilled and made NOT NULL in Phase 4c.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marking_papers",
                to="marking.markingtemplate",
            ),
        ),
    ]
