# Generated by Django 6.0.1 on 2026-05-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0017_add_marking_template_and_paper_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="markingtemplate",
            options={
                "ordering": ["code", "name"],
                "verbose_name": "Marking Template",
                "verbose_name_plural": "Marking Templates",
            },
        ),
        migrations.AlterField(
            model_name="markingtemplate",
            name="code",
            field=models.CharField(
                help_text="Series code (e.g., 'X', 'MM1', 'Y'). NOT unique by itself — catalog has duplicates with distinct names. Uniqueness enforced over composite (code, name).",
                max_length=10,
            ),
        ),
        # Django's AlterField drops the _like varchar_pattern_ops index but does
        # NOT always emit ALTER TABLE ... DROP CONSTRAINT for the unique=True
        # column-level constraint on PostgreSQL.  We drop it explicitly so the
        # old per-column UC is gone before we add the composite replacement.
        migrations.RunSQL(
            sql='ALTER TABLE "acted"."marking_templates" DROP CONSTRAINT IF EXISTS "marking_templates_code_key";',
            reverse_sql='ALTER TABLE "acted"."marking_templates" ADD CONSTRAINT "marking_templates_code_key" UNIQUE (code);',
        ),
        migrations.AddConstraint(
            model_name="markingtemplate",
            constraint=models.UniqueConstraint(
                fields=("code", "name"), name="uq_marking_template_code_name"
            ),
        ),
    ]
