# Generated by Django 6.0 on 2026-05-14
#
# Phase 4c: Make MarkingPaper.marking_template NOT NULL.
#
# This migration must run AFTER 0020_backfill_marking_paper_template which
# populated all 240 rows. Applying this migration to a DB with any NULL
# marking_template_id values will raise an IntegrityError, making the
# backfill gap immediately visible.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0020_backfill_marking_paper_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markingpaper",
            name="marking_template",
            field=models.ForeignKey(
                help_text=(
                    "The marking series this paper belongs to. Required as of "
                    "Phase 4c; backfilled by migration 0020 from MarkingProduct."
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marking_papers",
                to="marking.markingtemplate",
            ),
        ),
    ]
