# Create order tables in the 'acted' schema

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
        ('store', '0001_initial'),
        ('marking_vouchers', '0001_initial'),
        ('rules_engine', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Orders table
                '''CREATE TABLE IF NOT EXISTS "acted"."orders" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "user_id" integer NOT NULL,
                    "subtotal" numeric(10, 2) NOT NULL DEFAULT 0.00,
                    "vat_amount" numeric(10, 2) NOT NULL DEFAULT 0.00,
                    "total_amount" numeric(10, 2) NOT NULL DEFAULT 0.00,
                    "vat_rate" numeric(5, 4) NULL,
                    "vat_country" varchar(2) NULL,
                    "vat_calculation_type" varchar(50) NULL,
                    "calculations_applied" jsonb NOT NULL DEFAULT '{}'::jsonb,
                    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
                    "updated_at" timestamp with time zone NOT NULL DEFAULT now()
                )''',

                # Order items table
                '''CREATE TABLE IF NOT EXISTS "acted"."order_items" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "order_id" bigint NOT NULL,
                    "product_id" bigint NULL,
                    "marking_voucher_id" bigint NULL,
                    "item_type" varchar(20) NOT NULL DEFAULT 'product',
                    "quantity" integer NOT NULL DEFAULT 1 CHECK ("quantity" >= 0),
                    "price_type" varchar(20) NOT NULL DEFAULT 'standard',
                    "actual_price" numeric(10, 2) NULL,
                    "net_amount" numeric(10, 2) NOT NULL DEFAULT 0.00,
                    "vat_amount" numeric(10, 2) NOT NULL DEFAULT 0.00,
                    "gross_amount" numeric(10, 2) NOT NULL DEFAULT 0.00,
                    "vat_rate" numeric(5, 4) NOT NULL DEFAULT 0.0000,
                    "is_vat_exempt" boolean NOT NULL DEFAULT false,
                    "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
                    CONSTRAINT "order_item_has_product_or_voucher_or_is_fee"
                        CHECK ("product_id" IS NOT NULL OR "marking_voucher_id" IS NOT NULL OR "item_type" = 'fee'),
                    CONSTRAINT "order_item_not_both_product_and_voucher"
                        CHECK (NOT ("product_id" IS NOT NULL AND "marking_voucher_id" IS NOT NULL))
                )''',

                # Order payments table
                '''CREATE TABLE IF NOT EXISTS "acted"."order_payments" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "order_id" bigint NOT NULL,
                    "payment_method" varchar(20) NOT NULL DEFAULT 'card',
                    "amount" numeric(10, 2) NOT NULL,
                    "currency" varchar(3) NOT NULL DEFAULT 'GBP',
                    "transaction_id" varchar(100) NULL,
                    "status" varchar(20) NOT NULL DEFAULT 'pending',
                    "client_ip" inet NULL,
                    "user_agent" text NULL,
                    "opayo_response" jsonb NOT NULL DEFAULT '{}'::jsonb,
                    "opayo_status_code" varchar(10) NULL,
                    "opayo_status_detail" varchar(200) NULL,
                    "error_message" text NULL,
                    "error_code" varchar(50) NULL,
                    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
                    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
                    "processed_at" timestamp with time zone NULL,
                    "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb
                )''',

                # Order user acknowledgments table
                '''CREATE TABLE IF NOT EXISTS "acted"."order_user_acknowledgments" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "order_id" bigint NOT NULL,
                    "acknowledgment_type" varchar(50) NOT NULL,
                    "rule_id" integer NULL CHECK ("rule_id" >= 0),
                    "template_id" integer NULL CHECK ("template_id" >= 0),
                    "title" varchar(255) NOT NULL,
                    "content_summary" text NOT NULL DEFAULT '',
                    "is_accepted" boolean NOT NULL DEFAULT false,
                    "accepted_at" timestamp with time zone NOT NULL DEFAULT now(),
                    "ip_address" inet NULL,
                    "user_agent" text NOT NULL DEFAULT '',
                    "content_version" varchar(20) NOT NULL DEFAULT '1.0',
                    "acknowledgment_data" jsonb NOT NULL DEFAULT '{}'::jsonb,
                    "rules_engine_context" jsonb NOT NULL DEFAULT '{}'::jsonb
                )''',

                # Order user preferences table
                '''CREATE TABLE IF NOT EXISTS "acted"."order_user_preferences" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "order_id" bigint NOT NULL,
                    "rule_id" bigint NULL,
                    "template_id" bigint NULL,
                    "preference_type" varchar(50) NOT NULL DEFAULT 'custom',
                    "preference_key" varchar(100) NOT NULL,
                    "preference_value" jsonb NOT NULL DEFAULT '{}'::jsonb,
                    "input_type" varchar(20) NOT NULL DEFAULT 'text',
                    "display_mode" varchar(20) NOT NULL DEFAULT 'inline',
                    "title" varchar(255) NOT NULL DEFAULT '',
                    "content_summary" text NOT NULL DEFAULT '',
                    "is_submitted" boolean NOT NULL DEFAULT true,
                    "submitted_at" timestamp with time zone NOT NULL DEFAULT now(),
                    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
                    "ip_address" inet NULL,
                    "user_agent" text NOT NULL DEFAULT '',
                    "rules_engine_context" jsonb NOT NULL DEFAULT '{}'::jsonb,
                    CONSTRAINT "order_user_preferences_order_rule_key_uniq"
                        UNIQUE ("order_id", "rule_id", "preference_key")
                )''',

                # Order user contact table
                '''CREATE TABLE IF NOT EXISTS "acted"."order_user_contact" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "order_id" bigint NOT NULL,
                    "home_phone" varchar(20) NULL,
                    "home_phone_country" varchar(2) NOT NULL DEFAULT '',
                    "mobile_phone" varchar(20) NOT NULL,
                    "mobile_phone_country" varchar(2) NOT NULL DEFAULT '',
                    "work_phone" varchar(20) NULL,
                    "work_phone_country" varchar(2) NOT NULL DEFAULT '',
                    "email_address" varchar(254) NOT NULL,
                    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
                    "updated_at" timestamp with time zone NOT NULL DEFAULT now()
                )''',

                # Order delivery detail table
                '''CREATE TABLE IF NOT EXISTS "acted"."order_delivery_detail" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "order_id" bigint NOT NULL,
                    "delivery_address_type" varchar(10) NULL,
                    "invoice_address_type" varchar(10) NULL,
                    "delivery_address_data" jsonb NOT NULL DEFAULT '{}'::jsonb,
                    "invoice_address_data" jsonb NOT NULL DEFAULT '{}'::jsonb,
                    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
                    "updated_at" timestamp with time zone NOT NULL DEFAULT now()
                )''',

                # Foreign keys
                '''ALTER TABLE "acted"."orders"
                    ADD CONSTRAINT "orders_user_id_fk" FOREIGN KEY ("user_id")
                    REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_items"
                    ADD CONSTRAINT "order_items_order_id_fk" FOREIGN KEY ("order_id")
                    REFERENCES "acted"."orders" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_items"
                    ADD CONSTRAINT "order_items_product_id_fk" FOREIGN KEY ("product_id")
                    REFERENCES "acted"."products" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_items"
                    ADD CONSTRAINT "order_items_marking_voucher_id_fk" FOREIGN KEY ("marking_voucher_id")
                    REFERENCES "acted_marking_vouchers" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_payments"
                    ADD CONSTRAINT "order_payments_order_id_fk" FOREIGN KEY ("order_id")
                    REFERENCES "acted"."orders" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_user_acknowledgments"
                    ADD CONSTRAINT "order_acks_order_id_fk" FOREIGN KEY ("order_id")
                    REFERENCES "acted"."orders" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_user_preferences"
                    ADD CONSTRAINT "order_prefs_order_id_fk" FOREIGN KEY ("order_id")
                    REFERENCES "acted"."orders" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_user_preferences"
                    ADD CONSTRAINT "order_prefs_rule_id_fk" FOREIGN KEY ("rule_id")
                    REFERENCES "acted_rules" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_user_preferences"
                    ADD CONSTRAINT "order_prefs_template_id_fk" FOREIGN KEY ("template_id")
                    REFERENCES "acted_rules_message_templates" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_user_contact"
                    ADD CONSTRAINT "order_contact_order_id_fk" FOREIGN KEY ("order_id")
                    REFERENCES "acted"."orders" ("id") DEFERRABLE INITIALLY DEFERRED''',

                '''ALTER TABLE "acted"."order_delivery_detail"
                    ADD CONSTRAINT "order_delivery_order_id_fk" FOREIGN KEY ("order_id")
                    REFERENCES "acted"."orders" ("id") DEFERRABLE INITIALLY DEFERRED''',

                # Indexes
                'CREATE INDEX IF NOT EXISTS "orders_user_id_idx" ON "acted"."orders" ("user_id")',
                'CREATE INDEX IF NOT EXISTS "order_items_order_id_idx" ON "acted"."order_items" ("order_id")',
                'CREATE INDEX IF NOT EXISTS "order_items_product_id_idx" ON "acted"."order_items" ("product_id")',
                'CREATE INDEX IF NOT EXISTS "order_items_voucher_id_idx" ON "acted"."order_items" ("marking_voucher_id")',
                'CREATE INDEX IF NOT EXISTS "order_payments_order_id_idx" ON "acted"."order_payments" ("order_id")',
                'CREATE INDEX IF NOT EXISTS "order_acks_order_id_idx" ON "acted"."order_user_acknowledgments" ("order_id")',
                'CREATE INDEX IF NOT EXISTS "order_acks_type_idx" ON "acted"."order_user_acknowledgments" ("acknowledgment_type")',
                'CREATE INDEX IF NOT EXISTS "order_prefs_order_id_idx" ON "acted"."order_user_preferences" ("order_id")',
                'CREATE INDEX IF NOT EXISTS "order_prefs_key_idx" ON "acted"."order_user_preferences" ("preference_key")',
                'CREATE INDEX IF NOT EXISTS "order_contact_order_id_idx" ON "acted"."order_user_contact" ("order_id")',
                'CREATE INDEX IF NOT EXISTS "order_delivery_order_id_idx" ON "acted"."order_delivery_detail" ("order_id")',
            ],
            reverse_sql=[
                'DROP TABLE IF EXISTS "acted"."order_delivery_detail" CASCADE',
                'DROP TABLE IF EXISTS "acted"."order_user_contact" CASCADE',
                'DROP TABLE IF EXISTS "acted"."order_user_preferences" CASCADE',
                'DROP TABLE IF EXISTS "acted"."order_user_acknowledgments" CASCADE',
                'DROP TABLE IF EXISTS "acted"."order_payments" CASCADE',
                'DROP TABLE IF EXISTS "acted"."order_items" CASCADE',
                'DROP TABLE IF EXISTS "acted"."orders" CASCADE',
            ],
        ),
    ]
