# Generated by Django 6.0.1 on 2026-01-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total before VAT and fees",
                        max_digits=10,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total VAT amount",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Final total including VAT",
                        max_digits=10,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="VAT rate applied",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "vat_country",
                    models.CharField(
                        blank=True,
                        help_text="Country code for VAT calculation",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "vat_calculation_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of VAT calculation used",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "calculations_applied",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All rule engine calculations applied to this order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": '"acted"."orders"',
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acknowledgment_type",
                    models.CharField(
                        choices=[
                            ("terms_conditions", "Terms & Conditions"),
                            ("product_specific", "Product-Specific Acknowledgment"),
                            ("deadline_expired", "Expired Deadline Acknowledgment"),
                            ("policy_change", "Policy Change Acknowledgment"),
                            ("warning", "Warning Acknowledgment"),
                            ("digital_consent", "Digital Content Consent"),
                            ("custom", "Custom Acknowledgment"),
                        ],
                        help_text="Type of acknowledgment required",
                        max_length=50,
                    ),
                ),
                (
                    "rule_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the rule that triggered this",
                        null=True,
                    ),
                ),
                (
                    "template_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the message template used",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title/subject of the acknowledgment", max_length=255
                    ),
                ),
                (
                    "content_summary",
                    models.TextField(
                        help_text="Brief summary of what was acknowledged"
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False, help_text="Whether user accepted this"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when acknowledgment was made",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("content_version", models.CharField(default="1.0", max_length=20)),
                ("acknowledgment_data", models.JSONField(blank=True, default=dict)),
                ("rules_engine_context", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Order Acknowledgment",
                "verbose_name_plural": "Order Acknowledgments",
                "db_table": '"acted"."order_user_acknowledgments"',
                "ordering": ["-accepted_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "home_phone_country",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        help_text="Required mobile phone number", max_length=20
                    ),
                ),
                (
                    "mobile_phone_country",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "work_phone_country",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Required email address", max_length=254
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Order Contact",
                "verbose_name_plural": "Order Contacts",
                "db_table": '"acted"."order_user_contact"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_address_type",
                    models.CharField(
                        blank=True,
                        choices=[("home", "Home"), ("work", "Work")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "invoice_address_type",
                    models.CharField(
                        blank=True,
                        choices=[("home", "Home"), ("work", "Work")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("delivery_address_data", models.JSONField(blank=True, default=dict)),
                ("invoice_address_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Order Delivery Detail",
                "verbose_name_plural": "Order Delivery Details",
                "db_table": '"acted"."order_delivery_detail"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("marking_voucher", "Marking Voucher"),
                            ("fee", "Fee"),
                        ],
                        default="product",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_type", models.CharField(default="standard", max_length=20)),
                (
                    "actual_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount before VAT",
                        max_digits=10,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="VAT amount for this item",
                        max_digits=10,
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total amount including VAT",
                        max_digits=10,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="VAT rate applied to this item",
                        max_digits=5,
                    ),
                ),
                (
                    "is_vat_exempt",
                    models.BooleanField(
                        default=False, help_text="Whether this item is exempt from VAT"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional product-specific data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": '"acted"."order_items"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference_type",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing Preferences"),
                            ("communication", "Communication Preferences"),
                            ("delivery", "Delivery Preferences"),
                            ("notification", "Notification Preferences"),
                            ("custom", "Custom Preference"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                (
                    "preference_key",
                    models.CharField(
                        help_text="Unique key identifying this preference",
                        max_length=100,
                    ),
                ),
                (
                    "preference_value",
                    models.JSONField(
                        default=dict, help_text="User's preference value(s)"
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("radio", "Radio Button"),
                            ("checkbox", "Checkbox"),
                            ("text", "Text Input"),
                            ("textarea", "Text Area"),
                            ("select", "Dropdown Select"),
                            ("custom", "Custom Input"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "display_mode",
                    models.CharField(
                        choices=[
                            ("inline", "Inline Display"),
                            ("modal", "Modal Dialog"),
                        ],
                        default="inline",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title displayed to user", max_length=255
                    ),
                ),
                ("content_summary", models.TextField(blank=True)),
                ("is_submitted", models.BooleanField(default=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("rules_engine_context", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Order Preference",
                "verbose_name_plural": "Order Preferences",
                "db_table": '"acted"."order_user_preferences"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("invoice", "Invoice"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="card",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP", help_text="Payment currency", max_length=3
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Gateway transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string", null=True
                    ),
                ),
                (
                    "opayo_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full Opayo API response"
                    ),
                ),
                (
                    "opayo_status_code",
                    models.CharField(
                        blank=True,
                        help_text="Opayo status code",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "opayo_status_detail",
                    models.CharField(
                        blank=True,
                        help_text="Opayo status detail",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if payment failed",
                        null=True,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Error code if payment failed",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was processed", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Payment",
                "verbose_name_plural": "Order Payments",
                "db_table": '"acted"."order_payments"',
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
