# Generated by Django 6.0.1 on 2026-04-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking_vouchers", "0001_initial"),
        ("orders", "0002_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "managed": True,
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        # The FK columns and check constraints below already exist in the DB
        # (created via raw SQL in 0001_initial). We only need to register them
        # in Django's migration state so the autodetector stops trying to
        # re-create them now that the model is managed.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="orderitem",
                    name="order",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="product",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Reference to store.Product",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="store.product",
                    ),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="marking_voucher",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marking_vouchers.markingvoucher",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="orderitem",
                    constraint=models.CheckConstraint(
                        condition=(
                            models.Q(product__isnull=False)
                            | models.Q(marking_voucher__isnull=False)
                            | models.Q(item_type="fee")
                        ),
                        name="order_item_has_product_or_voucher_or_is_fee",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="orderitem",
                    constraint=models.CheckConstraint(
                        condition=~(
                            models.Q(product__isnull=False)
                            & models.Q(marking_voucher__isnull=False)
                        ),
                        name="order_item_not_both_product_and_voucher",
                    ),
                ),
            ],
        ),
        # New column — runs a real ALTER TABLE.
        migrations.AddField(
            model_name="orderitem",
            name="is_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this item is cancelled",
            ),
        ),
    ]
