# Generated by Django 6.0.1 on 2026-04-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_drop_order_item_legacy_fks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "managed": True,
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
    ]
