# Generated by Django 6.0.1 on 2026-04-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_orderitem_state_add_order"),
        ("store", "0013_drop_price_product_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="purchasable",
            field=models.ForeignKey(
                help_text="The catalog entity being purchased.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items_by_purchasable",
                to="store.purchasable",
            ),
        ),
    ]
