# Generated by Django 6.0.1 on 2026-04-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_orderitem_is_foc_and_order_managed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Business order date (when the customer placed the order). Distinct from created_at (DB insert time). Imported from the historical CSV `date` column.",
                null=True,
            ),
        ),
    ]
