# Generated by Django 5.2.2 on 2026-01-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('filtering', '0001_initial'),  # FilterGroup model moved from products to filtering
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
                'db_table': '"acted"."catalog_exam_sessions"',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('buy_both', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': '"acted"."catalog_products"',
                'ordering': ['shortname'],
            },
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(help_text="Name of the bundle (e.g., 'CM1 Materials & Marking Bundle')", max_length=255)),
                ('bundle_description', models.TextField(blank=True, help_text="Description of what's included in the bundle", null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this bundle prominently')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bundle is currently available')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this bundle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Bundle',
                'verbose_name_plural': 'Product Bundles',
                'db_table': '"acted"."catalog_product_bundles"',
                'ordering': ['subject__code', 'display_order', 'bundle_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': '"acted"."catalog_subjects"',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='catalog.product')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_product_product_groups', to='filtering.filtergroup')),
            ],
            options={
                'verbose_name': 'Product Product Group',
                'verbose_name_plural': 'Product Product Groups',
                'db_table': '"acted"."catalog_product_product_groups"',
                'unique_together': {('product', 'product_group')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(related_name='catalog_products', through='catalog.ProductProductGroup', to='filtering.filtergroup'),
        ),
        migrations.CreateModel(
            name='ProductProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Product Variation',
                'verbose_name_plural': 'Product Product Variations',
                'db_table': '"acted"."catalog_product_product_variations"',
            },
        ),
        migrations.CreateModel(
            name='ProductBundleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price_type', models.CharField(choices=[('standard', 'Standard'), ('retaker', 'Retaker'), ('additional', 'Additional Copy')], default='standard', help_text='Default price type for this product when added via bundle', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of this product to add when bundle is selected')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order of this product within the bundle')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is currently active in the bundle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(help_text='The bundle this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bundle_products', to='catalog.productbundle')),
                ('product_product_variation', models.ForeignKey(help_text='The specific product-variation combination included in the bundle', on_delete=django.db.models.deletion.CASCADE, to='catalog.productproductvariation')),
            ],
            options={
                'verbose_name': 'Bundle Product',
                'verbose_name_plural': 'Bundle Products',
                'db_table': '"acted"."catalog_product_bundle_products"',
                'ordering': ['sort_order', 'product_product_variation__product__shortname'],
                'unique_together': {('bundle', 'product_product_variation')},
            },
        ),
        migrations.AddField(
            model_name='productbundle',
            name='product_variations',
            field=models.ManyToManyField(help_text='Product variations included in this bundle', related_name='bundles', through='catalog.ProductBundleProduct', to='catalog.productproductvariation'),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('eBook', 'eBook'), ('Hub', 'Hub'), ('Printed', 'Printed'), ('Marking', 'Marking'), ('Tutorial', 'Tutorial')], max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_short', models.CharField(blank=True, help_text='Short description for display purposes', max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
                'db_table': '"acted"."catalog_product_variations"',
                'unique_together': {('variation_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='productproductvariation',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariation'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_variations',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalog.ProductProductVariation', to='catalog.productvariation'),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='subject',
            field=models.ForeignKey(help_text='Subject this bundle is for', on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='catalog.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='productproductvariation',
            unique_together={('product', 'product_variation')},
        ),
        migrations.AlterUniqueTogether(
            name='productbundle',
            unique_together={('subject', 'bundle_name')},
        ),
    ]
