# Generated by Django 5.2.2 on 2026-01-06 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_copy_data"),
        ("products", "0004_remove_productproductvariation_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsession",
            name="end_date",
            field=models.DateTimeField(help_text="End date of the exam session period"),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="session_code",
            field=models.CharField(
                help_text="Unique session identifier (e.g., 2025-04 for April 2025)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="start_date",
            field=models.DateTimeField(
                help_text="Start date of the exam session period"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="buy_both",
            field=models.BooleanField(
                default=False,
                help_text="Suggest purchasing both eBook and Printed versions",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(help_text="Unique product code", max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed product description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fullname",
            field=models.CharField(
                help_text="Full product name for display", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="groups",
            field=models.ManyToManyField(
                help_text="Filter groups this product belongs to",
                related_name="catalog_products",
                through="catalog.ProductProductGroup",
                to="products.filtergroup",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this product is available for purchase"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_variations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Available variations for this product",
                related_name="products",
                through="catalog.ProductProductVariation",
                to="catalog.productvariation",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shortname",
            field=models.CharField(
                help_text="Short product name for compact display", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="productproductgroup",
            name="product",
            field=models.ForeignKey(
                help_text="The product being categorized",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_groups",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="productproductgroup",
            name="product_group",
            field=models.ForeignKey(
                help_text="The filter group this product belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_product_product_groups",
                to="products.filtergroup",
            ),
        ),
        migrations.AlterField(
            model_name="productproductvariation",
            name="product",
            field=models.ForeignKey(
                help_text="The product",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="productproductvariation",
            name="product_variation",
            field=models.ForeignKey(
                help_text="The variation type for this product",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.productvariation",
            ),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique variation code",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="description",
            field=models.TextField(
                blank=True, help_text="Full description of this variation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="name",
            field=models.CharField(
                help_text="Variation name (e.g., 'Standard eBook', 'Premium Printed')",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="variation_type",
            field=models.CharField(
                choices=[
                    ("eBook", "eBook"),
                    ("Hub", "Hub"),
                    ("Printed", "Printed"),
                    ("Marking", "Marking"),
                    ("Tutorial", "Tutorial"),
                ],
                help_text="Type of product variation",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Whether this subject is currently active"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(
                help_text="Unique subject code (e.g., CB1, CM2, SA1)",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.TextField(
                blank=True, help_text="Full description of the subject", null=True
            ),
        ),
    ]
