# Generated by Django 5.2.2 on 2026-01-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_product_variation_recommendation'),
        ('filtering', '0002_update_filter_group_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(help_text='Filter groups this product belongs to', related_name='catalog_products', through='catalog.ProductProductGroup', to='filtering.filtergroup'),
        ),
        migrations.AlterField(
            model_name='productproductgroup',
            name='product_group',
            field=models.ForeignKey(help_text='The filter group this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_product_product_groups', to='filtering.filtergroup'),
        ),
    ]
