# Generated by Django 6.0.1 on 2026-01-25 21:15
# Modified: Uses SeparateDatabaseAndState to transfer model ownership
# from catalog app to sub-apps without touching DB tables.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_add_exam_session_subject_product"),
        ("catalog_exam_sessions", "0001_initial"),
        ("catalog_products", "0002_initial"),
        ("catalog_products_bundles", "0002_initial"),
        ("catalog_products_recommendations", "0001_initial"),
        ("catalog_subjects", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="examsessionsubject",
                    name="exam_session",
                    field=models.ForeignKey(
                        help_text="The exam session period",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_session_subjects",
                        to="catalog_exam_sessions.examsession",
                    ),
                ),
                migrations.RemoveField(
                    model_name="product",
                    name="groups",
                ),
                migrations.RemoveField(
                    model_name="product",
                    name="product_variations",
                ),
                migrations.RemoveField(
                    model_name="productproductgroup",
                    name="product",
                ),
                migrations.AlterField(
                    model_name="examsessionsubjectproduct",
                    name="product",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_session_subject_products",
                        to="catalog_products.product",
                    ),
                ),
                migrations.RemoveField(
                    model_name="productproductvariation",
                    name="product",
                ),
                migrations.AlterUniqueTogether(
                    name="productbundle",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="productbundle",
                    name="product_variations",
                ),
                migrations.RemoveField(
                    model_name="productbundle",
                    name="subject",
                ),
                migrations.RemoveField(
                    model_name="productbundleproduct",
                    name="bundle",
                ),
                migrations.AlterUniqueTogether(
                    name="productbundleproduct",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="productbundleproduct",
                    name="product_product_variation",
                ),
                migrations.AlterUniqueTogether(
                    name="productproductgroup",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="productproductgroup",
                    name="product_group",
                ),
                migrations.AlterUniqueTogether(
                    name="productproductvariation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="productproductvariation",
                    name="product_variation",
                ),
                migrations.AlterUniqueTogether(
                    name="productvariation",
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name="productvariationrecommendation",
                    name="cat_pvr_ppv_idx",
                ),
                migrations.RemoveIndex(
                    model_name="productvariationrecommendation",
                    name="cat_pvr_rec_ppv_idx",
                ),
                migrations.AlterField(
                    model_name="examsessionsubject",
                    name="subject",
                    field=models.ForeignKey(
                        help_text="The subject available in this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_session_subjects",
                        to="catalog_subjects.subject",
                    ),
                ),
                migrations.DeleteModel(
                    name="ExamSession",
                ),
                migrations.DeleteModel(
                    name="Product",
                ),
                migrations.DeleteModel(
                    name="ProductBundle",
                ),
                migrations.DeleteModel(
                    name="ProductBundleProduct",
                ),
                migrations.DeleteModel(
                    name="ProductProductGroup",
                ),
                migrations.DeleteModel(
                    name="ProductVariation",
                ),
                migrations.RemoveField(
                    model_name="productvariationrecommendation",
                    name="product_product_variation",
                ),
                migrations.RemoveField(
                    model_name="productvariationrecommendation",
                    name="recommended_product_product_variation",
                ),
                migrations.DeleteModel(
                    name="Subject",
                ),
                migrations.DeleteModel(
                    name="ProductProductVariation",
                ),
                migrations.DeleteModel(
                    name="ProductVariationRecommendation",
                ),
            ],
            database_operations=[],
        ),
    ]
