# Generated by Django 5.2.2 on 2026-01-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VATAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this VAT calculation execution",
                        max_length=100,
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID of the VAT rule that was applied",
                        max_length=100,
                    ),
                ),
                (
                    "rule_version",
                    models.IntegerField(
                        help_text="Version of the rule that was applied"
                    ),
                ),
                (
                    "input_context",
                    models.JSONField(
                        help_text="Input context for VAT calculation (user, item, settings)"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        help_text="Output data from VAT calculation (rates, amounts, rules applied)"
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this audit record was created",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cart this VAT calculation was for (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cart.cart",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Order this VAT calculation was for (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cart.actedorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT Audit Record",
                "verbose_name_plural": "VAT Audit Records",
                "db_table": "vat_audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["execution_id"], name="vat_audit_executi_75c892_idx"
                    ),
                    models.Index(fields=["cart"], name="vat_audit_cart_id_a47124_idx"),
                    models.Index(fields=["order"], name="vat_audit_order_i_69cca6_idx"),
                    models.Index(
                        fields=["rule_id"], name="vat_audit_rule_id_9ba339_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="vat_audit_created_2d8f69_idx"
                    ),
                ],
            },
        ),
    ]
