# Generated by Django 6.0.1 on 2026-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        help_text="Full product name for display", max_length=255
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        help_text="Short product name for compact display",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed product description", null=True
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Unique product code", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this product is available for purchase",
                    ),
                ),
                (
                    "buy_both",
                    models.BooleanField(
                        default=False,
                        help_text="Suggest purchasing both eBook and Printed versions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": '"acted"."catalog_products"',
                "ordering": ["shortname"],
            },
        ),
        migrations.CreateModel(
            name="ProductProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Product Variation",
                "verbose_name_plural": "Product Product Variations",
                "db_table": '"acted"."catalog_product_product_variations"',
            },
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variation_type",
                    models.CharField(
                        choices=[
                            ("eBook", "eBook"),
                            ("Hub", "Hub"),
                            ("Printed", "Printed"),
                            ("Marking", "Marking"),
                            ("Tutorial", "Tutorial"),
                        ],
                        help_text="Type of product variation",
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Variation name (e.g., 'Standard eBook', 'Premium Printed')",
                        max_length=64,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description of this variation",
                        null=True,
                    ),
                ),
                (
                    "description_short",
                    models.CharField(
                        blank=True,
                        help_text="Short description for display purposes",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Unique variation code",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variation",
                "verbose_name_plural": "Product Variations",
                "db_table": '"acted"."catalog_product_variations"',
            },
        ),
    ]
