# Generated by Django 6.0.1 on 2026-01-25 18:30
# Modified: Fields/constraints created by catalog.0002_create_models.
# Uses SeparateDatabaseAndState to register state without DB changes.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog_products", "0001_initial"),
        ("filtering", "0006_productproductgroup"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="product",
                    name="groups",
                    field=models.ManyToManyField(
                        help_text="Filter groups this product belongs to",
                        related_name="catalog_products",
                        through="filtering.ProductProductGroup",
                        to="filtering.filtergroup",
                    ),
                ),
                migrations.AddField(
                    model_name="productproductvariation",
                    name="product",
                    field=models.ForeignKey(
                        help_text="The product",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog_products.product",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="productvariation",
                    unique_together={("variation_type", "name")},
                ),
                migrations.AddField(
                    model_name="productproductvariation",
                    name="product_variation",
                    field=models.ForeignKey(
                        help_text="The variation type for this product",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog_products.productvariation",
                    ),
                ),
                migrations.AddField(
                    model_name="product",
                    name="product_variations",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Available variations for this product",
                        related_name="products",
                        through="catalog_products.ProductProductVariation",
                        to="catalog_products.productvariation",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="productproductvariation",
                    unique_together={("product", "product_variation")},
                ),
            ],
            database_operations=[],
        ),
    ]
