# Generated by Django 6.0.1 on 2026-05-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_products", "0003_remove_product_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="productproductvariation",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this specific product+variation combo is offered for sale (default off; activate via management command)",
            ),
        ),
        migrations.AddField(
            model_name="productvariation",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this variation type is offered for sale (default off; activate via management command)",
            ),
        ),
    ]
