# Generated by Django 5.1.1 on 2024-10-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_users_options_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
    ]
