# Generated by Django 5.1.1 on 2024-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_ref',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
