# Generated by Django 5.2.2 on 2026-01-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("venue", models.CharField(max_length=255)),
                ("is_soldout", models.BooleanField(default=False)),
                ("finalisation_date", models.DateField(blank=True, null=True)),
                ("remain_space", models.IntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store_product",
                    models.ForeignKey(
                        db_column="exam_session_subject_product_variation_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorial_events",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Event",
                "verbose_name_plural": "Tutorial Events",
                "db_table": "acted_tutorial_events",
                "ordering": ["start_date", "code"],
            },
        ),
    ]
