# Generated by Django 5.1.1 on 2025-05-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions_subjects_products', '0006_price_price_type_alter_price_variation_and_more'),
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exam_session_subject_product',
            field=models.ForeignKey(default=1, help_text='Related exam session subject product for this tutorial event', on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_events', to='exam_sessions_subjects_products.examsessionsubjectproduct'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='event',
            table='acted_tutorial_events',
        ),
        migrations.AlterModelTable(
            name='session',
            table='acted_tutorial_sessions',
        ),
    ]
