# Generated by Django 5.1.1 on 2025-06-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorialevent_remove_old_models'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tutorialevent',
            table='acted_tutorial_events',
        ),
    ]
