# Generated by Django 6.0.1 on 2026-04-17 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0011_remove_staff_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialevents",
            name="main_instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutorial_events",
                to="tutorials.tutorialinstructor",
            ),
        ),
    ]
