# Generated by Django 6.0.1 on 2026-05-01 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_order_date"),
        ("students", "0002_migrate_to_acted_schema"),
        ("tutorials", "0013_drop_legacy_session_varchar_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_rank",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1st"), (2, "2nd"), (3, "3rd")]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorial_choices",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutorial_choices",
                        to="students.student",
                    ),
                ),
                (
                    "tutorial_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chosen_by",
                        to="tutorials.tutorialevents",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Choice",
                "verbose_name_plural": "Tutorial Choices",
                "db_table": '"acted"."tutorial_choices"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order_item", "choice_rank"),
                        name="uniq_choice_rank_per_order_item",
                    ),
                    models.UniqueConstraint(
                        fields=("order_item", "tutorial_event"),
                        name="uniq_event_per_order_item",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("choice_rank__in", [1, 2, 3])),
                        name="choice_rank_in_1_2_3",
                    ),
                ],
            },
        ),
    ]
