# Generated by Django 6.0.1 on 2026-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0014_tutorial_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialevents",
            name="cancelled",
            field=models.BooleanField(
                default=False,
                help_text="True for stub events that were referenced by orders but never ran (or were cancelled after orders were placed). Excluded from registration / attendance flows; kept so historical TutorialChoice rows have a valid FK target.",
            ),
        ),
    ]
