# Generated by Django 6.0.1 on 2026-05-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_drop_cart_item_legacy_fks"),
        ("students", "0002_migrate_to_acted_schema"),
        ("tutorials", "0015_tutorialevents_cancelled"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartTutorialChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_rank",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1st"), (2, "2nd"), (3, "3rd")]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorial_choices",
                        to="cart.cartitem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_tutorial_choices",
                        to="students.student",
                    ),
                ),
                (
                    "tutorial_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="in_cart_choices",
                        to="tutorials.tutorialevents",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Tutorial Choice",
                "verbose_name_plural": "Cart Tutorial Choices",
                "db_table": '"acted"."cart_tutorial_choices"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cart_item", "choice_rank"),
                        name="uniq_cart_choice_rank_per_cart_item",
                    ),
                    models.UniqueConstraint(
                        fields=("cart_item", "tutorial_event"),
                        name="uniq_cart_event_per_cart_item",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("choice_rank__in", [1, 2, 3])),
                        name="cart_choice_rank_in_1_2_3",
                    ),
                ],
            },
        ),
    ]
