# Generated by Django 6.0.1 on 2026-05-05 10:42

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_order_date"),
        ("students", "0002_migrate_to_acted_schema"),
        ("tutorials", "0015_tutorialevents_cancelled"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutorial_registrations",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutorial_registrations",
                        to="students.student",
                    ),
                ),
                (
                    "tutorial_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrations",
                        to="tutorials.tutorialchoice",
                    ),
                ),
                (
                    "tutorial_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="tutorials.tutorialsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Registration",
                "verbose_name_plural": "Tutorial Registrations",
                "db_table": '"acted"."tutorial_registrations"',
                "base_manager_name": "objects_all",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("student", "tutorial_session"),
                        name="uniq_active_reg_per_student_session",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("objects_all", django.db.models.manager.Manager()),
            ],
        ),
    ]
