# Generated by Django 6.0.1 on 2026-05-05 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0016_tutorial_registration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATTENDED", "Attended"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("recorded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_tutorial_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="tutorials.tutorialregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Attendance",
                "verbose_name_plural": "Tutorial Attendance",
                "db_table": '"acted"."tutorial_attendance"',
            },
        ),
    ]
