# Generated by Django 6.0.1 on 2026-05-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_migrate_to_acted_schema"),
        ("tutorials", "0016_cart_tutorial_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carttutorialchoice",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_tutorial_choices",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="tutorialchoice",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutorial_choices",
                to="students.student",
            ),
        ),
    ]
