# Generated by Django 6.0.1 on 2026-05-05 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0017_tutorial_attendance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialEnrolmentImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DRY_RUN", "Dry run"),
                            ("COMMITTED", "Committed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("created_count", models.IntegerField(default=0)),
                ("reactivated_count", models.IntegerField(default=0)),
                ("deactivated_count", models.IntegerField(default=0)),
                ("unmatched_count", models.IntegerField(default=0)),
                ("report", models.JSONField(blank=True, default=dict)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutorial_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Enrolment Import",
                "verbose_name_plural": "Tutorial Enrolment Imports",
                "db_table": '"acted"."tutorial_enrolment_imports"',
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
