# Generated by Django 6.0.1 on 2026-05-05 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0018_tutorial_enrolment_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialregistration",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations",
                to="tutorials.tutorialenrolmentimport",
            ),
        ),
    ]
