# Generated by Django 6.0.1 on 2026-05-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0017_allow_null_student_on_choices"),
        ("tutorials", "0019_add_import_batch_to_registration"),
    ]

    operations = []
