# Generated by Django 6.0.1 on 2026-05-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0020_merge_20260507_1455"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorialregistration",
            name="order_item",
        ),
    ]
