# Generated by Django 6.0.1 on 2026-05-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0036_merge_variable_picker_and_versioning"),
        ("tutorials", "0021_tutorial_registration_drop_order_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialAttendanceEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("token_issued_at", models.DateTimeField()),
                (
                    "email_queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="email_system.emailqueue",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tutorials.tutorialinstructor",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_email_logs",
                        to="tutorials.tutorialsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Attendance Email Log",
                "verbose_name_plural": "Tutorial Attendance Email Logs",
                "db_table": '"acted"."tutorial_attendance_email_log"',
                "unique_together": {("session", "instructor")},
            },
        ),
    ]
