# Generated by Django 6.0.1 on 2026-05-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0022_tutorial_attendance_email_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialAttendanceLinkAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("save", "Save"),
                            ("upload", "Upload"),
                            ("reject", "Reject"),
                        ],
                        max_length=16,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tutorials.tutorialinstructor",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tutorials.tutorialsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial Attendance Link Access",
                "verbose_name_plural": "Tutorial Attendance Link Accesses",
                "db_table": '"acted"."tutorial_attendance_link_access"',
                "indexes": [
                    models.Index(
                        fields=["session", "accessed_at"],
                        name="tutorial_at_session_c761d1_idx",
                    )
                ],
            },
        ),
    ]
