# Generated by Django 6.0.1 on 2026-05-12 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0023_tutorial_attendance_link_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("retry", "Retry Scheduled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "administrate_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Most recent raw GraphQL response (data + errors).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sync_jobs",
                        to="tutorials.tutorialsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Sync Job",
                "verbose_name_plural": "Attendance Sync Jobs",
                "db_table": '"acted"."attendance_sync_jobs"',
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="attendance__status_70caed_idx",
                    ),
                    models.Index(
                        fields=["session", "status"],
                        name="attendance__session_901096_idx",
                    ),
                ],
            },
        ),
    ]
