# Generated by Django 6.0.1 on 2026-05-14 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_reshape_tutorial_product"),
        ("tutorials", "0024_attendance_sync_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorialevents",
            name="store_product",
            field=models.ForeignKey(
                db_column="product_id",
                help_text="Phase 4b retarget: was store.Product, now store.TutorialProduct. The PK column (product_id) is unchanged — MTI shared PK means every TutorialProduct.pk equals its parent Product.pk, so all existing FK values still resolve.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutorial_events",
                to="store.tutorialproduct",
            ),
        ),
    ]
