# Generated by Django 6.0.1 on 2026-05-15 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrate", "0011_add_webhook_registration"),
        ("tutorials", "0025_retarget_store_product_fk_to_tutorial_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialevents",
            name="access_duration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="administrator",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="course_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutorial_events",
                to="administrate.coursetemplate",
            ),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="event_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Administrate event id (Relay base64). Unique join key between adm.events.external_id and acted.tutorial_events.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="extra_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="learning_mode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="lifecycle_state",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="lms_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="lms_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="max_places",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="min_places",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="ocr_moodle_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="recording_pin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="recordings",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="sage_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="session_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="sitting",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="sold_out",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="timezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="tutorial_category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="tutors",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="virtual_classroom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tutorialevents",
            name="web_sale",
            field=models.BooleanField(null=True),
        ),
    ]
