# Generated by Django 5.2.2 on 2025-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking_vouchers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="markingvoucher",
            name="available_from",
        ),
        migrations.RemoveField(
            model_name="markingvoucher",
            name="available_until",
        ),
        migrations.RemoveField(
            model_name="markingvoucher",
            name="max_uses_per_customer",
        ),
        migrations.RemoveField(
            model_name="markingvoucher",
            name="total_available",
        ),
        migrations.RemoveField(
            model_name="markingvoucher",
            name="vat_rate",
        ),
        migrations.AddField(
            model_name="markingvoucher",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Voucher expires after this date. Leave blank for no expiry.",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="MarkingVoucherPurchase",
        ),
    ]
