# Generated by Django 5.2.2 on 2025-07-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marking_vouchers", "0002_remove_markingvoucher_available_from_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="markingvoucher",
            table="acted_marking_vouchers",
        ),
    ]
