# Generated by Django 6.0.1 on 2026-04-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking_vouchers", "0002_migrate_to_acted_schema"),
        ("orders", "0004_order_item_backfill_purchasable"),
        ("store", "0011_price_backfill_purchasable"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuedVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_code",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_vouchers",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "purchasable",
                    models.ForeignKey(
                        help_text="Which catalog SKU this voucher was issued from (denormalised for reporting).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_vouchers",
                        to="store.purchasable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issued Voucher",
                "verbose_name_plural": "Issued Vouchers",
                "db_table": '"acted"."issued_vouchers"',
                "indexes": [
                    models.Index(
                        fields=["status"], name="issued_vouc_status_25bfbd_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="issued_vouc_expires_e89842_idx"
                    ),
                    models.Index(
                        fields=["order_item"], name="issued_vouc_order_i_ea53ee_idx"
                    ),
                ],
            },
        ),
    ]
