# Generated by Django 6.0.1 on 2026-04-29 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marking", "0009_switch_marking_voucher_to_generic_item"),
        ("marking_vouchers", "0004_drop_marking_voucher_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedeemedVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_voucher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemption",
                        to="marking_vouchers.issuedvoucher",
                    ),
                ),
                (
                    "marking_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="marking.markingpaper",
                    ),
                ),
            ],
            options={
                "verbose_name": "Redeemed Voucher",
                "verbose_name_plural": "Redeemed Vouchers",
                "db_table": '"acted"."redeemed_vouchers"',
            },
        ),
    ]
