# Generated by Django 5.2.2 on 2026-01-15 15:25
# Indexes were already created in 0001_initial - this migration is a no-op

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    """No-op migration - indexes already exist from 0001_initial."""

    dependencies = [
        ('filtering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
