# Generated by Django 5.2.2 on 2026-01-15 16:19
# No-op: indexes already exist in database

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    """No-op migration - indexes already exist."""

    dependencies = [
        ('filtering', '0002_update_filter_group_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
