# Generated by Django 5.2.2 on 2026-01-16 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filtering", "0003_add_filter_analytics_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="filterusageanalytics",
            index=models.Index(
                fields=["filter_configuration", "-usage_count"],
                name="filter_usag_filter__e51648_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filterusageanalytics",
            index=models.Index(
                fields=["last_used"], name="filter_usag_last_us_026863_idx"
            ),
        ),
    ]
