# Generated by Django 6.0.1 on 2026-01-25 18:30
# Modified: Table created by catalog.0002_create_models.
# Uses SeparateDatabaseAndState to register model without creating table.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_create_models"),
        ("catalog_products", "0001_initial"),
        ("filtering", "0005_add_product_group_filter"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ProductProductGroup",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "product",
                            models.ForeignKey(
                                help_text="The product being categorized",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="product_groups",
                                to="catalog_products.product",
                            ),
                        ),
                        (
                            "product_group",
                            models.ForeignKey(
                                help_text="The filter group this product belongs to",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="product_product_groups",
                                to="filtering.filtergroup",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Product Product Group",
                        "verbose_name_plural": "Product Product Groups",
                        "db_table": '"acted"."catalog_product_product_groups"',
                        "unique_together": {("product", "product_group")},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
