# Generated by Django 6.0.1 on 2026-04-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filtering", "0010_ppg_fk_to_product_product_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productproductgroup",
            name="product_group",
            field=models.ForeignKey(
                help_text="The filter group this product-variation belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_product_groups",
                to="filtering.filtergroup",
            ),
        ),
    ]
