# Generated by Django 6.0.1 on 2026-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filtering", "0014_clean_subject_type_fcg_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterconfiguration",
            name="filter_type",
            field=models.CharField(
                choices=[
                    ("subject", "Subject"),
                    ("subject_type", "Subject Type"),
                    ("filter_group", "Filter Group"),
                    ("product_variation", "Product Variation"),
                    ("tutorial_format", "Tutorial Format"),
                    ("tutorial_location", "Tutorial Location"),
                    ("marking_template", "Marking Template"),
                    ("bundle", "Bundle"),
                    ("custom_field", "Custom Field"),
                    ("computed", "Computed Filter"),
                    ("date_range", "Date Range"),
                    ("numeric_range", "Numeric Range"),
                ],
                help_text="Type of filter",
                max_length=32,
            ),
        ),
    ]
