# Generated by Django 5.2.7 on 2025-11-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(db_index=True, help_text='UK postcode (uppercase, no spaces)', max_length=10)),
                ('search_query', models.CharField(blank=True, help_text='Original search query string', max_length=255)),
                ('response_data', models.JSONField(help_text='Full Postcoder API response')),
                ('formatted_addresses', models.JSONField(help_text='Transformed response in getaddress.io format')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when cache entry was created')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Timestamp when cache entry expires')),
                ('hit_count', models.IntegerField(default=0, help_text='Number of times served from cache')),
            ],
            options={
                'verbose_name': 'Cached Address',
                'verbose_name_plural': 'Cached Addresses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['postcode', 'expires_at'], name='postcode_expires_idx')],
            },
        ),
    ]
