# Generated by Django 5.1.1 on 2025-03-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS adm;",
            "DROP SCHEMA IF EXISTS adm CASCADE;"
        ),
    ]
