# Generated by Django 5.1.1 on 2025-03-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0002_rename_customfield_entity__a50e73_idx_adm_custom__entity__3df6f7_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customfield',
            new_name='custom_field_entity_idx',
            old_name='adm.custom__entity__3df6f7_idx',
        ),
        migrations.RenameIndex(
            model_name='customfield',
            new_name='custom_field_extid_idx',
            old_name='adm.custom__externa_74d36b_idx',
        ),
    ]
