# Generated by Django 5.1.1 on 2025-03-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0002_create_adm_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('possible_values', models.JSONField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'db_table': 'adm.customfields',
                'indexes': [models.Index(fields=['entity_type'], name='adm.customf_entity__d3d573_idx')],
            },
        ),
    ]
