# Generated by Django 5.1.1 on 2025-03-28 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0003_customfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfield',
            old_name='is_system',
            new_name='is_restricted',
        ),
        migrations.RenameField(
            model_name='customfield',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='customfield',
            old_name='possible_values',
            new_name='options',
        ),
        migrations.AddField(
            model_name='customfield',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='definition_locator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='permission_grants',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
