# Generated by Django 5.1.1 on 2025-03-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0004_rename_is_system_customfield_is_restricted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='definition_locator',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='is_restricted',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='permission_grants',
        ),
    ]
