# Generated by Django 5.1.1 on 2025-03-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0005_remove_customfield_can_edit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='options',
        ),
    ]
