# Generated by Django 6.0.1 on 2026-02-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailqueue",
            name="duplicated_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Original queue item this was duplicated from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="email_system.emailqueue",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="mjml_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="MJML source content for the template editor",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="mjml_last_synced",
            field=models.DateTimeField(
                blank=True,
                help_text="When MJML content was last imported from file",
                null=True,
            ),
        ),
    ]
