# Generated by Django 6.0.1 on 2026-02-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0002_emailqueue_duplicated_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="is_master",
            field=models.BooleanField(
                default=False,
                help_text="Shared MJML component (master template, banner, footer, styles)",
            ),
        ),
    ]
