# Generated by Django 6.0.1 on 2026-02-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0004_seed_master_mjml_components"),
        ("tutorials", "0010_move_instructors_to_sessions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosingSalutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Salutation identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "sign_off_text",
                    models.CharField(
                        default="Kind Regards",
                        help_text="Sign-off line, e.g. 'Kind Regards'",
                        max_length=200,
                    ),
                ),
                (
                    "signature_type",
                    models.CharField(
                        choices=[("team", "Team"), ("staff", "Staff")],
                        default="team",
                        max_length=10,
                    ),
                ),
                (
                    "team_signature",
                    models.CharField(
                        blank=True,
                        help_text="Team name when signature_type is 'team'",
                        max_length=200,
                    ),
                ),
                (
                    "staff_name_format",
                    models.CharField(
                        choices=[
                            ("full_name", "Full Name"),
                            ("first_name", "First Name Only"),
                        ],
                        default="full_name",
                        help_text="How staff names are displayed",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Closing Salutation",
                "verbose_name_plural": "Closing Salutations",
                "db_table": "utils_email_closing_salutation",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="closing_salutation",
            field=models.ForeignKey(
                blank=True,
                help_text="Closing salutation block for this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="email_system.closingsalutation",
            ),
        ),
        migrations.CreateModel(
            name="ClosingSalutationStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "closing_salutation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="email_system.closingsalutation",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closing_salutations",
                        to="tutorials.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Closing Salutation Staff",
                "verbose_name_plural": "Closing Salutation Staff",
                "db_table": "utils_email_closing_salutation_staff",
                "ordering": ["display_order"],
                "unique_together": {("closing_salutation", "staff")},
            },
        ),
    ]
