# Generated by Django 6.0.1 on 2026-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0006_seed_default_closing_salutation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="content_template_name",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="mjml_last_synced",
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("password_reset", "Password Reset"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("account_activation", "Account Activation"),
                    ("welcome", "Welcome Email"),
                    ("reminder", "Reminder Email"),
                    ("notification", "System Notification"),
                    ("marketing", "Marketing Email"),
                    ("support", "Support Email"),
                    ("custom", "Custom Email"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
