# Generated by Django 6.0.1 on 2026-02-25 12:57

from django.db import migrations, models


def seed_mjml_elements(apps, schema_editor):
    EmailMjmlElement = apps.get_model('email_system', 'EmailMjmlElement')

    elements = [
        {
            'element_type': 'heading_1',
            'display_name': 'Heading 1',
            'description': 'Primary heading — centered, 21px, bold',
            'mjml_template': (
                '<mj-text padding-top="32px" padding-bottom="16px" align="center" '
                'css-class="email-title" font-size="21px">'
                '<span style="color:#2c3e50;margin:0;font-size:21px;font-weight:600">'
                '{{content}}</span></mj-text>'
            ),
        },
        {
            'element_type': 'heading_2',
            'display_name': 'Heading 2',
            'description': 'Secondary heading — centered, 18px, bold',
            'mjml_template': (
                '<mj-text padding-top="24px" padding-bottom="12px" align="center" '
                'css-class="email-subtitle" font-size="18px">'
                '<span style="color:#2c3e50;margin:0;font-size:18px;font-weight:600">'
                '{{content}}</span></mj-text>'
            ),
        },
        {
            'element_type': 'heading_3',
            'display_name': 'Heading 3',
            'description': 'Tertiary heading — left-aligned, 16px, bold',
            'mjml_template': (
                '<mj-text padding-top="16px" padding-bottom="8px" align="left" '
                'css-class="email-heading3" font-size="16px">'
                '<span style="color:#2c3e50;margin:0;font-size:16px;font-weight:600">'
                '{{content}}</span></mj-text>'
            ),
        },
        {
            'element_type': 'paragraph',
            'display_name': 'Paragraph',
            'description': 'Body text — left-aligned with bottom padding',
            'mjml_template': (
                '<mj-text padding-bottom="24px" align="left" css-class="content-text">'
                '<span>{{content}}</span></mj-text>'
            ),
        },
        {
            'element_type': 'table',
            'display_name': 'Table',
            'description': 'Styled data table with header row',
            'mjml_template': (
                '<mj-text padding="0 24px 24px 24px" align="left" css-class="order-items">'
                '<table style="width:100%;border-collapse:collapse;margin:0">'
                '<thead><tr style="background-color:#ececee;color:#2c3e50">'
                '{{headers}}</tr></thead>'
                '<tbody>{{rows}}</tbody>'
                '</table></mj-text>'
            ),
        },
        {
            'element_type': 'bold',
            'display_name': 'Bold',
            'description': 'Inline bold text',
            'mjml_template': '<strong>{{content}}</strong>',
        },
        {
            'element_type': 'italic',
            'display_name': 'Italic',
            'description': 'Inline italic text',
            'mjml_template': '<em>{{content}}</em>',
        },
        {
            'element_type': 'link',
            'display_name': 'Link',
            'description': 'Inline hyperlink',
            'mjml_template': '<a href="{{url}}" style="color:#3498db">{{content}}</a>',
        },
        {
            'element_type': 'horizontal_divider',
            'display_name': 'Horizontal Divider',
            'description': 'Visual separator line',
            'mjml_template': '<mj-divider border-color="#dee2e6" padding="16px 0" />',
        },
    ]

    for elem in elements:
        EmailMjmlElement.objects.create(**elem)


def reverse_seed(apps, schema_editor):
    EmailMjmlElement = apps.get_model('email_system', 'EmailMjmlElement')
    EmailMjmlElement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0007_remove_content_template_name_and_mjml_last_synced"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMjmlElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("heading_1", "Heading 1"),
                            ("heading_2", "Heading 2"),
                            ("heading_3", "Heading 3"),
                            ("paragraph", "Paragraph"),
                            ("table", "Table"),
                            ("bold", "Bold"),
                            ("italic", "Italic"),
                            ("link", "Link"),
                            ("horizontal_divider", "Horizontal Divider"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "mjml_template",
                    models.TextField(
                        help_text="MJML template with {{content}}, {{url}}, {{headers}}, {{rows}} placeholders"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "utils_email_mjml_element",
                "ordering": ["element_type"],
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="basic_mode_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Markdown source for Basic Mode editing. Empty = Advanced Mode only.",
            ),
        ),
        migrations.RunPython(seed_mjml_elements, reverse_seed),
    ]
