# Generated by Django 6.0.1 on 2026-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0010_revise_closing_salutation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("password_reset", "Password Reset"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("account_activation", "Account Activation"),
                    ("email_verification", "Email Verification"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
