# Generated by Django 6.0.1 on 2026-03-25 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0011_alter_emailtemplate_template_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalApiKey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the API key",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 chars for admin identification", max_length=8
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this API key", max_length=200
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "External API Key",
                "verbose_name_plural": "External API Keys",
                "db_table": "utils_external_api_key",
            },
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("password_reset", "Password Reset"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("account_activation", "Account Activation"),
                    ("email_verification", "Email Verification"),
                    ("batch_completion_report", "Batch Completion Report"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="EmailBatch",
            fields=[
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requested_by", models.CharField(max_length=200)),
                ("notify_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with Errors"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="email_system.emailtemplate",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="email_system.externalapikey",
                    ),
                ),
            ],
            options={
                "db_table": "utils_email_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Batch this email belongs to, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queue_items",
                to="email_system.emailbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="emailbatch",
            index=models.Index(
                fields=["api_key", "created_at"], name="utils_email_api_key_7b7121_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailbatch",
            index=models.Index(fields=["status"], name="utils_email_status_f7bc93_idx"),
        ),
    ]
