# Generated by Django 6.0.1 on 2026-03-25 21:34

from django.db import migrations


def create_batch_completion_template(apps, schema_editor):
    EmailTemplate = apps.get_model('email_system', 'EmailTemplate')
    EmailTemplate.objects.get_or_create(
        name='batch_completion_report',
        defaults={
            'display_name': 'Batch Completion Report',
            'template_type': 'batch_completion_report',
            'subject_template': 'Email Batch {{ batch_id }} - {{ sent_count }}/{{ total_items }} sent',
            'is_active': True,
            'enable_queue': True,
            'use_master_template': False,
            'basic_mode_content': (
                '# Email Batch Report\n\n'
                '**Requested by:** {{ requested_by }}\n\n'
                '**Batch ID:** {{ batch_id }}\n\n'
                '**Results:** {{ sent_count }} sent, {{ error_count }} errors out of {{ total_items }} total\n\n'
                '{% if error_items %}## Errors\n\n'
                '{% for item in error_items %}'
                '- **{{ item.to_email }}** - {{ item.attempts }} attempts - {{ item.error_response.error_message }}\n'
                '{% endfor %}{% endif %}'
            ),
        },
    )


def reverse_migration(apps, schema_editor):
    EmailTemplate = apps.get_model('email_system', 'EmailTemplate')
    EmailTemplate.objects.filter(name='batch_completion_report').delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "email_system",
            "0012_externalapikey_alter_emailtemplate_template_type_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(create_batch_completion_template, reverse_migration),
    ]
