# Generated by Django 6.0.1 on 2026-03-30 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0015_db_driven_email_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMasterComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Component identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("master_template", "Master Template"),
                            ("banner", "Banner"),
                            ("footer", "Footer"),
                            ("styles", "Styles"),
                            ("closing", "Closing"),
                            ("dev_mode_banner", "Dev Mode Banner"),
                        ],
                        help_text="Type of shared component",
                        max_length=50,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Component description and purpose"
                    ),
                ),
                (
                    "mjml_content",
                    models.TextField(default="", help_text="MJML source content"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_email_master_components",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Master Component",
                "verbose_name_plural": "Email Master Components",
                "db_table": '"acted"."email_master_components"',
                "ordering": ["component_type", "name"],
            },
        ),
    ]
