# Generated by Django 6.0.1 on 2026-03-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0018_remove_emailtemplate_is_master"),
        ("staff", "0002_create_team_and_team_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="closingsalutation",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member used when signature_type is 'staff'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closing_salutations",
                to="staff.staff",
            ),
        ),
        migrations.DeleteModel(
            name="ClosingSalutationStaff",
        ),
    ]
