# Generated by Django 6.0.1 on 2026-03-31 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0021_rename_to_utils_email_master_components"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailbatch",
            name="notify_email",
        ),
        migrations.AddField(
            model_name="emailbatch",
            name="notify_emails",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of emails to receive batch completion report",
            ),
        ),
        migrations.AddField(
            model_name="externalapikey",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Django user linked to this API key",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
