# Generated by Django 6.0.1 on 2026-03-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0022_apikey_user_fk_and_batch_notify_emails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="closingsalutation",
            name="signature_type",
        ),
        migrations.RemoveField(
            model_name="closingsalutation",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="closingsalutation",
            name="team",
        ),
        migrations.AddField(
            model_name="closingsalutation",
            name="job_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Job title shown below the signature (optional)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="closingsalutation",
            name="display_name",
            field=models.CharField(
                help_text="Signature name shown in the email", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="closingsalutation",
            name="sign_off_text",
            field=models.CharField(
                blank=True,
                default="Kind Regards",
                help_text="Sign-off line (e.g. 'Kind Regards', 'Best Wishes')",
                max_length=200,
            ),
        ),
    ]
