# Generated by Django 6.0.1 on 2026-03-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0023_simplify_closing_salutation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="enhance_outlook_compatibility",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="max_retry_attempts",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="retry_delay_minutes",
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("order_confirmation", "Order Confirmation"),
                    ("password_reset", "Password Reset"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("account_activation", "Account Activation"),
                    ("email_verification", "Email Verification"),
                    ("batch_completion_report", "Batch Completion Report"),
                    ("materials", "Materials"),
                    ("marking", "Marking"),
                    ("tutorials", "Tutorials"),
                    ("apprentice", "Apprentice"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
