# Generated by Django 6.0.1 on 2026-03-31 14:26

from django.db import migrations


def seed_email_settings(apps, schema_editor):
    EmailSettings = apps.get_model('email_system', 'EmailSettings')
    defaults = [
        {
            'key': 'max_retry_attempts',
            'setting_type': 'queue',
            'display_name': 'Max Retry Attempts',
            'description': 'Maximum number of retry attempts for failed emails',
            'value': '3',
            'default_value': '3',
        },
        {
            'key': 'retry_delay_minutes',
            'setting_type': 'queue',
            'display_name': 'Retry Delay (Minutes)',
            'description': 'Delay in minutes between email retry attempts',
            'value': '5',
            'default_value': '5',
        },
        {
            'key': 'enhance_outlook_compatibility',
            'setting_type': 'template',
            'display_name': 'Enhance Outlook Compatibility',
            'description': 'Apply Outlook-specific HTML enhancements when sending emails',
            'value': 'true',
            'default_value': 'true',
        },
    ]
    for item in defaults:
        EmailSettings.objects.get_or_create(key=item['key'], defaults=item)


def reverse_seed(apps, schema_editor):
    EmailSettings = apps.get_model('email_system', 'EmailSettings')
    EmailSettings.objects.filter(
        key__in=['max_retry_attempts', 'retry_delay_minutes', 'enhance_outlook_compatibility']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0024_move_retry_outlook_to_settings"),
    ]

    operations = [
        migrations.RunPython(seed_email_settings, reverse_seed),
    ]
