# Generated by Django 6.0.1 on 2026-04-01 09:01

from django.db import migrations, models


def create_attributes_component(apps, schema_editor):
    EmailMasterComponent = apps.get_model('email_system', 'EmailMasterComponent')

    # Only create if it doesn't exist
    if not EmailMasterComponent.objects.filter(name='attributes').exists():
        EmailMasterComponent.objects.create(
            name='attributes',
            component_type='attributes',
            display_name='Attributes',
            description='MJML mj-class definitions placed inside <mj-attributes>. Controls element styling via class names.',
            mjml_content=(
                '<mj-class name="email-title" padding-top="32px" padding-bottom="32px" font-size="21px" font-weight="600" color="#4d4d4d" />\n'
                '<mj-class name="h1" padding-top="24px" padding-bottom="24px" font-size="32px" />\n'
                '<mj-class name="h2" padding-top="20px" padding-bottom="20px" font-size="26px" />\n'
                '<mj-class name="h3" padding-top="16px" padding-bottom="16px" font-size="20px" />\n'
                '<mj-class name="primary-button" />\n'
                '<mj-class name="secondary-button" />\n'
                '<mj-class name="link" />\n'
                '<mj-class name="divider" />\n'
                '<mj-class name="table" />\n'
                '<mj-class name="text-center" align="center" />\n'
                '<mj-class name="text-start" align="left" />\n'
                '<mj-class name="text-right" align="right" />\n'
                '<mj-class name="ul" align="left" />\n'
                '<mj-class name="ol" align="left" />\n'
                '<mj-class name="callout-info" />\n'
                '<mj-class name="callout-warning" />\n'
                '<mj-class name="callout-success" />\n'
                '<mj-class name="callout-error" />\n'
                '<mj-class name="callout-section" />\n'
                '<mj-class name="accordian" />\n'
            ),
            is_active=True,
        )


def reverse_create_attributes(apps, schema_editor):
    EmailMasterComponent = apps.get_model('email_system', 'EmailMasterComponent')
    EmailMasterComponent.objects.filter(name='attributes').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0025_seed_retry_outlook_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmastercomponent",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("master_template", "Master Template"),
                    ("banner", "Banner"),
                    ("footer", "Footer"),
                    ("styles", "Styles"),
                    ("attributes", "Attributes"),
                    ("closing", "Closing"),
                    ("dev_mode_banner", "Dev Mode Banner"),
                ],
                help_text="Type of shared component",
                max_length=50,
            ),
        ),
        migrations.RunPython(create_attributes_component, reverse_create_attributes),
    ]
