# Generated by Django 6.0.1 on 2026-04-01 09:04

from django.db import migrations, models


def update_and_seed_elements(apps, schema_editor):
    EmailMjmlElement = apps.get_model('email_system', 'EmailMjmlElement')

    # Update existing elements to use mj-class
    updates = {
        'heading_1': '<mj-text mj-class="email-title">{{content}}</mj-text>',
        'heading_2': '<mj-text mj-class="h2">{{content}}</mj-text>',
        'heading_3': '<mj-text mj-class="h3">{{content}}</mj-text>',
        'paragraph': '<mj-text>{{content}}</mj-text>',
        'table': (
            '<mj-text mj-class="table">'
            '<table style="width:100%;border-collapse:collapse;margin:0">'
            '<thead><tr>{{headers}}</tr></thead>'
            '<tbody>{{rows}}</tbody>'
            '</table></mj-text>'
        ),
    }
    for element_type, template in updates.items():
        EmailMjmlElement.objects.filter(element_type=element_type).update(
            mjml_template=template
        )

    # Create new elements
    new_elements = [
        {
            'element_type': 'unordered_list',
            'display_name': 'Unordered List',
            'description': 'Bullet list',
            'mjml_template': '<mj-text mj-class="ul"><ul>{{items}}</ul></mj-text>',
        },
        {
            'element_type': 'ordered_list',
            'display_name': 'Ordered List',
            'description': 'Numbered list',
            'mjml_template': '<mj-text mj-class="ol"><ol>{{items}}</ol></mj-text>',
        },
        {
            'element_type': 'callout_info',
            'display_name': 'Callout (Info)',
            'description': 'Information callout box',
            'mjml_template': '<mj-text mj-class="callout-info">{{content}}</mj-text>',
        },
        {
            'element_type': 'callout_warning',
            'display_name': 'Callout (Warning)',
            'description': 'Warning callout box',
            'mjml_template': '<mj-text mj-class="callout-warning">{{content}}</mj-text>',
        },
        {
            'element_type': 'callout_success',
            'display_name': 'Callout (Success)',
            'description': 'Success callout box',
            'mjml_template': '<mj-text mj-class="callout-success">{{content}}</mj-text>',
        },
        {
            'element_type': 'callout_error',
            'display_name': 'Callout (Error)',
            'description': 'Error callout box',
            'mjml_template': '<mj-text mj-class="callout-error">{{content}}</mj-text>',
        },
    ]
    for elem in new_elements:
        EmailMjmlElement.objects.get_or_create(
            element_type=elem['element_type'],
            defaults=elem,
        )


def reverse_update(apps, schema_editor):
    EmailMjmlElement = apps.get_model('email_system', 'EmailMjmlElement')
    EmailMjmlElement.objects.filter(element_type__in=[
        'unordered_list', 'ordered_list',
        'callout_info', 'callout_warning', 'callout_success', 'callout_error',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0026_add_attributes_component"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmjmlelement",
            name="element_type",
            field=models.CharField(
                choices=[
                    ("heading_1", "Heading 1"),
                    ("heading_2", "Heading 2"),
                    ("heading_3", "Heading 3"),
                    ("paragraph", "Paragraph"),
                    ("table", "Table"),
                    ("bold", "Bold"),
                    ("italic", "Italic"),
                    ("link", "Link"),
                    ("horizontal_divider", "Horizontal Divider"),
                    ("unordered_list", "Unordered List"),
                    ("ordered_list", "Ordered List"),
                    ("callout_info", "Callout (Info)"),
                    ("callout_warning", "Callout (Warning)"),
                    ("callout_success", "Callout (Success)"),
                    ("callout_error", "Callout (Error)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.RunPython(update_and_seed_elements, reverse_update),
    ]
