# Generated by Django 6.0.1 on 2026-04-02 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0027_update_mjml_elements_mj_class"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("subject_template", models.CharField(max_length=300)),
                ("mjml_content", models.TextField(blank=True, default="")),
                ("basic_mode_content", models.TextField(blank=True, default="")),
                (
                    "closing_sign_off",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "closing_display_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "closing_job_title",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional note describing what changed in this version",
                        max_length=500,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="email_system.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template Version",
                "verbose_name_plural": "Email Template Versions",
                "db_table": "utils_email_template_version",
                "ordering": ["template", "-version_number"],
                "unique_together": {("template", "version_number")},
            },
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="template_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Exact template version used when this email was queued",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queue_items",
                to="email_system.emailtemplateversion",
            ),
        ),
    ]
