# Generated by Django 6.0.1 on 2026-04-02

from django.db import migrations


def add_content_section_class(apps, schema_editor):
    """Add content-section mj-class to the attributes component if not present."""
    EmailMasterComponent = apps.get_model('email_system', 'EmailMasterComponent')

    try:
        attrs = EmailMasterComponent.objects.get(name='attributes')
    except EmailMasterComponent.DoesNotExist:
        return

    if 'content-section' not in attrs.mjml_content:
        attrs.mjml_content = (
            '<mj-class name="content-section" padding="0" />\n'
            + attrs.mjml_content
        )
        attrs.save(update_fields=['mjml_content'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0027_update_mjml_elements_mj_class"),
    ]

    operations = [
        migrations.RunPython(add_content_section_class, noop),
    ]
