# Generated by Django 6.0.1 on 2026-04-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0028_reset_element_templates_add_content_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable label shown in the template editor (e.g. 'First Name')",
                        max_length=100,
                    ),
                ),
                (
                    "variable_path",
                    models.CharField(
                        help_text="Dot-notation path used in templates (e.g. 'user.first_name')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("bool", "Boolean"),
                        ],
                        default="string",
                        help_text="Expected data type for payload validation",
                        max_length=20,
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default value when payload omits this variable",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Help text for staff editing templates",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Variable",
                "verbose_name_plural": "Email Variables",
                "db_table": "utils_email_variables",
                "ordering": ["variable_path"],
            },
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="payload_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Auto-generated schema from template variables. Used for batch send payload validation.",
            ),
        ),
    ]
