# Generated by Django 6.0.1 on 2026-04-02 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0028_add_template_versioning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailqueue",
            name="content_override_basic",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Basic mode (markdown) source for the content override",
            ),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="content_override_mjml",
            field=models.TextField(
                blank=True,
                default="",
                help_text="MJML content override for this specific queue item",
            ),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailqueue",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_queue_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
