# Generated by Django 6.0.1 on 2026-04-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0029_add_queue_item_content_editing"),
        ("email_system", "0030_update_batch_completion_report_with_status_table"),
    ]

    operations = []
