# Generated by Django 6.0.1 on 2026-04-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0032_move_content_to_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("USER", "User"),
                    ("MATERIALS", "Materials"),
                    ("MARKING", "Marking"),
                    ("TUTORIALS", "Tutorials"),
                    ("APPRENTICE", "Apprentice"),
                    ("STUDYPLUS", "Study Plus"),
                    ("SYSTEM", "System"),
                    ("order_confirmation", "Order Confirmation"),
                    ("password_reset", "Password Reset"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("account_activation", "Account Activation"),
                    ("email_verification", "Email Verification"),
                    ("batch_completion_report", "Batch Completion Report"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
