# Generated by Django 6.0.1 on 2026-04-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0033_alter_emailtemplate_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("USER", "User"),
                    ("MATERIALS", "Materials"),
                    ("MARKING", "Marking"),
                    ("TUTORIALS", "Tutorials"),
                    ("APPRENTICE", "Apprentice"),
                    ("STUDYPLUS", "Study Plus"),
                    ("SYSTEM", "System"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
