# Generated by Django 6.0.1 on 2026-04-08 09:34

from django.conf import settings
from django.db import migrations, models


def normalize_legacy_template_types(apps, schema_editor):
    """Normalize stale template_type values seeded by earlier migrations.

    Migration 0013 seeded an EmailTemplate row with
    template_type='batch_completion_report' — a legacy value from before the
    enum was restricted to category codes. This row violates the CheckConstraint
    added later in this migration, so normalize it to 'SYSTEM' before the
    constraint is applied.
    """
    EmailTemplate = apps.get_model("email_system", "EmailTemplate")
    allowed = {"ORDER", "USER", "MATERIALS", "MARKING", "TUTORIALS",
               "APPRENTICE", "STUDYPLUS", "SYSTEM"}
    EmailTemplate.objects.exclude(template_type__in=allowed).update(
        template_type="SYSTEM"
    )


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op — original stale values cannot be recovered."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0034_alter_emailtemplate_template_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            normalize_legacy_template_types,
            noop_reverse,
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("USER", "User"),
                    ("MATERIALS", "Materials"),
                    ("MARKING", "Marking"),
                    ("TUTORIALS", "Tutorials"),
                    ("APPRENTICE", "Apprentice"),
                    ("STUDYPLUS", "Study Plus"),
                    ("SYSTEM", "System"),
                ],
                default="SYSTEM",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="emailtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "template_type__in",
                        [
                            "ORDER",
                            "USER",
                            "MATERIALS",
                            "MARKING",
                            "TUTORIALS",
                            "APPRENTICE",
                            "STUDYPLUS",
                            "SYSTEM",
                        ],
                    )
                ),
                name="email_template_type_valid",
            ),
        ),
    ]
