# Generated by Django 6.0.1 on 2026-04-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0033_email_variable_consolidate_arrays"),
        ("email_system", "0035_alter_emailtemplate_template_type_and_more"),
    ]

    operations = []
