# Generated by Django 6.0.1 on 2026-05-12 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0037_seed_tutorial_attendance_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailQueueAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Filename shown to the recipient.", max_length=255
                    ),
                ),
                ("content", models.BinaryField(help_text="Raw attachment bytes.")),
                (
                    "mime_type",
                    models.CharField(
                        default="application/octet-stream",
                        help_text="MIME type of the attachment.",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "queue_item",
                    models.ForeignKey(
                        help_text="Queue row this attachment belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_attachments",
                        to="email_system.emailqueue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Queue Attachment",
                "verbose_name_plural": "Email Queue Attachments",
                "db_table": "utils_email_queue_attachment",
                "ordering": ["queue_item_id", "id"],
            },
        ),
    ]
