# Generated by Django 6.0.1 on 2026-01-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog_products", "0001_initial"),
        ("catalog_subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bundle_name",
                    models.CharField(
                        help_text="Name of the bundle (e.g., 'CM1 Materials & Marking Bundle')",
                        max_length=255,
                    ),
                ),
                (
                    "bundle_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what's included in the bundle",
                        null=True,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to feature this bundle prominently",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this bundle is currently available",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which to display this bundle"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject this bundle is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="catalog_subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Bundle",
                "verbose_name_plural": "Product Bundles",
                "db_table": '"acted"."catalog_product_bundles"',
                "ordering": ["subject__code", "display_order", "bundle_name"],
            },
        ),
        migrations.CreateModel(
            name="ProductBundleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_price_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("retaker", "Retaker"),
                            ("additional", "Additional Copy"),
                        ],
                        default="standard",
                        help_text="Default price type for this product when added via bundle",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of this product to add when bundle is selected",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of this product within the bundle",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this product is currently active in the bundle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle",
                    models.ForeignKey(
                        help_text="The bundle this product belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_products",
                        to="catalog_products_bundles.productbundle",
                    ),
                ),
                (
                    "product_product_variation",
                    models.ForeignKey(
                        help_text="The specific product-variation combination included in the bundle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog_products.productproductvariation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bundle Product",
                "verbose_name_plural": "Bundle Products",
                "db_table": '"acted"."catalog_product_bundle_products"',
                "ordering": [
                    "sort_order",
                    "product_product_variation__product__shortname",
                ],
                "unique_together": {("bundle", "product_product_variation")},
            },
        ),
        migrations.AddField(
            model_name="productbundle",
            name="product_variations",
            field=models.ManyToManyField(
                help_text="Product variations included in this bundle",
                related_name="bundles",
                through="catalog_products_bundles.ProductBundleProduct",
                to="catalog_products.productproductvariation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productbundle",
            unique_together={("subject", "bundle_name")},
        ),
    ]
