# Generated by Django 6.0.1 on 2026-01-25 18:30
# Modified: Fields/constraints created by catalog.0002_create_models.
# Uses SeparateDatabaseAndState to register state without DB changes.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog_products_bundles", "0001_initial"),
        ("catalog_products", "0002_initial"),
        ("catalog_subjects", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="productbundleproduct",
                    name="bundle",
                    field=models.ForeignKey(
                        help_text="The bundle this product belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_products",
                        to="catalog_products_bundles.productbundle",
                    ),
                ),
                migrations.AddField(
                    model_name="productbundleproduct",
                    name="product_product_variation",
                    field=models.ForeignKey(
                        help_text="The specific product-variation combination included in the bundle",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog_products.productproductvariation",
                    ),
                ),
                migrations.AddField(
                    model_name="productbundle",
                    name="subject",
                    field=models.ForeignKey(
                        help_text="Subject this bundle is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="catalog_subjects.subject",
                    ),
                ),
                migrations.AddField(
                    model_name="productbundle",
                    name="product_variations",
                    field=models.ManyToManyField(
                        help_text="Product variations included in this bundle",
                        related_name="bundles",
                        through="catalog_products_bundles.ProductBundleProduct",
                        to="catalog_products.productproductvariation",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="productbundleproduct",
                    unique_together={("bundle", "product_product_variation")},
                ),
                migrations.AlterUniqueTogether(
                    name="productbundle",
                    unique_together={("subject", "bundle_name")},
                ),
            ],
            database_operations=[],
        ),
    ]
