"""
Django settings for django_Admin3 project.

Generated by 'django-admin startproject django_Admin3' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
# settings.py

from datetime import timedelta
import os
from pathlib import Path
import sys
import environ

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False),    
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, []),
    CRSF_ALLOWED_ORIGINS=(list, []),
)

# Read .env file if it exists
# Determine environment from DJANGO_SETTINGS_MODULE if DJANGO_ENV not set
settings_module = os.environ.get('DJANGO_SETTINGS_MODULE', '')
if not os.getenv('DJANGO_ENV') and settings_module:
    if 'uat' in settings_module:
        os.environ.setdefault('DJANGO_ENV', 'uat')
    elif 'production' in settings_module:
        os.environ.setdefault('DJANGO_ENV', 'production')
    elif 'development' in settings_module:
        os.environ.setdefault('DJANGO_ENV', 'development')

DJANGO_ENV = os.getenv('DJANGO_ENV', 'development')
print(f'DJANGO_ENV {DJANGO_ENV}')
print(f'DJANGO_SETTINGS_MODULE {settings_module}')
env_file = os.path.join(BASE_DIR, f'.env.{DJANGO_ENV}')
print(f'DJANGO_ENV FILE {env_file}')
if os.path.exists(env_file):
    print(f'Loading environment from: {env_file}')
    environ.Env.read_env(env_file)
else:
    print(f'Warning: {env_file} not found!')

# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Use environment variables
DEBUG = env('DEBUG')

# Static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'


# Paths to the certificate and key files
CERT_FILE = os.path.join(BASE_DIR, 'certs', 'elo_cert.pem')
# KEY_FILE = os.path.join(BASE_DIR, 'certs', 'key.pem')

# HTTPS settings for development
if os.getenv('DJANGO_DEVELOPMENT') == 'true':
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-5rn#bj-51$-9c1fmwnn8yfguq#v@17a0z5-zi2a&+$u3&famf$'

# Environment-based settings
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'  # Default to True for development
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-5rn#bj-51$-9c1fmwnn8yfguq#v@17a0z5-zi2a&+$u3&famf$')


# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')


# Application definition
INSTALLED_APPS = [
    'users',
    'userprofile',
    'country',
    'cart',
    'students',
    'subjects',
    'tutorials',
    'exam_sessions',
    'exam_sessions_subjects',
    'exam_sessions_subjects_products',
    'products.apps.ProductsConfig',
    'marking',
    'marking_vouchers',
    'core_auth',
    'administrate.apps.AdministrateConfig',
    'rules_engine.apps.RulesEngineConfig',
    'utils.apps.UtilsConfig',  # Added utils app for email functionality
    'vat',  # Epic 3: VAT calculation and audit trail
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be before CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'django_Admin3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Add your templates directory
            os.path.join(BASE_DIR, 'administrate', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_Admin3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'ACTEDDBDEV01'),
        'USER': os.environ.get('DB_USER', 'actedadmin'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Act3d@dm1n0EEoo'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}
# if 'test' in sys.argv:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': ':memory:'
#         }
#     }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8888",
    "http://127.0.0.1:8888"
]
CRSF_ALLOWED_ORIGINS = os.environ.get('CRSF_ALLOWED_ORIGINS', '').split(',')

# Allow credentials (cookies) to be included in requests
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT"
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with"
]

AUTH_USER_MODEL = 'auth.User'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50
}

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_COOKIE_SECURE = True  # Use only with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True  # Ensure session persists across requests

# Add JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}


# GraphQL Template Settings
GRAPHQL_TEMPLATES_DIR = os.path.join(
    BASE_DIR, 'administrate/templates/graphql')

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Use Gmail SMTP for testing
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')  # Your email address
EMAIL_HOST_PASSWORD = os.environ.get(
    'EMAIL_HOST_PASSWORD', '')  # Your app password
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@acted.com')

# For development, you can use console backend for testing
# DISABLED: Uncomment below to print emails to console instead of sending
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Password Reset Settings
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://127.0.0.1:3000')
PASSWORD_RESET_TIMEOUT_HOURS = float(os.environ.get('PASSWORD_RESET_TIMEOUT_HOURS', '0.25'))  # 0.25 hours = 15 minutes
PASSWORD_RESET_TIMEOUT = 900  # 15 minutes in seconds for Django's token validation

# reCAPTCHA v3 Settings
RECAPTCHA_SITE_KEY = os.environ.get('RECAPTCHA_SITE_KEY', '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')  # Test key for development
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')  # Test secret key for development
RECAPTCHA_VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify'

# reCAPTCHA v3 Configuration
RECAPTCHA_VERSION = '3'  # Specify version 3
RECAPTCHA_DEFAULT_MIN_SCORE = float(os.environ.get('RECAPTCHA_MIN_SCORE', '0.5'))  # Default minimum score
RECAPTCHA_ACTIONS = {
    'password_reset': 'password_reset',
    'login': 'login', 
    'registration': 'registration',
    'contact_form': 'contact'
}

# Administrate API Settings
# ADMINISTRATE_INSTANCE_URL = env('ADMINISTRATE_INSTANCE_URL')
# ADMINISTRATE_API_URL = env('ADMINISTRATE_API_URL')
# ADMINISTRATE_API_KEY = env('ADMINISTRATE_API_KEY')
# ADMINISTRATE_API_SECRET = env('ADMINISTRATE_API_SECRET')
# ADMINISTRATE_REST_API_URL = env('ADMINISTRATE_REST_API_URL')

