# Generated by Django 5.1.1 on 2025-03-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_alter_student_apprentice_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='acted_students',
        ),
    ]
