# Generated by Django 5.2.7 on 2025-11-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressLookupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(db_index=True, help_text='UK postcode searched', max_length=10)),
                ('search_query', models.CharField(blank=True, help_text='Additional search text (if any)', max_length=255)),
                ('lookup_timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the lookup was performed')),
                ('cache_hit', models.BooleanField(db_index=True, help_text='Whether result was served from cache')),
                ('response_time_ms', models.IntegerField(help_text='Total response time in milliseconds')),
                ('result_count', models.IntegerField(help_text='Number of addresses returned')),
                ('api_provider', models.CharField(db_index=True, default='postcoder', help_text="Which API was used ('postcoder' or 'getaddress')", max_length=20)),
                ('success', models.BooleanField(db_index=True, help_text='Whether the lookup succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error details if lookup failed', null=True)),
            ],
            options={
                'verbose_name': 'Address Lookup Log',
                'verbose_name_plural': 'Address Lookup Logs',
                'ordering': ['-lookup_timestamp'],
                'indexes': [models.Index(fields=['lookup_timestamp', 'api_provider'], name='timestamp_provider_idx')],
            },
        ),
    ]
