# Generated by Django 5.2.2 on 2025-09-18 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0002_add_dismissible_to_message_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference_key",
                    models.CharField(
                        help_text="Unique key identifying this preference",
                        max_length=100,
                    ),
                ),
                (
                    "preference_value",
                    models.JSONField(
                        default=dict,
                        help_text="User's preference value(s) stored as JSON",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("radio", "Radio Button"),
                            ("checkbox", "Checkbox"),
                            ("text", "Text Input"),
                            ("textarea", "Text Area"),
                            ("select", "Dropdown Select"),
                            ("custom", "Custom Input"),
                        ],
                        default="text",
                        help_text="Type of input used to collect this preference",
                        max_length=20,
                    ),
                ),
                (
                    "display_mode",
                    models.CharField(
                        choices=[
                            ("inline", "Inline Display"),
                            ("modal", "Modal Dialog"),
                        ],
                        default="inline",
                        help_text="How the preference was displayed to the user",
                        max_length=20,
                    ),
                ),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this preference blocks checkout until completed",
                    ),
                ),
                (
                    "is_submitted",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user has submitted this preference",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "session_data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional session context when preference was saved",
                    ),
                ),
                (
                    "message_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules_engine.messagetemplate",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rules_engine.actedrule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "acted_rules_user_preferences",
                "indexes": [
                    models.Index(
                        fields=["user", "rule"], name="acted_rules_user_id_86f349_idx"
                    ),
                    models.Index(
                        fields=["preference_key"], name="acted_rules_prefere_f5ef06_idx"
                    ),
                    models.Index(
                        fields=["submitted_at"], name="acted_rules_submitt_caac40_idx"
                    ),
                ],
                "unique_together": {("user", "rule", "preference_key")},
            },
        ),
    ]
