# Generated by Django 5.2.2 on 2025-09-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0003_userpreference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentstyle",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="messagetemplatestyle",
            name="custom_styles",
        ),
        migrations.RemoveField(
            model_name="messagetemplatestyle",
            name="theme",
        ),
        migrations.DeleteModel(
            name="HolidayCalendar",
        ),
        migrations.RemoveField(
            model_name="messagetemplatestyle",
            name="message_template",
        ),
        migrations.DeleteModel(
            name="ContentStyle",
        ),
        migrations.DeleteModel(
            name="ContentStyleTheme",
        ),
        migrations.DeleteModel(
            name="MessageTemplateStyle",
        ),
    ]
