# Generated by Django 5.2.2 on 2025-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0003_alter_messagetemplate_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rulecondition",
            name="operator",
            field=models.CharField(
                choices=[
                    ("equals", "Equals"),
                    ("not_equals", "Not Equals"),
                    ("contains", "Contains"),
                    ("not_contains", "Does Not Contain"),
                    ("greater_than", "Greater Than"),
                    ("less_than", "Less Than"),
                    ("between", "Between"),
                    ("in_list", "In List"),
                    ("not_in_list", "Not In List"),
                    ("regex", "Regular Expression"),
                    ("custom_function", "Custom Function"),
                ],
                max_length=20,
            ),
        ),
    ]
