# Generated by Django 5.2.2 on 2025-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0004_alter_rulecondition_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="useracknowledgment",
            name="acknowledgment_type",
            field=models.CharField(
                choices=[
                    ("required", "Required Acknowledgment"),
                    ("optional", "Optional Selection"),
                    ("preference", "User Preference"),
                ],
                default="required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="useracknowledgment",
            name="is_selected",
            field=models.BooleanField(
                default=False,
                help_text="For optional rules, whether user selected this option",
            ),
        ),
        migrations.AddField(
            model_name="useracknowledgment",
            name="session_data",
            field=models.JSONField(
                default=dict, help_text="Additional session context"
            ),
        ),
    ]
