# Generated by Django 5.2.2 on 2025-06-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0005_useracknowledgment_acknowledgment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("show_message", "Show Message"),
                    ("require_acknowledgment", "Require Acknowledgment"),
                    ("redirect", "Redirect"),
                    ("send_email", "Send Email"),
                    ("log_event", "Log Event"),
                    ("custom_function", "Custom Function"),
                    ("calculate_vat", "Calculate VAT"),
                    ("apply_discount", "Apply Discount"),
                    ("calculate_fee", "Calculate Fee"),
                ],
                max_length=30,
            ),
        ),
    ]
