# Generated by Django 5.2.2 on 2025-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0006_schema_field_updates"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="actedrule",
            name="acted_rules_rule_id",
        ),
        migrations.RemoveIndex(
            model_name="actedruleexecution",
            name="acted_exec_rule_created",
        ),
        migrations.RemoveField(
            model_name="actedrule",
            name="rule_id",
        ),
        migrations.AlterField(
            model_name="actedrule",
            name="rules_fields_code",
            field=models.CharField(
                blank=True,
                help_text="Code of the ActedRulesFields schema for context validation",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="actedruleexecution",
            name="execution_seq_no",
            field=models.CharField(
                blank=True,
                help_text="Unique execution sequence number",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
