# Generated by Django 5.2.2 on 2025-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0007_remove_actedrule_acted_rules_rule_id_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="actedruleexecution",
            index=models.Index(
                fields=["rule_code", "created_at"], name="acted_exec_rule_created"
            ),
        ),
    ]
