# Generated by Django 5.2.2 on 2025-10-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0008_actedruleexecution_acted_exec_rule_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleentrypoint",
            name="code",
            field=models.CharField(
                choices=[
                    ("home_page_mount", "Home Page Mount"),
                    ("product_list_mount", "Product List Mount"),
                    ("product_card_mount", "Product Card Mount"),
                    ("checkout_start", "Checkout Start"),
                    ("checkout_preference", "Checkout Preference"),
                    ("checkout_terms", "Checkout Terms"),
                    ("checkout_payment", "Checkout Payment"),
                    ("user_registration", "User Registration"),
                    ("cart_calculate_vat", "Cart Calculate VAT"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
