# Generated by Django 5.2.2 on 2025-08-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0008_rules_engine_refinements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rulechain",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rulechainlink",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="condition_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional condition group this condition belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="rules_engine.ruleconditiongroup",
            ),
        ),
        migrations.AlterField(
            model_name="ruleconditiongroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ruleconditiongroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent group for nested conditions",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_groups",
                to="rules_engine.ruleconditiongroup",
            ),
        ),
    ]
