# Generated by Django 5.2.2 on 2025-08-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0009_alter_rulechain_id_alter_rulechainlink_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="content_format",
            field=models.CharField(
                choices=[
                    ("html", "HTML Content"),
                    ("json", "JSON Structure"),
                    ("markdown", "Markdown"),
                ],
                default="html",
                help_text="Format of the content field",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="json_content",
            field=models.JSONField(
                blank=True,
                help_text="Structured JSON content for rendering with Material UI components",
                null=True,
            ),
        ),
    ]
