# Generated by Django 5.2.2 on 2025-08-06 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0010_add_json_content_to_message_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentStyleTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Content Style Theme",
                "verbose_name_plural": "Content Style Themes",
                "db_table": "acted_content_style_themes",
            },
        ),
        migrations.CreateModel(
            name="ContentStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this style",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("container", "Container"),
                            ("box", "Box"),
                            ("p", "Paragraph"),
                            ("h1", "Heading 1"),
                            ("h2", "Heading 2"),
                            ("h3", "Heading 3"),
                            ("h4", "Heading 4"),
                            ("h5", "Heading 5"),
                            ("h6", "Heading 6"),
                            ("ul", "Unordered List"),
                            ("ol", "Ordered List"),
                            ("li", "List Item"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("alert", "Alert/Notice"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                            ("info", "Information"),
                            ("holiday", "Holiday Notice"),
                            ("terms", "Terms & Conditions"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "css_class_selector",
                    models.CharField(
                        blank=True,
                        help_text="CSS class that triggers this style (e.g., 'alert alert-warning')",
                        max_length=200,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="e.g., #fff3cd, rgba(255,243,205,1)",
                        max_length=20,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True, help_text="e.g., #856404, #000000", max_length=20
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        blank=True, help_text="e.g., #ffeaa7", max_length=20
                    ),
                ),
                (
                    "border_width",
                    models.CharField(
                        default="1px", help_text="e.g., 1px, 2px, 0", max_length=10
                    ),
                ),
                (
                    "border_radius",
                    models.CharField(
                        default="4px", help_text="e.g., 4px, 8px, 0", max_length=10
                    ),
                ),
                (
                    "padding",
                    models.CharField(
                        default="12px 16px",
                        help_text="e.g., 12px 16px, 10px",
                        max_length=20,
                    ),
                ),
                (
                    "margin",
                    models.CharField(
                        default="0 0 16px 0",
                        help_text="e.g., 0 0 16px 0, 10px",
                        max_length=20,
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 14px, 1.2rem, inherit",
                        max_length=10,
                    ),
                ),
                (
                    "font_weight",
                    models.CharField(
                        blank=True, help_text="e.g., normal, bold, 600", max_length=10
                    ),
                ),
                (
                    "text_align",
                    models.CharField(
                        default="left",
                        help_text="left, center, right, justify",
                        max_length=10,
                    ),
                ),
                (
                    "custom_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional CSS properties as JSON (e.g., {'boxShadow': '0 2px 4px rgba(0,0,0,0.1)'})",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Higher numbers = higher priority when multiple styles match",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="styles",
                        to="rules_engine.contentstyletheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Style",
                "verbose_name_plural": "Content Styles",
                "db_table": "acted_content_styles",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplateStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_styles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Override specific styles for this template",
                        to="rules_engine.contentstyle",
                    ),
                ),
                (
                    "message_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_config",
                        to="rules_engine.messagetemplate",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rules_engine.contentstyletheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Template Style",
                "verbose_name_plural": "Message Template Styles",
                "db_table": "acted_message_template_styles",
            },
        ),
    ]
