# Generated by Django 5.2.2 on 2025-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules_engine", "0011_add_dynamic_styling_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rulecondition",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("product_category", "Product Category"),
                    ("product_code", "Product Code"),
                    ("product_type", "Product Type"),
                    ("user_type", "User Type"),
                    ("date_range", "Date Range"),
                    ("holiday_proximity", "Holiday Proximity"),
                    ("cart_value", "Cart Value"),
                    ("cart_item_count", "Cart Item Count"),
                    ("user_order_history", "User Order History"),
                    ("custom_field", "Custom Field"),
                    ("user_country", "User Country"),
                    ("user_home_address", "User Home Address"),
                    ("user_home_email", "User Home Email"),
                    ("user_work_address", "User Work Address"),
                    ("user_work_email", "User Work Email"),
                    ("user_is_reduced_rate", "User Is Reduced Rate"),
                    ("user_is_apprentice", "User Is Apprentice"),
                    ("user_is_caa", "User Is CAA"),
                    ("user_is_study_plus", "User Is Study Plus"),
                    ("cart_has_material", "Cart Has Material"),
                    ("cart_has_marking", "Cart Has Marking"),
                    ("cart_has_tutorial", "Cart Has Tutorial"),
                    ("product_variations", "Product Variations"),
                    ("material_despatch_date", "Material Despatch Date"),
                    ("marking_expired_deadlines", "Marking Expired Deadlines"),
                    ("tutorial_has_started", "Tutorial Has Started"),
                    (
                        "exam_session_transition_period",
                        "Exam Session Transition Period",
                    ),
                    ("date_xmas", "Christmas Period"),
                    ("date_easter", "Easter Period"),
                    ("checkout_payment_method", "Checkout Payment Method"),
                    ("checkout_employer_code", "Checkout Employer Code"),
                    ("cart_item_expired_deadline", "Cart Item Has Expired Deadline"),
                ],
                max_length=30,
            ),
        ),
    ]
