# Generated by Django 6.0.1 on 2026-01-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog_products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_product_variation",
                    models.OneToOneField(
                        help_text="Source product-variation combination that makes the recommendation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="catalog_products.productproductvariation",
                    ),
                ),
                (
                    "recommended_product_product_variation",
                    models.ForeignKey(
                        help_text="Recommended complementary product-variation combination",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_by",
                        to="catalog_products.productproductvariation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variation Recommendation",
                "verbose_name_plural": "Product Variation Recommendations",
                "db_table": '"acted"."product_productvariation_recommendations"',
                "indexes": [
                    models.Index(
                        fields=["product_product_variation"], name="cat_pvr_ppv_idx"
                    ),
                    models.Index(
                        fields=["recommended_product_product_variation"],
                        name="cat_pvr_rec_ppv_idx",
                    ),
                ],
            },
        ),
    ]
