# Generated by Django 5.1.1 on 2025-05-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'acted_products',
                'ordering': ['shortname'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'acted_product_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'acted_product_main_category',
            },
        ),
        migrations.CreateModel(
            name='ProductProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
            options={
                'db_table': 'acted_product_productcategory',
                'unique_together': {('product', 'product_category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_categories',
            field=models.ManyToManyField(related_name='products', through='products.ProductProductCategory', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductProductMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmaincategory')),
            ],
            options={
                'db_table': 'acted_product_productmaincategory',
                'unique_together': {('product', 'product_main_category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_main_categories',
            field=models.ManyToManyField(related_name='products', through='products.ProductProductMainCategory', to='products.productmaincategory'),
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product Subcategory',
                'verbose_name_plural': 'Product Subcategories',
                'db_table': 'acted_product_subcategories',
                'unique_together': {('product_category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubcategory')),
            ],
            options={
                'db_table': 'acted_product_productsubcategory',
                'unique_together': {('product', 'product_subcategory')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcategories',
            field=models.ManyToManyField(related_name='products', through='products.ProductProductSubcategory', to='products.productsubcategory'),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('format', 'Format'), ('delivery', 'Delivery Method')], max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
                'db_table': 'acted_product_variations',
                'unique_together': {('variation_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation')),
            ],
            options={
                'db_table': 'acted_product_productvariation',
                'unique_together': {('product', 'product_variation')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_variations',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductProductVariation', to='products.productvariation'),
        ),
    ]
