# Generated by Django 5.1.1 on 2025-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='code',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation_type',
            field=models.CharField(choices=[('eBook', 'eBook'), ('Hub', 'Hub'), ('Printed', 'Printed'), ('Marking', 'Marking'), ('Tutorial', 'Tutorial')], max_length=32),
        ),
    ]
