# Generated by Django 5.1.1 on 2025-04-30 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_subtype',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.CreateModel(
            name='ProductProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
            options={
                'db_table': 'acted_product_productcategory',
                'unique_together': {('product', 'product_category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_categories',
            field=models.ManyToManyField(related_name='products', through='products.ProductProductCategory', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductProductSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsubtype')),
            ],
            options={
                'db_table': 'acted_product_productsubtype',
                'unique_together': {('product', 'product_subtype')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_subtypes',
            field=models.ManyToManyField(related_name='products', through='products.ProductProductSubtype', to='products.productsubtype'),
        ),
        migrations.CreateModel(
            name='ProductProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
            ],
            options={
                'db_table': 'acted_product_producttype',
                'unique_together': {('product', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_types',
            field=models.ManyToManyField(related_name='products', through='products.ProductProductType', to='products.producttype'),
        ),
    ]
