# Generated by Django 5.2.2 on 2025-10-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_product_variation', models.OneToOneField(help_text='Source product-variation combination that makes the recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='products.productproductvariation')),
                ('recommended_product_product_variation', models.ForeignKey(help_text='Recommended complementary product-variation combination', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='products.productproductvariation')),
            ],
            options={
                'verbose_name': 'Product Variation Recommendation',
                'verbose_name_plural': 'Product Variation Recommendations',
                'db_table': 'acted_product_productvariation_recommendations',
                'indexes': [models.Index(fields=['product_product_variation'], name='acted_produ_product_7fbfa4_idx'), models.Index(fields=['recommended_product_product_variation'], name='acted_produ_recomme_0a59f2_idx')],
            },
        ),
    ]
