# Generated by Django 5.1.1 on 2025-05-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategory',
            table='acted_product_category',
        ),
        migrations.AlterModelTable(
            name='productsubcategory',
            table='acted_product_subcategory',
        ),
    ]
