# Generated by Django 5.1.1 on 2025-05-01 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_product_subtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'acted_product_main_category',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subtypes',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['shortname'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_types',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='acted_product_categories',
        ),
        migrations.AlterModelTable(
            name='productproductmaincategory',
            table='acted_product_productmaincategory',
        ),
        migrations.AlterModelTable(
            name='productproductsubcategory',
            table='acted_product_productsubcategory',
        ),
        migrations.RenameModel(
            old_name='ProductProductSubtype',
            new_name='ProductProductMainCategory',
        ),
        migrations.AlterUniqueTogether(
            name='productproductmaincategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='product_main_categories',
            field=models.ManyToManyField(related_name='products', through='products.ProductProductMainCategory', to='products.productmaincategory'),
        ),
        migrations.AddField(
            model_name='productproductmaincategory',
            name='product_main_category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='products.productmaincategory'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productproductmaincategory',
            unique_together={('product', 'product_main_category')},
        ),
        migrations.RenameModel(
            old_name='ProductType',
            new_name='ProductCategory',
        ),
        migrations.RenameModel(
            old_name='ProductProductType',
            new_name='ProductProductSubcategory',
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product Subcategory',
                'verbose_name_plural': 'Product Subcategories',
                'db_table': 'acted_product_subcategories',
                'unique_together': {('product_category', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productproductsubcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcategories',
            field=models.ManyToManyField(related_name='products', through='products.ProductProductSubcategory', to='products.productsubcategory'),
        ),
        migrations.AddField(
            model_name='productproductsubcategory',
            name='product_subcategory',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='products.productsubcategory'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productproductsubcategory',
            unique_together={('product', 'product_subcategory')},
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('format', 'Format'), ('delivery', 'Delivery Method')], max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
                'db_table': 'acted_product_variations',
                'unique_together': {('variation_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation')),
            ],
            options={
                'db_table': 'acted_product_productvariation',
                'unique_together': {('product', 'product_variation')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_variations',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductProductVariation', to='products.productvariation'),
        ),
        migrations.DeleteModel(
            name='ProductSubtype',
        ),
        migrations.RemoveField(
            model_name='productproductmaincategory',
            name='product_subtype',
        ),
        migrations.RemoveField(
            model_name='productproductsubcategory',
            name='product_type',
        ),
    ]
