# Generated by Django 5.1.1 on 2025-05-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='products.productcategory'),
        ),
    ]
