# Generated by Django 5.1.1 on 2025-05-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productsubcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaincategory',
            name='order_sequence',
        ),
    ]
