# Generated by Django 5.2.2 on 2025-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productvariation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="description_short",
            field=models.CharField(
                blank=True,
                help_text="Short description for display purposes",
                max_length=255,
                null=True,
            ),
        ),
    ]
