# Generated by Django 5.1.1 on 2025-05-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productmaincategory_order_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.productmaincategory'),
        ),
        migrations.AddField(
            model_name='productmaincategory',
            name='order_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
