# Generated by Django 5.1.1 on 2025-05-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcategory_main_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaincategory',
            name='order_sequence',
        ),
    ]
