# Generated by Django 5.1.1 on 2025-05-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productmaincategory_order_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaincategory',
            name='order_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
