# Generated by Django 5.2.2 on 2025-07-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_configurable_filters"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="filterusageanalytics",
            new_name="acted_filte_filter__0dbb6f_idx",
            old_name="acted_filter_usage_analytics_filter_configuration_usage_count_idx",
        ),
        migrations.RenameIndex(
            model_name="filterusageanalytics",
            new_name="acted_filte_last_us_ec5d9c_idx",
            old_name="acted_filter_usage_analytics_last_used_idx",
        ),
    ]
