# Generated by Django 5.1.1 on 2025-05-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_main_categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcategories',
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productgroup')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'db_table': 'acted_product_group',
            },
        ),
        migrations.CreateModel(
            name='ProductProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup')),
            ],
            options={
                'db_table': 'acted_product_productgroup',
                'unique_together': {('product', 'product_group')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(related_name='products', through='products.ProductProductGroup', to='products.productgroup'),
        ),
    ]
