# Generated by Django 5.1.1 on 2025-05-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_product_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroupFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filter_type', models.CharField(choices=[('type', 'Product Type'), ('delivery', 'Delivery Method'), ('custom', 'Custom')], max_length=32)),
                ('groups', models.ManyToManyField(related_name='filters', to='products.productgroup')),
            ],
            options={
                'verbose_name': 'Product Group Filter',
                'verbose_name_plural': 'Product Group Filters',
                'db_table': 'acted_product_group_filter',
            },
        ),
    ]
