# Generated by Django 5.2.2 on 2025-07-15 23:04

from django.db import migrations


def remove_obsolete_tables(apps, schema_editor):
    """Remove obsolete filter tables"""
    from django.db import connection
    
    obsolete_tables = [
        'acted_filter_configuration',
        'acted_filter_option_provider', 
        'acted_filter_preset',
        'acted_filter_usage_analytics',
        'acted_product_group_filter',
        'acted_product_group_filter_groups'
    ]
    
    with connection.cursor() as cursor:
        for table in obsolete_tables:
            try:
                cursor.execute(f"DROP TABLE IF EXISTS {table} CASCADE;")
                print(f"Dropped table: {table}")
            except Exception as e:
                print(f"Error dropping table {table}: {e}")


def restore_obsolete_tables(apps, schema_editor):
    """This is a one-way migration - cannot restore deleted tables"""
    print("Cannot restore obsolete tables - this is a one-way migration")


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_refactored_filter_system"),
    ]

    operations = [
        migrations.RunPython(
            remove_obsolete_tables,
            restore_obsolete_tables,
        ),
    ]
