# Generated by Django 5.1.1 on 2025-05-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productgroupfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroupfilter',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filter_group', to='products.productgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgroupfilter',
            name='type',
            field=models.CharField(default='OTHERS', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productgroupfilter',
            name='groups',
            field=models.ManyToManyField(related_name='filter_groups', to='products.productgroup'),
        ),
    ]
