# Generated by Django 5.1.1 on 2025-05-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productgroupfilter_group_productgroupfilter_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroupfilter',
            name='group',
        ),
        migrations.RemoveField(
            model_name='productgroupfilter',
            name='type',
        ),
    ]
