# Generated by Django 5.2.2 on 2025-07-16 09:49

from django.db import migrations


class Migration(migrations.Migration):
    """
    Empty migration to sync Django's migration state with the current 
    database state after manual model renames.
    """

    dependencies = [
        ("products", "0013_update_product_group_references"),
    ]

    operations = [
        # Empty - the database is already in the correct state
        # This migration just tells Django that the current state is correct
    ]
