# Generated by Django 5.2.2 on 2025-07-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_current_state_sync"),
    ]

    operations = [
        # This migration is a no-op as the models are already in the correct state
        # The previous migration 0014_current_state_sync already synced the database
        # with the current model definitions
    ]
