# Generated by Django 5.2.2 on 2025-07-16 10:40

from django.db import migrations


class Migration(migrations.Migration):
    """
    Final sync migration to ensure database state matches the current models.
    This migration assumes the database is already in the correct state after
    the previous refactoring operations.
    """

    dependencies = [
        ("products", "0015_rename_refactoredfilterconfigurationgroup_filterconfigurationgroup_and_more"),
    ]

    operations = [
        # Empty migration - the database should already be in the correct state
        # This just updates Django's migration tracking to match the current models
    ]