# Generated by Django 5.2.2 on 2025-07-16 10:45

from django.db import migrations


def mark_migration_as_applied(apps, schema_editor):
    """
    This migration marks the database as being in the correct state.
    The actual database changes were done manually/through previous migrations.
    """
    pass


class Migration(migrations.Migration):
    """
    This migration assumes the database is already in the correct state
    and just updates Django's migration tracking to reflect the current models.
    """

    dependencies = [
        ("products", "0016_final_sync"),
    ]

    operations = [
        migrations.RunPython(mark_migration_as_applied, migrations.RunPython.noop),
    ]