# Generated by Django 5.2.2 on 2025-07-16 10:41

from django.db import migrations


class Migration(migrations.Migration):
    """
    Fix Django's model state tracking for FilterConfigurationGroup.
    
    The issue is that Django's migration state believes the model is still called
    RefactoredFilterConfigurationGroup (from migration 0010), but the current
    models.py has FilterConfigurationGroup. This migration uses RenameModel
    to properly update Django's migration state without actually changing the
    database (since the table was already renamed by previous migrations).
    """

    dependencies = [
        ("products", "0017_final_state_migration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RefactoredFilterConfiguration",
            new_name="FilterConfiguration",
        ),
        migrations.RenameModel(
            old_name="RefactoredFilterConfigurationGroup",
            new_name="FilterConfigurationGroup",
        ),
        migrations.RenameModel(
            old_name="RefactoredFilterPreset",
            new_name="FilterPreset",
        ),
        migrations.RenameModel(
            old_name="RefactoredFilterUsageAnalytics",
            new_name="FilterUsageAnalytics",
        ),
    ]
