# Generated by Django 5.2.2 on 2025-07-16 10:44

from django.db import migrations


def remove_filter_option_provider_table(apps, schema_editor):
    """
    Remove the FilterOptionProvider table if it exists.
    This model was created but is no longer needed.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        try:
            cursor.execute("DROP TABLE IF EXISTS acted_filter_option_provider CASCADE;")
            print("Dropped acted_filter_option_provider table")
        except Exception as e:
            print(f"Error dropping table: {e}")


class Migration(migrations.Migration):
    """
    Remove the FilterOptionProvider model and table.
    This model was created in migration 0008 but is no longer needed.
    """

    dependencies = [
        ("products", "0018_fix_model_state"),
    ]

    operations = [
        migrations.RunPython(
            remove_filter_option_provider_table,
            migrations.RunPython.noop,
        ),
        # Use SeparateDatabaseAndState to only affect Django's migration state
        # without trying to modify the database
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations needed - table already doesn't exist
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="FilterOptionProvider",
                ),
            ]
        ),
    ]
