# Generated by Django 5.2.2 on 2025-07-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_remove_filter_option_provider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filterconfiguration",
            options={
                "ordering": ["display_order", "display_label"],
                "verbose_name": "Filter Configuration",
                "verbose_name_plural": "Filter Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="filterconfigurationgroup",
            options={
                "ordering": ["display_order", "filter_group__name"],
                "verbose_name": "Filter Configuration Group",
                "verbose_name_plural": "Filter Configuration Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="filterpreset",
            options={
                "ordering": ["-usage_count", "name"],
                "verbose_name": "Filter Preset",
                "verbose_name_plural": "Filter Presets",
            },
        ),
        migrations.AlterModelOptions(
            name="filterusageanalytics",
            options={
                "verbose_name": "Filter Usage Analytics",
                "verbose_name_plural": "Filter Usage Analytics",
            },
        ),
        migrations.RenameIndex(
            model_name="filterusageanalytics",
            new_name="acted_filte_filter__0dbb6f_idx",
            old_name="acted_refac_filter__06283c_idx",
        ),
        migrations.RenameIndex(
            model_name="filterusageanalytics",
            new_name="acted_filte_last_us_ec5d9c_idx",
            old_name="acted_refac_last_us_a9c1a2_idx",
        ),
        migrations.AlterField(
            model_name="product",
            name="groups",
            field=models.ManyToManyField(
                related_name="products",
                through="products.ProductProductGroup",
                to="products.filtergroup",
            ),
        ),
        migrations.AlterField(
            model_name="productproductgroup",
            name="product_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.filtergroup"
            ),
        ),
    ]
