# Generated by Django 5.2.2 on 2025-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_sync_final_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterconfiguration",
            name="filter_type",
            field=models.CharField(
                choices=[
                    ("subject", "Subject"),
                    ("filter_group", "Filter Group"),
                    ("product_variation", "Product Variation"),
                    ("tutorial_format", "Tutorial Format"),
                    ("bundle", "Bundle"),
                    ("custom_field", "Custom Field"),
                    ("computed", "Computed Filter"),
                    ("date_range", "Date Range"),
                    ("numeric_range", "Numeric Range"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="filterconfiguration",
            name="ui_component",
            field=models.CharField(
                choices=[
                    ("multi_select", "Multi-Select Checkboxes"),
                    ("single_select", "Single Select Dropdown"),
                    ("checkbox", "Single Checkbox"),
                    ("radio_buttons", "Radio Buttons"),
                    ("toggle_buttons", "Toggle Buttons"),
                    ("search_select", "Searchable Select"),
                    ("tree_select", "Hierarchical Tree Select"),
                    ("range_slider", "Range Slider"),
                    ("date_picker", "Date Picker"),
                    ("tag_input", "Tag Input"),
                ],
                default="multi_select",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="productgroupfilter",
            name="groups",
            field=models.ManyToManyField(
                related_name="filter_groups", to="products.filtergroup"
            ),
        ),
        migrations.DeleteModel(
            name="ProductGroup",
        ),
    ]
