# Generated by Django 5.2.2 on 2025-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_alter_filterconfiguration_filter_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="buy_both",
            field=models.BooleanField(default=False),
        ),
    ]
