# Generated by Django 5.2.2 on 2025-08-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_remove_obsolete_product_group_tables"),
        ("products", "0022_product_buy_both"),
    ]

    operations = []
