# Generated by Django 5.2.2 on 2025-09-01 12:39

from django.db import migrations


def noop(apps, schema_editor):
    """
    No-op migration - models already removed in previous migrations.
    This migration is kept for consistency in migration history.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_merge_20250828_1455"),
    ]

    operations = [
        migrations.RunPython(noop, reverse_code=noop),
    ]