# Generated by Django 5.0.7 on 2024-09-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
        migrations.AlterModelTable(
            name='usercontactnumber',
            table='User_Contact_Number',
        ),
        migrations.AlterModelTable(
            name='useremail',
            table='User_Email',
        ),
    ]
